### ISSUE TITLE
Bug in ConvexSolver with inequality constraints but no equality constraints

### ISSUE THREAD

**Issue by innuo** [optimatika/ojAlgo#10]
Hi,

I recently upgraded to v38.2 of Ojalgo for solving some quadratic programs. It seems that somewhere in the code there is an assumption that whenever there are inequality constraints there must be at least one equality constraint. My problem has a bunch of inequality constraints but no equality constraints and running it gives a "divide by zero" error. Again, this only seems to manifest itself when there are inequality constraints but no equality constraints.

I have reproduced it below with a simple example. 

scala> val P = Array(Array(1.0, 0), Array(0, 1.0))
val c = Array(0.0, 0.0)
val Q = PrimitiveDenseStore.FACTORY.rows(P:_*).builder().build()
val C = PrimitiveDenseStore.FACTORY.columns(c).builder().build()
val myBuilderI = new ConvexSolver.Builder(Q, C)

val ai = Array(Array(1.0, 1.0))
val rhs = Array(1.0)

myBuilderI.inequalities(PrimitiveDenseStore.FACTORY.rows(ai:_*).builder().build(), PrimitiveDenseStore.FACTORY.columns(rhs).builder().build())

val prob = myBuilderI.build()
val solved = prob.solve()

scala> java.lang.ArithmeticException: / by zero
  at org.ojalgo.matrix.store.PrimitiveDenseStore.fillByMultiplying(PrimitiveDenseStore.java:1199)
  at org.ojalgo.matrix.store.MatrixStore.multiply(MatrixStore.java:438)
  at org.ojalgo.matrix.store.MatrixStore.multiply(MatrixStore.java:432)
  at org.ojalgo.optimisation.convex.ActiveSetSolver.performIteration(ActiveSetSolver.java:412)
  at org.ojalgo.optimisation.convex.ConvexSolver.solve(ConvexSolver.java:310)
  at org.ojalgo.optimisation.Optimisation$Solver.solve(Optimisation.java:383)

**Comment by apete** [comment]
I believe this has been fixed (and there is a simple workaround).

https://sourceforge.net/p/ojalgo/mailman/message/34442573/

Is it possible you get the latest source from either GitHub or SourceForge to verify if the problem is still there?

If there sill is a problem that needs to be fixed I would overmuch appreciate a test case that demonstrates the problem . something immediately executable.

**Comment by innuo** [comment]
Thanks for the quick response, Anders. I don't know if this is the same problem as the other question. The divide by zero seems to go away when I add a dummy equality constraint with (0 * x = 0) but the solution returned is incorrect.

I attached a simple example to my question that gives the error. You should be able to copy and paste those statements into a scala shell to reproduce it.

I have not tested the latest github repo. I have reverted to an earlier version for the time being (v31). I will try out the github experiment when I can find some time.

**Comment by innuo** [comment]
Here is an experiment with adding a dummy equality constraint to avoid the / by zero error. Unfortunately it gives the wrong solution.

The problem (with the dummy constraint) is minimize x^2 + y^2, s.t. x+y <= -1 and 0.x + 0.y = 0.0 

and it returns the solution
solved: org.ojalgo.optimisation.Optimisation.Result = OPTIMAL 0.5 @ [-1.0, 0.0]

However, clearly the point [-0.5, -0.5] has a lower objective value (while satisfying the constraint). See below the code that generated the solution.
-------------------
import org.ojalgo.matrix.store.PrimitiveDenseStore
import org.ojalgo.optimisation.convex.ConvexSolver

val P = Array(Array(1.0, 0), Array(0, 1.0))
val c = Array(0.0, 0.0)
val Q = PrimitiveDenseStore.FACTORY.rows(P:_*).builder().build()
val C = PrimitiveDenseStore.FACTORY.columns(c).builder().build()
val myBuilderI = new ConvexSolver.Builder(Q, C)

val ai = Array(Array(1.0, 1.0))
val bi = Array(-1.0)

val ae = Array(Array(0.0, 0))
val be = Array(0.0)

myBuilderI.inequalities(PrimitiveDenseStore.FACTORY.rows(ai:_*).builder().build(), PrimitiveDenseStore.FACTORY.columns(bi).builder().build())
myBuilderI.equalities(PrimitiveDenseStore.FACTORY.rows(ae:_*).builder().build(), PrimitiveDenseStore.FACTORY.columns(be).builder().build())

val prob = myBuilderI.build()
val solved = prob.solve()

**Comment by apete** [comment]
I created a Java test case from that Scala code snippet you provided. (ojAlgo is a Java project. Why do you assume I have a Scala shell?)

There is no problem with the current head/master. I'm sure this was the same problem as the one I mentioned before. There is a simple workaround. You add 1 obviously redundant inequality constraint.

You added an equality constraint instead, and it's not redundant - it's degenerate!

I'll release v38.3 or v39 soon, but right now there are just too many things not quite finished.

**Comment by innuo** [comment]
Thanks for your suggestions. For now I will stick with the older version and wait for the next release. I did some further testing of the recommended workaround (i.e. adding a redundant inequality constraint) and decided that it doesn't work. In case you are interested, adding the redundant constraint and solving

minimize x^2 + y^2, s.t. x+y <= -1, x+y <= 0  

gives the following error

java.lang.ArrayIndexOutOfBoundsException: 0
  at org.ojalgo.array.PrimitiveArray.set(PrimitiveArray.java:513)
  at org.ojalgo.array.DenseArray.set(DenseArray.java:114)
  at org.ojalgo.array.Array2D.set(Array2D.java:527)
  at org.ojalgo.matrix.store.PrimitiveDenseStore.set(PrimitiveDenseStore.java:1535)
  at org.ojalgo.optimisation.BaseSolver$AbstractBuilder.setLI(BaseSolver.java:438)
  at org.ojalgo.optimisation.convex.ConvexSolver$Builder.setLI(ConvexSolver.java:70)
  at org.ojalgo.optimisation.BaseSolver.setLI(BaseSolver.java:912)
  at org.ojalgo.optimisation.convex.ActiveSetSolver.performIteration(ActiveSetSolver.java:457)
  at org.ojalgo.optimisation.convex.ConvexSolver.solve(ConvexSolver.java:310)
  at org.ojalgo.optimisation.Optimisation$Solver.solve(Optimisation.java:383)
  ... 35 elided
