### ISSUE TITLE
Preallocation matrix is reset to zeroes in fillByMultiplication(left, right) and mutliply(right, target)

### ISSUE THREAD

**Issue by slang03** [optimatika/ojAlgo#102]
The following code example
```java
PhysicalStore.Factory<Double, PrimitiveDenseStore> factory = PrimitiveDenseStore.FACTORY;
int n = 11; // Has to be > 10 as n <= 10 uses optimized multiplication primitives
PrimitiveDenseStore matrix = factory.makeFilled(n,  n, new Weibull(5.0, 2.0));
for (int i = 0; i < 3; i++) {
  matrix.multiply(matrix, matrix);
}
BasicLogger.debug("Matrix result", matrix);
```

results in the following unexpected behavior:
```
Matrix result
 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0
```

This comes from `PrimitiveMultiplyNeither#invoke` as it first [overwrites the preallocated array with zeroes](https://github.com/optimatika/ojAlgo/blob/ebc875167d9870a298aa5796763b19a5c7d5ea43/src/org/ojalgo/matrix/store/operation/MultiplyNeither.java#L41).

The above can be fixed by replacing 
```java
matrix.multiply(matrix, matrix);
```
with
```java 
matrix.copy().multiply(matrix.copy(), matrix);
```
which eliminates the intention behind using a preallocated matrix to store the result in.

Is there a way around this?

**Comment by apete** [comment]
In your example the left, right and preallocated results matrices are all the same - the exact same instance. Why do you expect that to work?

I would expect that the left and right matrices are not modified and that the results matrix is.

**Comment by slang03** [comment]
Ah ok, I think I understand why my use-case cannot work. 
I'm in the following situation:
```python
mat = init() // [n x n] matrix
for i in 1..iter:
  other = get_other() // [n x n] matrix
  mat.multiply(other, mat)
```
And to eliminate the overhead of a new `[n x n]` matrix allocation I wanted to do the multiplication in-place. But that obviously does not work since the in-place multiplication would overwrite values that are necessary for other elements of the same matrix.
