### ISSUE TITLE
Efficient Elementwise Multiplication

### ISSUE THREAD

**Issue by slang03** [optimatika/ojAlgo#103]
`MatrixStore<N>` currently lacks the possibility to do elementwise multiplication, that is `C_ij = A_ij * B_ij`.

**Comment by apete** [comment]
It may not obvious how to do it, but the feature is there. Look for the word "matching" in the method name.

`matrixStore.operateOnMatching(MULTIPLY, anotherStore).get();`

or

```
        PhysicalStore<Double> result = matrixStore.copy();
        result.modifyMatching(MULTIPLY, anotherStore);
```

**Comment by slang03** [comment]
That's it, thank you!
