### ISSUE TITLE
MatrixDecomposition.EconomySize<>.setFullSize does not work.

### ISSUE THREAD

**Issue by prubin73** [optimatika/ojAlgo#104]
While trying to use matrix decompositions to find a basis for the kernel of a rectangular matrix, I have run into two problems with the setFullSize() method.

1. Invoking setFullSize(true) on a SingularValue<Double> instance seems to have no effect. Calling isFullSize() immediately afterward returns false.

2. While setFullSize(true) nominally works on a QR<Double> instance (in that isFullSize() returns true), it does not produce a Q matrix of the expected size.

The attached code sample and output file demonstrate the problems. The second occurs when the initial matrix has more columns than rows. Adding rows of zeros to make the matrix square produces the desired result, but should not be necessary.

[ojAlgoTest.zip](https://github.com/optimatika/ojAlgo/files/2107213/ojAlgoTest.zip)

**Comment by apete** [comment]
I've already looked at this a bit, and found more than one problem. Will most likely release a v45.1.1 once I've decided what to do about them. You should still be able to get the nullspace as is done in this test case:

https://github.com/optimatika/ojAlgo/blob/b691155d77cf265257f3b296297de020ad6b6cfc/test/org/ojalgo/matrix/decomposition/DesignCase.java#L125-L155

When you call `SingularValue.PRIMITIVE.make(2000,2000);` make sure the example dimensions are large to make that factory method return the correct implementation. The implementation normally returned for smaller matrices has a problem.

**Comment by prubin73** [comment]
Thanks for the quick response. I tested the QR code from the test case on my 5 x 7 test matrix, and it worked. With the SVD code, I did not see where the dimensions are entered in the test code. However, line 137 in the test code does not compile for me, which makes me wonder if it uses something that has changed between the production version I have (45.1.0) and the code for which the test case is written.
I changed the right-hand side of the assignment in line 137 to `SingularValue.PRIMITIVE.make(2000,2000)`, which worked, and then experimented a bit. For my 5 x 7 matrix, it works with dimensions 1100 x 1100, but with dimensions 1000 x 1000 it gives only one of three kernel basis vectors (dropping Q2 from 7 x 7 to 5 x 7). So the question is how to know in advance what dimensions to specify to the constructor. My production code will be working with matrices row and column dimensions in the low thousands. Would this require 1E6 x 1E6 dimensions in the constructor? (Unfortunately, some of them have funky numerics, so the QR approach may not be sufficiently accurate.)

**Comment by apete** [comment]
I believe this is fixed now in :

https://github.com/optimatika/ojAlgo/tree/hotfix/EconomySizeNotWorking

I turned that test code of yours into a junit test:

https://github.com/optimatika/ojAlgo/blob/e72b15c93ab8761fab3dad855a32d7f10984abd4/test/org/ojalgo/matrix/decomposition/DecompositionProblems.java#L420-L473

If you could verify that everything works now, and close this issue, I'll release a version 45.1.1.

**Comment by prubin73** [comment]
I can confirm that both my test code and my production code work correctly with the hot fix.

**Comment by apete** [comment]
v45.1.1, with this fix, is now released.

**Comment by prubin73** [comment]
Great. Thanks for the update.
