### ISSUE TITLE
problems with Eigenvalue

### ISSUE THREAD

**Issue by hongtaicao** [optimatika/ojAlgo#105]
javadoc: [Eigenvalue](http://ojalgo.org/generated/org/ojalgo/matrix/decomposition/Eigenvalue.html)
The example of a 3 by 3 matrix locates at the end of this post.

## Q1. `getEigenpair(int index)`
What does the parameter mean?

I assume `index` means the which eigenpair. For a 3 by 3 matrix, index should be in range [0, 2]. However, I got the following:
`getD()` returns `org.ojalgo.matrix.store.RawStore < 3 x 3 >`
`getV()` returns `org.ojalgo.matrix.store.GenericDenseStore < 3 x 3 >`
`getEigenpair(1)` throws the following 
```
java.lang.ArrayIndexOutOfBoundsException: 3
	at org.ojalgo.array.ReferenceTypeArray.set(ReferenceTypeArray.java:279)
	at org.ojalgo.array.PlainArray.set(PlainArray.java:123)
	at org.ojalgo.array.Array1D.set(Array1D.java:550)
	at org.ojalgo.matrix.decomposition.Eigenvalue.copyEigenvector(Eigenvalue.java:254)
	at org.ojalgo.matrix.decomposition.Eigenvalue.getEigenpair(Eigenvalue.java:279)
	...
```
I think ``destination.set(i, tmpV.doubleValue(i, index));`` of ``Eigenvalue.java:254`` calls the wrong `set` function (Array1D.java:550).

## Q2
Why to have both `getEigenvalues()` v.s. `getD()` for eigenvalues  `getEigenvectors()` v.s. `getV()` for eigenvectors with different return types? Why does `getD()` and `getV()` always return double when decomposing a real matrix? It's possible that the eigenvectors are complex. 

## Q3
I want to request more documentation and example codes for common tasks.

## Data
* Example Matrix
```
{ { 0.730967787376657,	0.24053641567148587,	0.6374174253501083 },
{ 0.24053641567148587,	0.5975452777972018,	0.3332183994766498 },
{ 0.6374174253501083,	0.3332183994766498,	0.8791825178724801 } }
```
* getEigenvalues()
```
[(0.43823612253193817 + 0.0i), (0.15768834183886482 + 0.0i), (1.611771118675537 + 0.0i)]
```
* getD()
```
org.ojalgo.matrix.store.RawStore < 3 x 3 >
{ { 0.43823612253193817,	0.0,	0.0 },
{ 0.0,	0.15768834183886482,	0.0 },
{ 0.0,	0.0,	1.611771118675537 } }
```
* getEigenvectors()
```
org.ojalgo.matrix.store.GenericDenseStore < 3 x 3 >
{ { (0.35197611065642076 + 0.0i), (0.7111682862714321 + 0.0i), (0.6085659258691156 + 0.0i) },
{ (-0.9176190185150541 + 0.0i), (0.1339253584570143 + 0.0i), (0.37421829888666563 + 0.0i) },
{ (0.18462977654389448 + 0.0i), (-0.6901475689763131 + 0.0i), (0.699720071635391 + 0.0i) } }
```
* getV()
```
org.ojalgo.matrix.store.TransposedStore < 3 x 3 >
{ { 0.35197611065642076, 0.7111682862714321, 0.6085659258691156 },
{ -0.9176190185150541, 0.1339253584570143, 0.37421829888666563 },
{ 0.18462977654389448, -0.6901475689763131, 0.699720071635391 } }
```

**Comment by apete** [comment]
A1: I confirm there is a problem and will have look at it

A2: I believe it's standard behaviour to return matrices of the same (element) type as the original matrix. Since the eigenvalues can be complex it is also convenient to be able directly get as complex numbers.

A3: This is an open source project. You're welcome to contribute documentation. I believe the wiki is editable by anyone.

**Comment by apete** [comment]
Please verify that the getEigenpair(int) now works:

https://github.com/optimatika/ojAlgo/tree/hotfix/EigenvalueProblems

If you verify this there shortly be a v45.1.1 release

**Comment by hongtaicao** [comment]
Thank you.
The function ``getEigenpair(int index)`` works as my expectation. It should be fixed.

**Comment by apete** [comment]
v45.1.1, with this fix, is now released.
