### ISSUE TITLE
Solvable model becomes infeasible when solving second time

### ISSUE THREAD

**Issue by jbx1** [optimatika/ojAlgo#117]
Sometimes when a model gets solved successfully (state OPTIMAL, DISTINCT etc.), solving the same model a second time suddenly makes it unsolvable (state INFEASIBLE). This seems to occur when numbers with very high numeric precision (possibly due to internal floating point representation issues) get generated and fed into the solver.

I managed to regenerate it with the following few constraints. (The example is trivial because I extracted it from a much larger generated set of constraints, but demonstrates the behaviour).

```
minimize: 1.0 d57

1.000000 d35 = 0.000000
d56 - d35 = -2000.0400000000002
1.0 d57 - 1.0 d56 = 0.000000
```

When I print out the `ExpressionBasedModel` it looks like this: 
```
############################################
0 <= d35 <= 0
d56
d57 (1)
0 <= -d56 + d57: 0.0 <= 0
-2000.04 <= -d35 + d56: 0.0 <= -2000.04
############################################
```

Calling `minimize()` generates this solution:
```
DISTINCT
DISTINCT -2000.04 @ [0.0, -2000.0400000000002, -2000.04]
```
Solving it again (calling `minimize()` again), without changing the objective weights or changing any variable limits or constraints, then generates the following:
```
INFEASIBLE
INFEASIBLE -2000.04 @ [0.0, -2000.0400000000002, -2000.04]
```
 
The same situation occurs if I change the objective function (which is what I am really trying to do). 

Is there a way to avoid this issue? Why is the model solvable the first time, and then infeasable in the second run?

**Comment by apete** [comment]
If you can supply runnable java code that demonstrates the problem I'd be interested in running it.

Automatically generating models not paying much attention to what numbers are actually used is a bad idea. You should read the Optimisation Modelling Advice in the wiki:

https://github.com/optimatika/ojAlgo/wiki/Optimisation-Modelling-Advice

I wouldn't call `-2000.0400000000002` a very accurate number - it's most likely a number with some noise/error, and it's better you remove that error.

Call `model.validate(solution)` to test the first solution you get.

**Comment by jbx1** [comment]
First of all some additional info. 
Setting this option seems to solve the problem. 

```  
 Optimisation.Options options = new Optimisation.Options();
 options.solution = new NumberContext(12, RoundingMode.HALF_EVEN);

 ExpressionsBasedModel newModel = new ExpressionsBasedModel(options);
```

It seems an issue with feeding back the previous solution values of the model when running it again. (This is actually a pleasant surprise, I thought the LP solver wasn't warm starting the model, but maybe that isn't available only when the user wants to initialise them explicitly?)

> If you can supply runnable java code that demonstrates the problem I'd be interested in running it.

Sure of course.

```
  @Test
  public void precisionTestDoubleRunInfeasible() {

    ExpressionsBasedModel model = new ExpressionsBasedModel();
    Variable d35 = model.addVariable("d35");
    Variable d56 = model.addVariable("d56");
    Variable d57 = model.addVariable("d57");

    // d35 = 0.0;
    d35.level(0.0);

    // d56 - d35 = -2000.0400000000002;
    Expression expression1 = model.addExpression("d56 - d35");
    expression1.set(d56, 1.0);
    expression1.set(d35, -1.0);
    expression1.level(-2000.0400000000002);

    // d57 - d56 = 0.0;
    Expression expression2 = model.addExpression("d57 - d56");
    expression2.set(d57, 1.0);
    expression2.set(d56, -1.0);
    expression2.level(0.0);

    // minimize: 1.0 d57;
    d57.weight(1.0);

    System.out.println(model);
    Optimisation.Result result1 = model.minimise();
    System.out.println(result1);
    System.out.println("Valid? " + model.validate(result1));

    Optimisation.Result result2 = model.minimise();
    System.out.println(result2);
    System.out.println("Valid? " + model.validate(result2));

    assertEquals(result1.getState(), result2.getState());
  }
```

> I wouldn't call -2000.0400000000002 a very accurate number - it's most likely a number with some noise/error, and it's better you remove that error.

Yes it is definitely noise coming from internal precision error after performing some necessary arithmetic. 
Something like `double d = 2000.12 + 0.01` results in `2000.1299999999999`. 

Although sometimes I do try to mimic strict inequalities by using [Math.nextUp()](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#nextUp-double-) and [Math.nextDown()](https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#nextDown-double-). However, this wasn't the case. 

What threw me off during debugging was that this was occurring after running the model the second time. (Since I was modifying the objective function it wasn't immediately evident the problem was precision related.)

> Call model.validate(solution) to test the first solution you get.

Seems its always `true`.

**Comment by apete** [comment]
I think the correct thing to do here is to convert all model parameters to BigDecimal before feeding them to the model. Any parameters you set on a model gets converted to BigDecimal internally. The only way to avoid any conversion, and to completely control what number is actually used in the model, is to create the BigDecimal yourself. The `NumberContext` class has a `toBigDecimal(double)` method that would be suitable.

It's unfortunate that you get a different result the second time. I'll think about what can be done about it.

**Comment by apete** [comment]
The real/actual problem here is that ojAlgo fails to identify the problem as infeasible the first time.

The first time the presolver determines that all 3 variables are actually fixed and that both the expressions/constraints are redundant, but it fails to see that with those fixed variable values one of the expressions is actually infeasible (by 1E-13).

The second time the presolver starts from a different state - the derived bounds on the variables are maintained, but flags regarding redundancy are cleared. Since the redundancy flags are cleared the expressions are checked again and this time the infeasibility is discovered.

I'll se if I can fix this inconsistency, but you should make sure the models you specify are not infeasible because of some rounding error.

**Comment by jbx1** [comment]
OK. That explains why setting the `options.solution` scale to 12 gets it to work. 

What determines if a value is infeasible? Is it the `options.feasibility` `MathContext`?

The default seems to have a different scale from `options.solution`, maybe that is the cause?

``` 
 public NumberContext feasibility = new NumberContext(12, 8, RoundingMode.HALF_EVEN);
```

**Comment by apete** [comment]
I plan to close this issue as "wontfix". There is a glitch in ExpressionsBasedModel's presolver logic, but I think a it's minor edge-case problem that will be complicated to fix. You've gotten an explanation for what happens as well as recommendations on how to avoid the problem. In addition I assume that code change I made would greatly decrease the likelihood of this edge-case occurring.

**Comment by jbx1** [comment]
OK great.
