### ISSUE TITLE
Problems with changing maximization to minimization  + objective value 

### ISSUE THREAD

**Issue by danyaljj** [optimatika/ojAlgo#12]
I have written [this Java code](https://github.com/danyaljj/ojAlgoJavaHook/blob/master/src/main/java/OJalgoHook.java) to make calls to your system. I also have [this jUnit test file](https://github.com/danyaljj/ojAlgoJavaHook/blob/master/src/test/java/JalgoHookTest.java) to make sure things are working fine. 

Two questions
 -  So apparently the [`setMaximize`](https://github.com/danyaljj/ojAlgoJavaHook/blob/master/src/test/java/JalgoHookTest.java) function does not work, since half of my tests fail.  Any idea where I am going wrong? 

 - In [getting the value of objective](https://github.com/danyaljj/ojAlgoJavaHook/blob/master/src/main/java/OJalgoHook.java#L206-L214) after solving the problem, I was using `result.getValue()`, which I noticed it always returns 0. Any idea where I am going wrong?

**Comment by apete** [comment]
You cannot extract and cache the objective function/expression the way you do - it is generated on demand. More specifically you cannot modify that generated expression. Those updates are not part of the optimisation model.

In your various addVariable methods you should simply do something like this:

Variable var = Variable.makeBinary(Integer.toString(numbers)).weight(c);

Alternatively you could define your own objective function/expression. Just create an expression, use it as you are using the generated expression and set its weight to anything other than 0.0 or NULL – 1.0 is a good choice.

The Optimisation.Result returned by ojAlgo's ExpressionsBasedModel contains the objective function value. You do not need to calculate it.

**Comment by danyaljj** [comment]
Thanks! Problems fixed!
