### ISSUE TITLE
ElementsSupplier transpose() problem

### ISSUE THREAD

**Issue by manabu-tsunokai** [optimatika/ojAlgo#133]
Hi, I'm new to ojAlgo.
ElementsSupplier's transpose() doesn't seem to work correctly under some conditions.

Here is an example.
        double[][] _x = {{1, 2, 3}, {4, 5, 6}, {7, 8, 9}};
        double[][] _y = {{0, 0, 0}, {1, 1, 1}, {2, 2, 2}};
        PrimitiveDenseStore x = PrimitiveDenseStore.FACTORY.rows(_x);
        PrimitiveDenseStore y = PrimitiveDenseStore.FACTORY.rows(_y);
        ElementsSupplier<Double> es = y.operateOnMatching(x, SUBTRACT);
        System.out.println("x - y : " + es.get());
        ElementsSupplier<Double> es2 = es.transpose();
        System.out.println("(x - y)t : " + es2.get()); 

The Output:
x - y : org.ojalgo.matrix.store.PrimitiveDenseStore < 3 x 3 >
{ { 1.0,	2.0,	3.0 },
{ 3.0,	4.0,	5.0 },
{ 5.0,	6.0,	7.0 } }
(x - y)t : org.ojalgo.matrix.store.PrimitiveDenseStore < 3 x 3 >
{ { 1.0,	1.0,	1.0 },
{ 4.0,	4.0,	4.0 },
{ 7.0,	7.0,	7.0 } }

I got this result with version 46.0.0 and 46.1.0.
I've never tried previous versions.

**Comment by apete** [comment]
I committed code yesterday, in the development branch, that should fix the bug. Please verify that it is fixed, and close this issue if it is.

**Comment by manabu-tsunokai** [comment]
I confirmed it is fixed. Thanks.
