### ISSUE TITLE
Calculating the sum for each row in sparse matrices

### ISSUE THREAD

**Issue by szarnyasg** [optimatika/ojAlgo#136]
Slightly related to my previous issue #134.

I am working on graph analysis with sparse matrices with my Master's student @missvarhegyi.

Now that element-wise multiplications work, we need to calculate the sum of each row. We first tried to calculate this using [`reduceRows`](http://javadoc.scijava.org/ojAlgo/org/ojalgo/matrix/store/MatrixStore.html#reduceRows-org.ojalgo.function.aggregator.Aggregator-), but it turned out to be very slow.

We then tried calculating `A * 1`, which performs row-wise sum (as described in Sec. II.B of paper [A task-based linear algebra building blocks approach for scalable graph analytics](https://dblp.uni-trier.de/rec/html/conf/hpec/WolfBS15)). This was orders of magnitudes faster than the `reduceRows` approach.

Here are separate unit tests for the two approaches, using 100k × 100k empty matrices. The multiplication approach is sub-second while the `reduceRows` one takes 1.5 minutes.

```java

    @Test
    public void testReduceRows() {
        int n = 100_000;
        SparseStore<Double> a = SparseStore.PRIMITIVE.make(n, n);

        System.out.println("reduceRows(A)");
        PrimitiveDenseStore sum = PrimitiveDenseStore.FACTORY.makeZero(n, 1);
        a.reduceRows(Aggregator.SUM).supplyTo(sum);
        ElementView1D<Double, ?> nnz = sum.get().nonzeros();
        while (nnz.hasNext()) { nnz.next(); }
    }

    @Test
    public void testMultByOneVector() {
        int n = 100_000;
        SparseStore<Double> a = SparseStore.PRIMITIVE.make(n, n);

        System.out.println("A * 1");
        PrimitiveDenseStore ones = PrimitiveDenseStore.FACTORY.makeZero(n, 1);
        ones.operateOnAll(ADD, 1).supplyTo(ones);
        PrimitiveDenseStore sum = PrimitiveDenseStore.FACTORY.makeZero(n, 1);
        a.multiply(ones).supplyTo(sum);
        ElementView1D<Double, ?> nnz = sum.get().nonzeros();
        while (nnz.hasNext()) { nnz.next(); }
    }
```

Are there any ways to speed up `reduceRows`? (If not, this issue shows a faster alternative.)

**Comment by apete** [comment]
It's probably a little bit faster now (I made some changes) but the vector multiplication solution is most likely a better alternative.

**Comment by szarnyasg** [comment]
Thanks, it seems a lot faster now -- it beats the vector multiplication method on pretty much all sizes.

50k × 50k empty matrix:
![image](https://user-images.githubusercontent.com/1402801/45889707-696eb180-bdc1-11e8-81d5-d72a9e2c4ec5.png)

50M × 50M empty matrix:
![image](https://user-images.githubusercontent.com/1402801/45889652-45ab6b80-bdc1-11e8-970d-7412d1564a38.png)
