### ISSUE TITLE
Test code errors in eclipse

### ISSUE THREAD

**Issue by norvar** [optimatika/ojAlgo#14]
I added ojAlgo built jars(version 40.0) to eclipse and made a project for the test code. I got three compiled errors.
![screenshot 10](https://cloud.githubusercontent.com/assets/9779240/12402294/eb916e20-bdf9-11e5-9e8f-c79ad825977e.png)
![screenshot 11](https://cloud.githubusercontent.com/assets/9779240/12402293/eb8f6850-bdf9-11e5-934b-7fc721590e81.png)
![screenshot 12](https://cloud.githubusercontent.com/assets/9779240/12402295/eb92d0bc-bdf9-11e5-804c-e61ed14b1797.png)

**Comment by apete** [comment]
What version of junit are you using? ojAlgo still uses junit 3.

The eclipse project files are are also checked in. Use them to "Import existing project". I've not checked in code that doesn't compile.

**Comment by norvar** [comment]
OK. And there are a few other issues in my eclipse after upgrade to Java 8. I will come back. Sorry.

**Comment by norvar** [comment]
I fixed the problems for the last two pictures. Although I upgraded JRE  for eclipse, the java compiler was not changed automatically. I downloaded a new eclipse Mars release and fixed last two problems.

I checked my Junit version is much higher. I'll try to find one.

Thanks.

**Comment by norvar** [comment]
I tried junit 3.8.1. The constructor error is still there. Could you please tell me what is your version number?

Thanks

**Comment by norvar** [comment]
Any junit 3 doesn't have package org.junit. Finally I found Junit 4.3.1 removed the error.

Thanks.
