### ISSUE TITLE
SimplexSolver does not call isIterationAllowed

### ISSUE THREAD

**Issue by alexlukas** [optimatika/ojAlgo#149]
I'm using ojAlgo via [Optimus](https://github.com/vagmcs/Optimus) and discovered that setting a timeout there (translating to options.time_abort  in ojAlgo) does not have any effect for my particular optimization problem. After some debugging, I found out that `ExpressionsBasedModel` invokes a `SimplexSolver` instance in my case, which does not seem to call `GenericSolver.isIterationAllowed` to see whether the solver should abort (according to a quick search with IntelliJ, this method is only called in ConvexSolver and IntegerSolver).

I could solve the problem locally by simply calling the appropriate methods in `solve`, I'll create a pull request in a second - I just was not sure whether that actually is a bug or there is a reason for not checking for timeouts in the simplex solver.

**Comment by apete** [comment]
Probably just didn't think this was necessary or relevant for the simplex solver. Why do you need this?

**Comment by apete** [comment]
https://github.com/optimatika/ojAlgo/tree/feature/SufficeAndAbort
