### ISSUE TITLE
A question about Sparse

### ISSUE THREAD

**Issue by asevans48** [optimatika/ojAlgo#15]
I am working to find a decent Java or Scala Matrix library to support large amounts of data for streamed learning. I have tried Breeze but ran into a memory issue at a relatively small 1000 * 50000 size matrix, a size Scipy handles with ease. Since I do a lot of mixed operations (in and out of the library), I was wondering, are you planning on creating an optimized Sparse library at any point?

**Comment by apete** [comment]
That's a very unspecific question. What exactly do you need and why don't you build it yourself?

org.ojalgo.array.SparseArray was introduced with v38, and that means Array1D, Array2D and ArrayAntD can be sparse.

org.ojalgo.matrix.store.SparseStore was introduced with v39.

With v40 the optimisation algorithms will make use of sparse structures to greatly improve performance on larger problems.
