### ISSUE TITLE
MarkowitzModel trouble with small values

### ISSUE THREAD

**Issue by Galigator** [optimatika/ojAlgo#153]
Hello, 

thank you for your nice work, I am using  MarkowitzModel (available in version 45.1.0), and it work fine. But some time I get the following exception : 

```
 
 Exception in thread "main" java.lang.IllegalArgumentException: Q must be positive semidefinite!
 	at org.ojalgo.optimisation.convex.ConvexSolver.validate(ConvexSolver.java:885)
 	at org.ojalgo.optimisation.convex.ConstrainedSolver.validate(ConstrainedSolver.java:51)
 	at org.ojalgo.optimisation.convex.ConvexSolver.solve(ConvexSolver.java:651)
 ...
 

```
here a complete sample of code that produce the problem :
[Test.txt](https://github.com/optimatika/ojAlgo/files/2605084/Test.txt)
It must be compile with the following dependencies

`
		<dependency>
    		<groupId>org.ojalgo</groupId>
    		<artifactId>ojalgo</artifactId>
    		<version>45.1.0</version>
		</dependency>
		<dependency>
    		<groupId>org.ojalgo</groupId>
    		<artifactId>ojalgo-finance</artifactId>
    		<version>1.1.0</version>
		</dependency>
`

Here an example of matrix that produce the problem.

```
0.0036133015701268483 7.389913608466776E-4 6.41031397418522E-4 -2.3105096877969656E-5 8.879125330915954E-4 
7.389913608466776E-4 1.8348350177020605E-4 1.1482397012107551E-4 -8.167817650045201E-6 2.701855163781939E-4 
6.41031397418522E-4 1.1482397012107551E-4 1.2573449753628196E-4 -3.721569692276288E-5 1.3670994762578353E-4 
-2.3105096877969656E-5 -8.167817650045201E-6 -3.721569692276288E-5 3.7685337454122363E-4 -3.022900619430631E-4 
8.879125330915954E-4 2.701855163781939E-4 1.3670994762578353E-4 -3.022900619430631E-4 6.934651608369498E-4 
```

I understand that it may be hard to solve, but is there a workaround to this kind of problem ?

Best regards.

**Comment by apete** [comment]
The problem is with your data not with ojAlgo.

There is a method "clean" in the MarketEquilibrium that could help, but I wouldn't recommend using that unless you understand something about what it does and why you have the problem in the first place.
