### ISSUE TITLE
Implement TDistribution

### ISSUE THREAD

**Issue by thomasnield** [optimatika/ojAlgo#162]
Would it be possible to add Student's TDistribution?
https://en.wikipedia.org/wiki/Student%27s_t-distribution

**Comment by apete** [comment]
What's the key thing you need? random number generation with that distribution?

**Comment by thomasnield** [comment]
@apete Affirmative. I used the one in Apache Commons Math for a simualated annealing experiment I did for a linear regression. 

https://github.com/thomasnield/kotlin_linear_regression/blob/master/src/main/kotlin/Model.kt

I can try to contribute it if you like, although I may look like a complete amateur. But I've become very interested in coding random sampling from distributions from scratch. However I do find myself getting frustrated inversing CDF's for nonlinear distributions. I'm guessing the integral calculus can be avoided.

**Comment by apete** [comment]
Just because you mentioned it I started looking at the code in the org.ojalgo.random package (wrote that code a long time ago).

https://github.com/optimatika/ojAlgo/tree/feature/ReviewRandomNumbers

Did a bit of refactoring and cleanup. Created a Cauchy distribution class and outlined a TDistribution class. Apart from testing and performance/numerical improvements there are only 2 methods missing. The CDF and its inverse... Implementing those is the real difficulty here.

**Comment by thomasnield** [comment]
@apete okay awesome, thank you. I'll see if I can try implementing them again one I get back from this road trip.

**Comment by thomasnield** [comment]
Just curious since I'm hacking my way through learning this stuff. Why did you stop at 4 degrees of freedom before just defaulting to infinity? Thanks for putting this together. I'm enjoying studying this.

**Comment by apete** [comment]
I didn't – that's not how it works. There are special cases for 1, 2 , 3, 4 and inf degrees of freedom. The default is the parent Distribution class.

I just coded what I could read directly at Wikipedia and using what was already available in ojAlgo.

**Comment by thomasnield** [comment]
This is beautiful. Thank you! This should be good to merge.

**Comment by apete** [comment]
There are 2 important methods not yet implemented. Is this ev en usable without those?

**Comment by thomasnield** [comment]
@apete I think I just sampled some randoms from it and built a plot. I didn't test the other methods. I'll take a look....

**Comment by apete** [comment]
I've merged this to the develop branch. For this to be complete and useful someone needs to implement those 2 methods in the main Distribution class: getDistribution and getQuantile.

**Comment by thomasnield** [comment]
You probably already know this. It looks like Apache Commons Math does some interesting things, and doesn't exactly use a quantile function. 

I wish I could help but I can't guarantee I can make time to figure this out. 

https://github.com/apache/commons-statistics/blob/master/commons-statistics-distribution/src/main/java/org/apache/commons/statistics/distribution/TDistribution.java

https://github.com/apache/commons-statistics/blob/master/commons-statistics-distribution/src/main/java/org/apache/commons/statistics/distribution/AbstractContinuousDistribution.java

**Comment by apete** [comment]
Done in v48.2.0
