### ISSUE TITLE
Hankel, pinv, and toeplitz matrix into Oj!Algo?

### ISSUE THREAD

**Issue by DanielMartensson** [optimatika/ojAlgo#166]
Hello!

Is it possible to implement Hankel matrix, pseudo inverse pinv and toeplitz matrix in Oj!Algo?
Those are used for system identification. If you wonder how it works, you can check out my "Mataveid" repository and "EmbeddedAlgebra" repository. 

I'm new to Oj!Algo and I'm going to use this for control engineering.

**Comment by apete** [comment]
Should be possible. Contributions are best made by those who need the feature and understand the requirements.

If you open a PR with draft code I can try to guide you regarding how to best use what's already there.

**Comment by apete** [comment]
Wish list items for completely new functionality that no one is working on should be here.
