### ISSUE TITLE
Strange performance degradation of Linear Solver

### ISSUE THREAD

**Issue by jbx1** [optimatika/ojAlgo#169]
ojAlgo usually has very competitive performance, especially considering it is pure Java. 
When comparing it to native LPSolve, it often performs almost to the same level. 

However, I am occasionally observing strange performance degradation occasionally when the same model gets a few extra variables and constraints added to them (the additions wouldn't be constraining the original model). LPsolve would solve the model in approximately the same time, while ojAlgo slows down significantly. I don't think it is a Java vs native issue, although I could be wrong.

The attached 2 LPs demonstrate this (they are in the simple LPSolve text format). They are machine generated and might seem a bit redundant in some places, but they show the problem in isolation well.

The first file `t_206.txt` is solved by LPSolve (using the LPSolve IDE) in **281ms**. 
The same LP is solved by ojAlgo in **323ms**. Pretty close. 
It generates 261 variables and 474 constraints in ojAlgo's ExpressionBasedModel.

The second file `t_235.txt` is solved by LPSolve in **346ms**.
The same LP however is solved by ojAlgo in **2358ms**. 
It generates 292 variables and 529 constraints on ojAlgo's ExpressionBasedModel.
 
I am parsing exactly the same files to both. I am using ojAlgo 47.0.0.

In case of ojAlgo what I am doing programmatically is that if the constraint has only one variable, the constant is divided by the coefficient, and the result is added as a bound to the variable itself, unless it already has a tighter bound (in case another constraint on the variable was defined). This way I don't add extra redundant constraints.

 ```
 switch (inequality) {
            case LESS_THAN_EQUAL:
                //check if the existent limit is already tighter
                if ((variable.getUpperLimit() == null)
                        || (Double.compare(variable.getUpperLimit().doubleValue(), limit) > 0)) {
                    variable.upper(limit);
                }
                break;

            case GREATER_THAN_EQUAL:
                //check if the existent limit is already tighter
                if ((variable.getLowerLimit() == null)
                        || (Double.compare(variable.getLowerLimit().doubleValue(), limit) < 0)) {
                    variable.lower(limit);
                }
                break;

            case EQUAL:
                variable.level(limit);
                break;
}
```

If you diff the 2 files, you will see that t_235 just has some extra variables added, and constraints on them to get their value from other variables. 

What could be the reason for this sudden performance drop? As more constraints get added I notice similar drops ... going up to 34 seconds. Is there anything I can do to understand a bit more what is going on?

[t_206.txt](https://github.com/optimatika/ojAlgo/files/2836102/t_206.txt)
[t_235.txt](https://github.com/optimatika/ojAlgo/files/2836103/t_235.txt)

**Comment by apete** [comment]
I've got a really bad conscience about one thing. There is absolutely no science behind the logic in this method:

https://github.com/optimatika/ojAlgo/blob/b3073788e35d40eea3e97124e305c9063b96f9b0/src/org/ojalgo/optimisation/linear/SimplexTableau.java#L866-L877

Perhaps you can help out here. Please do some tests to figure out when to switch between the dense and sparse implementations. It seems very likely that this will solve/explain your problem.

**Comment by jbx1** [comment]
I did a quick test and replaced that code to always return a `DenseTableau`. 
As you suspected, the slightly larger model solves in  **377ms** instead of 2358ms.

What is the main difference between `SparseTableau` and `DenseTableau`?

**Comment by apete** [comment]
The solver's internal storage is either dense or (memory saving) sparse. Operation on sparse storage is typically much slower than on a dense. Performance gains from using sparse over dense would come at some large problem size. Problem here is that I never investigated what would be a suitable problem size to switch at, and I set it much too low.

Would you help me find out at what problem size the sparse implementation becomes preferable?

**Comment by jbx1** [comment]
What do you think affects the performance between Sparse and Dense most? 
A lot of constraints (rows) even if there is a modest amount of variables? 
Or a lot of variables?

**Comment by apete** [comment]
Guessing based on how it's currently implemented...

1) There has to to be "many" variables for sparse to be effective!
2) The number of constraints is most likely less important, but I guess the ratio "number of variables over number of constraints" would be a factor. More variables than constraints should tilt the choice towards sparse.
3) The sparsity of the constraints does of course matter, but that's just the point. Most constraints are very sparse. If this was not the case the would be no point in having a sparse solver.

**Comment by jbx1** [comment]
OK, so some initial tests. Nothing scientific, just running my application (which incrementally adds new variables and chains constraints with previous ones). 

I've forced ojAlgo to use `DenseTableau` only, and then to use `SparseTableau` only, so we don't have to guess when it switched. I've attached the results of both (they have the same lines exactly to be able to diff them). The LPs are exactly the same of course.

`DenseTableau` keeps degrading its performance gracefully, while `SparseTableau` degrades significantly here (more than 15x):

Using `DenseTableau`
```
2019-02-13 15:40:25.583 [main] DEBUG - Solving LP with 261 variables and 423 constraints took 175ms
2019-02-13 15:40:27.609 [main] DEBUG - Solving LP with 292 variables and 475 constraints took 258ms
```

Using `SparseTableau`
```
2019-02-13 16:02:55.508 [main] DEBUG - Solving LP with 261 variables and 423 constraints took 168ms
2019-02-13 16:02:59.984 [main] DEBUG - Solving LP with 292 variables and 475 constraints took 2760ms
```
 
`SparseTableau` keeps getting slower at a much greater pace than `DenseTableau`, and they don't converge (at least not with my test set so far). 

The last (larger) LP I have then gets solved in less than 2s with `DenseTableau`, while `SparseTableau` takes almost 13s. 

Using `DenseTableau`
```
2019-02-13 15:42:23.122 [main] DEBUG - Solving LP with 559 variables and 916 constraints took 1906ms
```

Using `SparseTableau`
```
2019-02-13 16:15:09.159 [main] DEBUG - Solving LP with 559 variables and 916 constraints took 12892ms
```

Side note: Some tests fail when switching to always use `SparseTableau`. I get: 
`java.lang.IllegalStateException: java.lang.IllegalStateException: Requires a count/size greater than the limit!`

[DenseTableau.txt](https://github.com/optimatika/ojAlgo/files/2860924/DenseTableau.txt)
[SparseTableau.txt](https://github.com/optimatika/ojAlgo/files/2860925/SparseTableau.txt)

**Comment by apete** [comment]
Thanks, that's scientific enough and something I should have done a long time ago.

1) Is there anyway can give me code to run that would generate that java.lang.IllegalStateException?

2) I still think the sparse implementation will be beneficial at some point, but obviously the implementation needs to be tuned. You have many more constraints than variables. This is most likely part of the problem here (for the sparse implementation). Do you need them all? Are there not redundancies? If you can get rid of some of them it will improve the dense performance as well.

**Comment by jbx1** [comment]
> 1. Is there anyway can give me code to run that would generate that java.lang.IllegalStateException?

It is the unit tests of ojAlgo themselves. I've created a separate issue so that we leave this issue focused on the performance observations.

> 2. Do you need them all? Are there not redundancies?

Well most of the constraints link 2 variables. Often you just need one, but sometimes you need more.
In my specific case the majority (but not all) of the variables represent an unknown timepoint, and the constraints are putting bounds on how much time could pass between both. Sometimes the same variable has constraints with more than one other variable. 

There might be some redundant constraints. I already went through an exercise to minimise a lot of them. Removing some more is possible but a bit tricky (they are machine generated from other data structures).

**Comment by apete** [comment]
@jbx1 I've made one change to how the sparse tableau works. Would be very interesting to know how (if) if effects that test you made. Can you run it again? You have to take the latest changes from the feature/TestCaseCPLEX branch.

**Comment by jbx1** [comment]
I pulled the feature/TestCaseCPEX branch. Unfortunately still the same effect. The moment it goes over this same  boundary the time it takes still spikes up:

```
2019-02-14 16:37:21.901 [main] DEBUG - Solving LP with 261 variables and 423 constraints took 192ms
2019-02-14 16:37:26.462 [main] DEBUG - Solving LP with 292 variables and 475 constraints took 2986ms
```

**Comment by jbx1** [comment]
What do you think, if we add an extra option to the `Optimisation.Options` class, and pass the Options instance to the `SimplexSolver.build()` from the `LinearSolver` class (lines 107 and 114), and subsequently to the `SimplexTableau.make()` method where the decision to use Dense or Sparse is being made. 

We could have 3 choices for this new option, use only `DenseTableau`, use only `SparseTableau`, and switch between both (the current functionality).

**Comment by apete** [comment]
Yes, possibly we may end up adding some sort configuration. You can control this already now. If you set OjAlgoUtils#ENVIRONMENT to something with a very large CPU cache, you will trick ojAlgo to always choose the dense implementation.

If you modify that factory method to always return "sparse" like you did before. Then the exceptions should be gone now. And is it possible to to get a file with execution times for various problem sizes. I want to compare "old sparse" with "new sparse". I don't expect the changes I made to solve your problem. Just interested to learns how much the change I made improved the timings.

**Comment by apete** [comment]
@jbx1 I've changed the logic to always use the dense version when there are more constraints than variables. That's not unreasonable as a general rule and it solves your problem.

**Comment by jbx1** [comment]
I've attached the logs of another run of those tests.
I did a quick diff between the `SparseTableau` and `SparseTableauNew` and actually the new seems to be approx 10% slower after it does its first performance drop (line 106).

The last LP was computed in 12892ms with the previous `SparseTableau`, while it took 13969ms with the new `SparseTableau`. 

[SparseTableauNew.txt](https://github.com/optimatika/ojAlgo/files/2875271/SparseTableauNew.txt)

**Comment by jbx1** [comment]
Attached the log with the new branch untouched, so I presume it is using your latest change where it uses the dense version when there are more constraints. 

Performance is around 6x better with this branch.

[newOjAlgoBranch.txt](https://github.com/optimatika/ojAlgo/files/2875312/newOjAlgoBranch.txt)

**Comment by apete** [comment]
Thanks, yes, newOjAlgoBranch.txt should then be compared with DenseTableau.txt.

I also changed details regarding how presolving is performed. It seems that cost you 5-10% in both the dense and sparse cases. The changes I made were necessary for other cases. I'll have to see what I can do restore performance in your case.

**Comment by jbx1** [comment]
OK cool. Comparing `newOjAlgoBranch.txt` and `DenseTableau.txt` , there doesn't seem to have any material difference in performance yet.

**Comment by apete** [comment]
@jbx1 There is now an option (as you suggested) named `sparse` that controls if the sparse or dense solver should be used. Not setting the option – the default is `null` – ojAlgo will choose for you, and the logic for that is similar to (but not the same as) what it was before.

There is now also a couple of new presolvers that would effect execution times.

Can you verify that what's currently in the develop branch doesn't screw things up for you?

**Comment by jbx1** [comment]
Sorry for taking long to get back to you on this. Today I did some tests with 47.2.0. 
With default configuration (`sparse = null`) the behaviour goes back to very bad performance: 

`Solving LP with 547 variables and 898 constraints took 14875ms`

With `sparse = false` this goes down by 85%:

`Solving LP with 547 variables and 898 constraints took 2143ms`

I guess I have to switch this to false for my case.

**Comment by apete** [comment]
Set it to `false` for. I'm currently working on some changes for the LP solver. Next release (47.3 or 48) you should test/evaluate again.
