### ISSUE TITLE
SingularValueDecomposition.getInverse returns the inaccurate pseudo-inverse in case of big matrices

### ISSUE THREAD

**Issue by chang-chao** [optimatika/ojAlgo#17]
for the details ,See the discussion thread below in the mailing list .
https://sourceforge.net/p/ojalgo/mailman/message/35025943/

**Comment by apete** [comment]
Thanks for the code fix! I cleaned the code a bit. Would you mind verifying that it still works for you?

**Comment by chang-chao** [comment]
@apete thanks for the fix,still works for me.
