### ISSUE TITLE
MarkowitzModel#addConstraint doesn't handle null values

### ISSUE THREAD

**Issue by esarbe** [optimatika/ojAlgo#20]
contrary to what the javadoc says null values will not result in the expected limits. instead, null values are silently converted to BigDecimal.ZERO, which can make problems unfeasible.

**Comment by apete** [comment]
Thanks for the fix, I've accepted your pull request as it solves the immediate problem. I'll look into the design of the MarkowitzModel more thoroughly later.

**Comment by apete** [comment]
Hi,

I modified/moved the code fix so that it maintains that null means unbounded, and also fixes the same problem with the PortfolioMixer class. Could you please verify that this still works for you?

/Anders

**Comment by esarbe** [comment]
@apete This works for me. Thanks!
