### ISSUE TITLE
IntegerSolver using too many threads and peek entire system CPUs to 100% 

### ISSUE THREAD

**Issue by frankiearzu** [optimatika/ojAlgo#212]
**Using the Integer Solver, it peek the CPU to 100% regardless of thread configuration**

After looking at the code, it is using _ForkJoinPool.commonPool()_ that is not limiting the number of threads.. We can change it globally via a System Property, but could affect other areas of the code in a shared environment.

**To Reproduce**
Just run something that uses IntegerSolver and ALL the CPUs will go to 100%

**Expected behavior**
Should respect _OjAlgo.ENVIRONMENT_ setting, and create local/internal pool for its own usage. Using the Java global common pool is not right.

**Next Steps**
We will pull the code, make the changes, and submit the fix

**Comment by frankiearzu** [comment]
This are my changes so far:  (localForkJoinPool).. Also we can take the same aproach of DeamonPoolExecutor to create one shared for all OjAlgo code.

![image](https://user-images.githubusercontent.com/32604366/61667975-10053680-aca1-11e9-8962-73343d332b67.png)

**Comment by apete** [comment]
There is most likely a problem here:

https://github.com/optimatika/ojAlgo/blob/2c6dc0255efa9a3e3349793dc4b5140aa84049ee/src/org/ojalgo/machine/AbstractMachine.java#L56-L66

It will set the `threads` to `runtime.availableProcessors()` regardless of what the hardware specifies. It seems to me that both the `memory` and `threads` should be derived from the hardware.

**Comment by apete** [comment]
Currently there are 2 thread pools used by ojAlgo:

1. DaemonPoolExecutor.INSTANCE used all low level linear algebra stuff
2. That ForkJoinPool.commonPool used y the IntegerSolver

That common pool can be replaced 3 ways:

1. A local instance in each IntegerSolver instance
2. A static instance shared by any/all IntegerSolver instances
3. Make `DaemonPoolExecutor.INSTANCE` a fork/join pool and use that for everything.

I think I prefer (3) but that's also the alternative that requires the most coding and testing.

**Comment by frankiearzu** [comment]
Thank you @apete, I think you are right with respect to `OJAlgo.ENVIRONMENT.threads`. I could be a bug. 
The DeamonPoolExecutor uses `OjAlgo.ENVIRONMENT.cores` instead.. that seems not right either, but do limit the number of threads used.
I'm not too familiar with the other usages inside the library to make that call (if is a bug or not)

As for the `IntegerSolver` ForkJoinPool, the quick/safer will be option 2 (Static instance shared by all solvers).  If we want to later use the `DeamonPoolExecutor`, it will be easy to find where to do the change.
(or simply make the new OjAlgo's `ForkJoinPoolExecutor.INSTANCE` to point to DeamonPoolExecutor.INSTANCE once the DeamonPoolExecutor is tested as a ForkJoinPool)

Will work on option 2.

**Comment by apete** [comment]
I've created a feature branch MachineLimitis with some changes. You ranch your work from that. I plan to add functionality like limitThreads(int), limitCores(int), limitUnits(int) to org.ojalgo.machine.VirtualMachine.

**Comment by apete** [comment]
I have now pushed some updates to that branch. Please test if "limiting" `OjAlgoUtils.ENVIRONMENT` works for you (without having to create a custom/fake Hardware instance).

Are you aware of the option `mip_defer`? It also affects the parallelism of the InterSolver. It is possible to make the IntegerSolver effectively single threaded simply by modifying that parameter.

**Comment by frankiearzu** [comment]
Updated from your changes, and we will test locally... will check what the mip_defer do.
After successful testing, will push to our github branch.

**Comment by apete** [comment]
@frankiearzu I just pushed some further configuration changes

If you have any feedback on how things are working for you I'd like to hear it.

If your problem is solved, then please close this issue.
