### ISSUE TITLE
SVD getSolution method with 2nd argument results in error with v47.2.0 and develop branch build

### ISSUE THREAD

**Issue by sudheergattu** [optimatika/ojAlgo#214]
Below program runs fine with v47.1.2 where as failing with v47.2.0 and artifacts from latest develop branch

package com.svdevaluation.svd;

import java.util.Arrays;

import org.apache.commons.math3.linear.Array2DRowRealMatrix;
import org.apache.commons.math3.linear.RealMatrix;
import org.ojalgo.commons.math3.linear.RealMatrixWrapper;
import org.ojalgo.matrix.decomposition.SingularValue;
import org.ojalgo.matrix.store.MatrixStore;
import org.ojalgo.matrix.store.PrimitiveDenseStore;

public class OjAlgo {

	public static void main(String[] args) {
		//
		double[][] olsColumns = { { 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
				{ 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0 }, { 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0 },
				{ 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, { 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0 },
				{ 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0 }, { 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0 },
				{ 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }, { 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0 },
				{ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0 }, { 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0 },
				{ 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0 }, { 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0 },
				{ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0 } };
		double[] observationVector = {26.0, 12.0, 9.0, 18.0, 16.0, 17.0, 24.0, 32.0, 30.0, 21.0, 16.0, 12.0, 21.0, 16.0};

		final PrimitiveDenseStore tmpOriginal = PrimitiveDenseStore.FACTORY.rows(olsColumns);
		SingularValue<Double> tmpSVD = SingularValue.make(tmpOriginal);
		tmpSVD.decompose(tmpOriginal);
		double[] singularValues = tmpSVD.getSingularValues().toRawCopy1D();
		//System.out.println("rank threshold "+tmpSVD.getRankThreshold());
		double[][] V = tmpSVD.getQ2().toRawCopy2D();
		System.out.println("V" + Arrays.deepToString(V));
		System.out.println("Singular values" + Arrays.toString(singularValues));
		try {

			// MatrixStore<Double> doubleMat = tmpSVD.solve(tmpOriginal,
			// PrimitiveDenseStore.FACTORY.column(Utils.prepareObservationVector()));
			MatrixStore<Double> solution = tmpSVD.getSolution(PrimitiveDenseStore.FACTORY.column(observationVector), tmpSVD.preallocate(tmpOriginal));
		//	MatrixStore<Double> covariance = tmpSVD.getCovariance();
			//System.out.println("Covariance " + Arrays.toString(covariance.toRawCopy1D()));
			System.out.println("Solution " + Arrays.toString(solution.toRawCopy1D()));
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

}

Error
------
ProgrammingError: The column dimension of the left matrix does not match the row dimension of the right matrix!
	at org.ojalgo.ProgrammingError.throwForMultiplicationNotPossible(ProgrammingError.java:46)
	at org.ojalgo.matrix.store.PrimitiveDenseStore.fillByMultiplying(PrimitiveDenseStore.java:766)
	at org.ojalgo.matrix.decomposition.RawSingularValue.getSolution(RawSingularValue.java:184)
	at com.svdevaluation.svd.OjAlgo.main(OjAlgo.java:38)

**Comment by apete** [comment]
You need to use the preallocate-method that takes 2 arguments - the equation system body and the RHS. The one you're using is paired with the getInverse() method.

Using the preallocated alternatives of getSolution(...) or getInverse(...) only makes sense if you are going to call them many times with same dimension arguments – otherwise don't bother with this.
