### ISSUE TITLE
OPTIMAL solution is wrong

### ISSUE THREAD

**Issue by LucaRitz** [optimatika/ojAlgo#218]
First of all thank you very much for this great API.

### Description
I have to model the distribution of articles to orders.
There are two types of articles: new and old ones.
Each order has a minimum amount of new articles, which is called longtime.
For example: 10 articles requested, longtime is 60 -> 6 articles have to be new to fulfill this order. The other 4 articles may be new, but can be old ones.

Maybe there are not enough articles to fulfill all the orders. In this case, the first orders have to be completed.
To handel all these cases, I've decided to introduce two variables:
longtime -> Describes the amount of new articles
enabled -> Can be one or zero. If zero, then the order won't be completed.

I know also the available amount of new and old articles, so we can say:
1) all distributed new articles <= available amount of new articles
2) all distributed old articles <= available amount of old articles

longtime and enabled are bound the following way:
enabled = 0 -> longtime = 0
enabled = 1 -> minimum <= longtime <= 1

To create the first condition, i can just sum up all the distributed new variables by:
dist_new_1 + ... + dist_new_n <= available amount of new articles
dist_new_n = longtime_n * requested_n

The second condition is not as easy to write because of the bounding of the variables.
"dist_new_n" is the same as "longtime_n" multiplied by "requested_n". This means, that "dist_new_n" is zero if the order is not completable (enabled_n = 0) which means that "dist_old_n" is the requested amount of order n (dist_old_n = requested_n - dist_new_n).
If I sum up all the dist_old_n variables, a solution is never possible to find if not enough articles are given. To handel this case, I introduced a new variable:
old_deduction_n = enabled_n * dist_old_n
It is bound to enabled_n the following way:
enabled_n = 0 -> old_deduction_n = 0
enabled_n = 1 -> old_deduction_n = dist_old_n
The second condition can be epxressed as:
old_deduction_1 + ... + old_deduction_n <= available amount of old articles

This way, it is possible to ignore an order if not enough articles are available.

To do this kind of multiplication, I used four additional conditions:
M = 1'000'000
1) 0 <= M * enabled_n - old_deduction_n
2) 0 <= old_deduction_n
3) 0 <= dist_old_n - old_deduction_n
4) 0 >= dist_old_n - M(1 - enabled_n) - old_deduction_n

This works fine in most of the cases. But now i've found a test which won't be possible to complete, even if there should be a possible solution.

### Initial situation
Available new amount: 30
Available old amount: 10
**Order A**
requested amount: 20
minimum longtime: 60 -> 60% has to be new (12)
**Order B**
requested amount: 10
minimum longtime: 10 -> 10% has to be new (1)

### Expected
There are some weights which should lead to the following result.
**Order A**
new amount: 19
old amount: 1
**Order B**
new amount: 1
old amount: 9

### Actual
**Order A**
new amount: 12
old amount: 8
**Order B**
new amount: 1
old amount: 9

There are too much old articles distributed (8 + 9 = 17 which is more than the available 10).
I think the problem is contributed by the described multiplication above, but I'm not sure. Maybe the model is not solvable this way, I don't know. This is just one example which does not work, perhaps there are more.

Because it is a bit more code and for easier test purposes, I've crated a repository:
[Repo](https://github.com/LucaRitz/blister)

Thank you for taking time

**Comment by LucaRitz** [comment]
I've tested it with an older version.
With 44.0.0 it seems to work, since version 45.0.0 it fails.
Can you confirm this?

**Comment by apete** [comment]
I cloned that repo and imported the project to my IDE (eclipse). But, I can't run the tests. Don't have time to figure out why that doesn't work. Can you put together something simpler?

**Comment by apete** [comment]
I got it running, but please keep things small and simple. This feels big and complicated for me to debug.

Using very large or very small numbers in ExpressionsBasedModel has been problematic before. Behaviour regarding scaling the problem parameters, and how to determine if something is zero or not, are constantly tweaked.

**Comment by LucaRitz** [comment]
You're right, it is a bit too big. I could shorten it, cause there are more requirements modelled than described above which are not necessary to know to reproduce the failed test case.

Ok, I don't think that I am using very large or small numbers (if numbers above MAX_INT or below MIN_INT are meant?), but I have to use a high precision of floating point numbers, because they can be really close together. I had to increase "options.mip_gap" to get the expected best result. Is that also problematic?

**Comment by LucaRitz** [comment]
I just found out that in Version 44.0.0 another test case fails sometimes.
I pushed a commit with that test case to the repo. It is a bit hard to reproduce it, so I execute it ten thousand times to increase the probability it fails.
This case seems to work since 45.0.0.

There is something written about fixing problems related to rounding errors in the changelog of 45.0.0.
So I tried to fix the bug in 44.0.0 by increasing the scale of the BigDecimals. It works most of the time but not always and the computation is very slow.
Is the problem I described in my first comment also related to that change in 45.0.0?

**Comment by apete** [comment]
I assume the actual problem is with some LP subproblem. Add some additional validation (in the IntegerSolver) to check the node problems. (There's already stuff there that you can turn on.)

Set the 'mip_defer' option to make the MIP solver sequential.

When you have a more condensed test case I'll do my best to help find and fix the problem, but as things are now this is simply to big and time consuming for me.

I would also revise the model construction. 

This is a very small        `options.mip_gap = 1.0E-100;`

Why do you do this:

```
        Variable constantBigInt = Variable.make("constant_big_int").integer(true).level(BIG_INT);
        model.addVariable(constantBigInt);
```

I can't see that it's used, but it will affect the scaling of the generated solver instances.

**Comment by LucaRitz** [comment]
OK, I'm gonna have a look at this, thank you.

I'll try to simplify the model and reproduce the failed test case but I need some time to do this.

You're right, the mip_gap is very small. Some optimal solutions seem to be very close together so in the corresponding test cases unexpected results are found (which are correct against the model).

The "constantBigInt" is used on line 101 as a parameter. I reuse it several times to express the multiplication in constraint 4 (line 165). I thought I can reuse the constant because it is not part of the objective function since it does not get a weight.

**Comment by apete** [comment]
Open a new issue when you have a more focused test case.
