### ISSUE TITLE
InverterTask.invert goes into Infinite loop in case of some specific large matrices

### ISSUE THREAD

**Issue by chang-chao** [optimatika/ojAlgo#22]
This is the test code for reproducing the issue.

<pre>
  @Test
  public void test_invert_large_matrix() throws TaskException {
    double[][] data = new double[3000][3000];
    for (int i = 0; i < data.length; i++) {
      for (int j = 0; j < data.length; j++) {
        data[i][j] = 0.9;
      }
    }
    data[0][1] = 1.01;

    PrimitiveMatrix input = PrimitiveMatrix.FACTORY.rows(data);
    double[][] inv = SingularValue.make(input).invert(input.toPrimitiveStore()).toRawCopy2D();

    // The issue:can't  be reached here!!!
  }
</pre>

The reason may be that, after the following line(No.144) of the current SVDnew32 class ,the value the shift local variable becomes NaN in this case.

<pre>
shift = c / (b + shift);
</pre>

**Comment by apete** [comment]
Is there a problem with all large all-elements-equal matrices?

Is there any way to reproduce the problem with smaller matrices?


Could you help me to verify which implementations have this problem. Instantiate the svn by calling the package private constructors directly:

SingularValue<Double> svd = new RawSingularValue();

or

SingularValue<Double> svd = new SVDnew32.Primitive();


There is also an older

SingularValue<Double> svd = new SVDold30.Primitive();

but I'm unsure if that's fully functional at the moment.

**Comment by chang-chao** [comment]
All-elements-equal matrices don't necessarily reproduce the issue,as my test code shows,that data[0][1] = 1.01;other values are 0.9 is one case for reproducing.
RawSingularValue doesn't reproduce because there is "if ((b != ZERO) | (c != ZERO))" check in line 599.
SVDold30 has not been tested.

**Comment by apete** [comment]
I’ve changed the code in SVDnew32 to be the same as in RawSingularValue, but would like to investigate this further.

**Comment by apete** [comment]
That was it.
