### ISSUE TITLE
Looking for On call support 

### ISSUE THREAD

**Issue by sudheergattu** [optimatika/ojAlgo#222]
We are currently adopting OjAlgo for SVD calculation, we were previously using apache commons math3 and observed performance issue during SVD calculation.
 
We are looking for on call support if at all possible for any issues arise or is it possible only if we obtain Optamika subscription?Also, is there any closed source code which further improves the performance of SVD calculation which will be opened after obtaining Optamika subscription.

I am not sure whether this qualifies to be raised as an issue, Please let me know if there is any other channel of communication to be made for these kinds of queries

**Comment by apete** [comment]
@sudheergattu This is possible. Contact me directly at optimatika.se

**Comment by apete** [comment]
@sudheergattu I haven't received any email from you. If you sent one it didn't make it through.

On call support is available via the Optimatika Membership Subscription. Or, that is the intention. I got too busy so setting up the payment alternative was never finished. (Highly unprofessional, I know.) The clients that are on support right now paid for their memberships "manually".

At this moment there is no additional closed source software available. Very soon there will be a next generation optimisation modelling tool. That's probably not of interest to you at this point.

**Comment by sudheergattu** [comment]
Hi @apete ,

Somehow i am not able to send mail to optimatika.se either from microsoft account or my gmail account. Could you please let me know how to send a mail to you or any alternative mail address to discuss further on the issues we see and to inquire on the membership.

**Comment by apete** [comment]
That's strange!

anders at optimatika dot se

The contact form on the optimatika web site also works.

/Anders

**Comment by apete** [comment]
I have still not received anything...
