### ISSUE TITLE
A potential calculation issue of MarkowitzModel

### ISSUE THREAD

**Issue by edwardluzi** [optimatika/ojAlgo#23]
hi there,

Below test case is failed, could you please have a check?
Attached is an reference document  to design the  test case. FYI.

Regards,
Edward

[portfolioTheoryMatrix.pdf](https://github.com/optimatika/ojAlgo/files/303833/portfolioTheoryMatrix.pdf)

 BasicMatrix.Factory<PrimitiveMatrix> matrixFactory = PrimitiveMatrix.FACTORY;
        PrimitiveMatrix cov = matrixFactory.rows(new double[][] { { 0.01, 0.0018, 0.0011 }, { 0.0018, 0.0109, 0.0026 },
                { 0.0011, 0.0026, 0.0199 } });
        PrimitiveMatrix ret = matrixFactory.columns(new double[] { 0.0427, 0.0015, 0.0285 });
        BigDecimal riskAversion = new BigDecimal(1000000);
        MarketEquilibrium marketEquilibrium = new MarketEquilibrium(cov, riskAversion);
        MarkowitzModel markowitz = new MarkowitzModel(marketEquilibrium, ret);
        markowitz.setShortingAllowed(true);
 markowitz.setTargetReturn(BigDecimal.valueOf(0.0427));
  assert (FloatUtil.equal(markowitz.getWeights().get(0).doubleValue(), 0.82745, FloatUtil.Precision.P5));
        assert (FloatUtil.equal(markowitz.getWeights().get(1).doubleValue(), -0.09075, FloatUtil.Precision.P5));
        assert (FloatUtil.equal(markowitz.getWeights().get(2).doubleValue(), 0.26329, FloatUtil.Precision.P5));
        assert (FloatUtil.equal(markowitz.getMeanReturn(), 0.0427, FloatUtil.Precision.P4));
        assert (FloatUtil.equal(markowitz.getReturnVariance(), 0.0084, FloatUtil.Precision.P4));

**Comment by edwardluzi** [comment]
BigDecimal riskAversion = new BigDecimal(1000000); means minimum risk.

**Comment by apete** [comment]
There was a problem when/if the target return (or variance) was set to exactly the max possible value. I've checked in a small fix for that problem.

Generally you should set either targetReturn, targetVariance or riskAversion. Sometimes you may have to adjust the riskAversion to a "size" that enable reaching the target return or variance, but in those cases it should definitely not to an extreme value as 1000000.

**Comment by apete** [comment]
Checked in some further changes - there where wider issues regarding portfolios with shorting allowed. Please verify that the current code works for your use case.

**Comment by edwardluzi** [comment]
hi Anders,

Thanks for you quick response.  I confirm above test case is passed on new source code.

Regards,
Edward
