### ISSUE TITLE
Using ExpressionsBasedModel to solve minimal least-squares problem

### ISSUE THREAD

**Issue by jonasseglare** [optimatika/ojAlgo#236]
I am trying to use the ExpressionsBasedModel to solve a minimal least-squares problem, but I do not obtain the result that I would expect. The problem is to minimize `f(x) = (x - 4)^2` w.r.t. x, which obviously has the solution x = 4, but I get the result x = 0. To demonstrate that, I wrote this program
```java
import org.ojalgo.optimisation.ExpressionsBasedModel;
import org.ojalgo.optimisation.Variable;
import org.ojalgo.optimisation.Expression;
import org.ojalgo.optimisation.Optimisation.Result;


public class OjalgoDemo {
    public static void main(String[] args) {
        ExpressionsBasedModel model = new ExpressionsBasedModel();
        
        // Minimize f(x) = (x - 4)^2, which has minimum x = 4
        
        // (x - 4)^2 = x^2 - 8x + 16.
        // Note that minimum of 
        //   f(x) = x^2 - 8x + k 
        // is the same no matter the choice of k.

        Variable x = model.addVariable("x");
        Expression expr = model.addExpression("objective");

        // Add the x^2 term
        expr.set(x, x, 1.0);
        
        // Add the -8x term
        expr.set(x, -8.0);

        Result result = model.minimise();

        System.out.println("The state: " + result.getState());
        System.out.println("The full result: " + result);
    }
}
```
and compile and run it like this:
```
javac OjalgoDemo.java -classpath ~/.m2/repository/org/ojalgo/ojalgo/47.3.1/ojalgo-47.3.1.jar
java -classpath ".:/home/jonas/.m2/repository/org/ojalgo/ojalgo/47.3.1/ojalgo-47.3.1.jar" OjalgoDemo
```
and obtain this output
```
The state: OPTIMAL
The full result: OPTIMAL 0.0 @ { 0 }
```
Why am I not getting the solution x = 4 in the result?

**Comment by apete** [comment]
https://stackoverflow.com/questions/58919581/ojalgo-solve-least-squares-problem-using-expressionsbasedmodel

**Comment by jonasseglare** [comment]
It turned out that I have to set the weight of `expr`: 
```java
expr.weight(1.0);
```
This will make it contribute to the objective function and I end up the solution ```DISTINCT -16.0 @ { 4 }```. I actually [posted](https://stackoverflow.com/a/58927180/1008794) this same question on StackOverflow and answered it myself.
