### ISSUE TITLE
Question: Possible to get the matrices from the neural network

### ISSUE THREAD

**Issue by DanielMartensson** [optimatika/ojAlgo#242]
Deep neural network is the best tool to have image classification. Right now I have a repository named Deeplearning2C and it's generating a neural network in C and MATLAB. The problem is that Deeplearning2C is using Deeplearning4J. Heavy library that updates often. Deeplearning2C is made for Android as well, but the problem is the application is 500 Mb or more...

I'm planning to replace the library with your simple neural network library inside ojAlgo. 
So I have a question.

Is it possible to get all the matrices from the neural network?

**Comment by apete** [comment]
There is a method `getWeights()` both in NetworkBuilder and ArtificialNeuralNetwork that will get you the weights – but they're package private. If you create a package named `org.ojalgo.ann` in your own project you can access it and expose it publicly.

I have a few things planned for an ANN update:

1) Possibility to store trained networks, and read them back later (is this what you need to do? Seems reasonable to be able to do this...)
2) Option to use float instead of double
3) Multithreaded execution of trained networks
4) Maybe support for some standard file format.

Just not sure when I'll get the time to do this. Short term that "trick" can serve as a workaround

**Comment by DanielMartensson** [comment]
> There is a method `getWeights()` both in NetworkBuilder and ArtificialNeuralNetwork that will get you the weights – but they're package private. If you create a package named `org.ojalgo.ann` in your own project you can access it and expose it publicly.
> 
> I have a few things planned for an ANN update:
> 
>     1. Possibility to store trained networks, and read them back later (is this what you need to do? Seems reasonable to be able to do this...)
> 
>     2. Option to use float instead of double
> 
>     3. Multithreaded execution of trained networks
> 
>     4. Maybe support for some standard file format.
> 
> 
> Just not sure when I'll get the time to do this. Short term that "trick" can serve as a workaround

It would be perfect if ojAlgo can generate an 1D array of every network. I prefer 1D arrays before 2D arrays due to the speed if I want to display a matrix. Also in C language, it's more preferred to use 1D array than 2D arrays. 

What kind of math are you using to train a deep neural network?
Backpropagation with Adam? AdaGrad?

Take your time! :)

**Comment by apete** [comment]
It's just simple back-propagation. I forget the terminology, but believe this is called stochastic gradient descent.

**Comment by DanielMartensson** [comment]
> There is a method `getWeights()` both in NetworkBuilder and ArtificialNeuralNetwork that will get you the weights – but they're package private. If you create a package named `org.ojalgo.ann` in your own project you can access it and expose it publicly.
> 
> I have a few things planned for an ANN update:
> 
>     1. Possibility to store trained networks, and read them back later (is this what you need to do? Seems reasonable to be able to do this...)
> 
>     2. Option to use float instead of double
> 
>     3. Multithreaded execution of trained networks
> 
>     4. Maybe support for some standard file format.
> 
> 
> Just not sure when I'll get the time to do this. Short term that "trick" can serve as a workaround

Hi!

I just connected Vaadin with OjAlgo so your Neural Network library can be a GUI version.
But I did not understand what you mean with "If you create a package named org.ojalgo.ann in your own project you can access it and expose it publicly."?

I have created a package named `org.ojalgo.ann` in my project. Then I don't know what to do else.

**Comment by apete** [comment]
Classes you create in your `org.ojalgo.ann` package can access the package private `getWeights()` methods (this is a trick / workaround). 

Create a utility class/method, in that package, that takes an ANN as input then you'll get access to some otherwise restricted stuff.

If you're using modules, then I believe this is not allowed.

**Comment by DanielMartensson** [comment]
> Classes you create in your `org.ojalgo.ann` package can access the package private `getWeights()` methods (this is a trick / workaround).
> 
> Create a utility class/method, in that package, that takes an ANN as input then you'll get access to some otherwise restricted stuff.
> 
> If you're using modules, then I believe this is not allowed.

Yes! That did not work. I think I have to wait until you release next version of OjAlgo?

```java.lang.IllegalAccessError: class org.ojalgo.ann.NNWeights tried to access method 'java.util.List org.ojalgo.ann.ArtificialNeuralNetwork.getWeights()' (org.ojalgo.ann.NNWeights is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @47c434a6; org.ojalgo.ann.ArtificialNeuralNetwork is in unnamed module of loader 'app')
	at org.ojalgo.ann.NNWeights.getWeights(NNWeights.java:9) ~[classes/:na]```

**Comment by DanielMartensson** [comment]
Will getters be implemented for that ANN class in next version of OjAlgo?

**Comment by apete** [comment]
It's on my todo-list to to do something, but:

1. There is no schedule for new releases
2. I'm not sure what to do. I'd like to investigate the possibility to support some standard file format.

**Comment by apete** [comment]
I'll build something now.

**Comment by apete** [comment]
- The class ArtificialNeuralNetwork now expose public methods `getWeight`, `getBias`, `getActivator`
- There is now an ANN file format and ArtificialNeuralNetwork has methods to read and write.

What I's like you to do:

1. Clone this repository, checkout the `ANN-additions` branch and build your own snapshot version of ojAlgo
2. Try using the new features and report any problems you find
3. Live with this snapshot build for a while. I'd like to investigate which of the other planned changes/additions can be done before releasing a new version.

**Comment by DanielMartensson** [comment]
> I'll build something now – a file format to write and read back a trained network.

I would recommend to generate a .c file and .m file where the user can simulate the neural network in a computer and then implement into a microcontroller. That's cool stuff and very usefull. 

Like this.
https://github.com/DanielMartensson/Deeplearning2C/blob/c5cff334edb20d00d07804906a7ace45694e6d5b/Deeplearning2CApp/src/main/java/se/danielmartensson/deeplearning2c/views/TrainEvalGeneratePresenter.java#L99

**Comment by DanielMartensson** [comment]
>     * The class ArtificialNeuralNetwork now expose public methods `getWeight`, `getBias`, `getActivator`
> 
>     * There is now an ANN file format and ArtificialNeuralNetwork has methods to read and write.
> 
> 
> What I'd like you to do:
> 
>     1. Clone this repository, checkout the `ANN-additions` branch and build your own snapshot version of ojAlgo
> 
>     2. Try using the new features and report any problems you find
> 
>     3. Live with this snapshot build for a while. I'd like to investigate which of the other planned changes/additions can be done before releasing a new version.

I will do that. Give you a reply later.

**Comment by apete** [comment]
> I would recommend to generate a .c file and .m file where the user can simulate the neural network in a computer and then implement into a microcontroller. That's cool stuff and very useful.
> 
> Like this.
> https://github.com/DanielMartensson/Deeplearning2C/blob/c5cff334edb20d00d07804906a7ace45694e6d5b/Deeplearning2CApp/src/main/java/se/danielmartensson/deeplearning2c/views/TrainEvalGeneratePresenter.java#L99

Stuff like that needs to be written by people who need/use it. Can't you just adapt the code you have to be able to read ojAlgo ANN:s as well? (Now the the api you need is exposed)

**Comment by DanielMartensson** [comment]
> > I would recommend to generate a .c file and .m file where the user can simulate the neural network in a computer and then implement into a microcontroller. That's cool stuff and very useful.
> > Like this.
> > https://github.com/DanielMartensson/Deeplearning2C/blob/c5cff334edb20d00d07804906a7ace45694e6d5b/Deeplearning2CApp/src/main/java/se/danielmartensson/deeplearning2c/views/TrainEvalGeneratePresenter.java#L99
> 
> Stuff like that needs to be written by people who need/use it. Can't you just adapt the code you have to be able to read ojAlgo ANN:s as well? (Now the the api you need is exposed)

It was just a suggestion for the comment "I'll build something now – a file format to write and read back a trained network.".

I'm building a web application with Vaadin and your software to generate ANN:s. Will upload it soon as a repo. Will give you a reply later then if you want to use that code.

**Comment by apete** [comment]
https://github.com/optimatika/ojAlgo/pull/263

I added support for 32-bit float and multithreaded invocation/evaluation of the network.

**Comment by DanielMartensson** [comment]
> #263
> 
> I added support for 32-bit float and multithreaded invocation/evaluation of the network.

Will you add drop out layer too? 
Or regularization? Just like Deeplearning4J has.

**Comment by apete** [comment]
Don't know. I'll have to investigate what is required. Are there standards for this?

**Comment by DanielMartensson** [comment]
> Don't know. I'll have to investigate what is required. Are there standards for this?

Regularization is used if your data is noisy.
Dropout is used to set some activation functions to zero or setting a scalar between 0 and 1 multiply with the output of the activation. Dropout can lead to better trained networks.

**Comment by apete** [comment]
Now there is dropouts. If turned on 50% of the nodes in any hidden layer will be randomly dropped during training iterations.

**Comment by apete** [comment]
I'd say I'm done with this. Please help me test what's in the PR. I'll release a new version soon after I get confirmation that everything is ok.

Comment on the PR: https://github.com/optimatika/ojAlgo/pull/263

**Comment by DanielMartensson** [comment]
> I'd say I'm done with this. Please help me test what's in the PR. I'll release a new version soon after I get confirmation that everything is ok.
> 
> Comment on the PR: #263

Yes. I will test it. By the way. Does your neural network have detection? I have seen that ESP Micro processors can have face identification now. 

https://m.youtube.com/watch?v=U7qbehy9aDo

Esp32-Who is C code only. Perhaps you want to have a look at it  :)
