### ISSUE TITLE
What is the correct way to add rows/columns to a SparseStore?

### ISSUE THREAD

**Issue by thomas4g** [optimatika/ojAlgo#25]
My use case for this library involves building up an in-memory store of information from streaming data and thus adding rows or columns to a matrix as new data comes in. It seemed from examining the source that `Store` objects have a fixed size and the only way to grow them would be to copy them into a new object, like so:

 ```java 
SparseStore<Double> sparseStore = SparseStore.makePrimitive(NUM_ROWS, NUM_COLS);
SparseStore<Double> sparseStore2 = SparseStore.makePrimitive((int) sparseStore.countRows(), (int) sparseStore.countColumns() + 1);
sparseStore2.accept(sparseStore);
sparseStore2.add(sparseStore.countRows() - 1, sparseStore.countColumns(), 42);
```

However, for `NUM_ROWS = NUM_COLS = 100000`, the time it took to execute this code was ~15s, and seemed to grow exponentially as I increased matrix size. Is there a more efficient way to simply add a row/column to a matrix?

**Comment by apete** [comment]
Support for sparse data structures is relatively new to ojAlgo. Most likely its missing some useful utilities.

Yes, most data structures in ojAlgo are fixed size I've been thinking about adding MatrixStore that are dynamic lists of (sparse) rows or columns. Sounds like that could be useful to you.

One insert is relatively expensive with a sparse store - bulk inserts could be much more efficient.

What are you going to do with that in-memory store? Are you going to make use of the fact that it is a "matrix" or could you just as well use a sparse array from the org.ojalgo.array package?


One thing you can do now, to avoid copying, is to create a matrix that is larger than what you need initially. When you add a row/column you simply write to a row/column you haven't used yet. The you can do

sparse.logical().limit(actuallyUsedRows, actuallyUsedColumns);

to get a store of the right size.

**Comment by apete** [comment]
Or you could do something like this:

`        
MatrixStore<Double> existing = SparseStore.PRIMITIVE.make(357, 1000000);

final SparseStore<Double> additional = SparseStore.PRIMITIVE.make(3, 1000000);

existing = existing.logical().below(additional).get();
`

It makes it very cheap to add new rows or columns but if you do that many times you get a very complex data structure and that will cost you every time you try to get or set an element. You're best choice depends on what going to do with that matrix.

**Comment by thomas4g** [comment]
@apete The in-memory store will be passed to an algorithm running at intervals that requires the matrix as an input. However, your suggestion about using a bigger matrix than we need is perfect. Thanks for your help and detailed answers!

**Comment by apete** [comment]
If possible keep the number of rows fixed and add columns as needed (only create more columns than you need) and when you add a column set the elements in row index order. You want to avoid inserting new elements in-between existing elements. Everything in a new column is "after" the existing columns.

**Comment by thomas4g** [comment]
That's exactly what I was planning. Cool. Thanks!
