### ISSUE TITLE
Question: Does OjAlgo have min,max, mean etc as MATLAB have?

### ISSUE THREAD

**Issue by DanielMartensson** [optimatika/ojAlgo#251]
Hi!

I'm trying to write this in Java code by using your library.
https://github.com/DanielMartensson/FisherFaces-Examples/blob/master/models/lda.m

So on I have manage to write this:

```
        // Find dimension
        long dim = X.countRows();
        long c = y.longValue(y.indexOfLargestInRow(0, 0)); // Max of column vector y
```

But is there a better way to describe min, max, mean, repmat etc. Basic MATLAB matrix functions?

Here is a list of functions that I need to use but I haven't found them in your library.

- X(:, 3) // Access the whole row at column 3
- mean(X, 2) // Take the average of very row
- repmat(X, n, m) // Extend X at n times down and m times to right
- X(: 1:m) // Cut the matrix from 1:m columns
- sorting with descend
- max and min
- find (y==i) // return a vector with the same length as vector y 

I have search a lot in your API but did not find any matrix manipulation functions.

**Comment by apete** [comment]
I'll try to give you some answers here, but please follow the support guidelines in the future!

> Bug reports, or any issue with the existing code, should be posted at GitHub Issues. GitHub is all about collaboration. If you raise an issue there then participate in resolving it. Please do not use GitHub Issues for general discussions or support requests.

> X(:, 3) // Access the whole row at column 3

Do you mean all rows at column 3?

`Array1D<Double> slicedColumn = matrix.sliceColumn(3);`

> mean(X, 2) // Take the average of very row

`ElementsSupplier<Double> averageOfEveryRow = matrix.reduceRows(Aggregator.AVERAGE);`

> repmat(X, n, m) // Extend X at n times down and m times to right

No direct support, but should be able to use the LogicalBuilder
`LogicalBuilder<Double> logicalBuilder = matrix.logical();`

> X(: 1:m) // Cut the matrix from 1:m columns
```
LogicalBuilder<Double> columns1toM = matrix.logical().limits(-1, m).offsets(1, 0);
LogicalBuilder<Double> specificColumns = matrix.logical().column(0, 2, 3, 6, 8);
```
> sorting with descend

Not everything is sortable. Check which classes implement the `Mutate1D.Sortable` interface

> max and min
```
double max = matrix.aggregateAll(Aggregator.MAXIMUM);
double min = matrix.aggregateAll(Aggregator.MINIMUM);
```
> find (y==i) // return a vector with the same length as vector y

Don't know what this does

**Comment by DanielMartensson** [comment]
> I'll try to give you some answers here, but please follow the support guidelines in the future!
> 
> > Bug reports, or any issue with the existing code, should be posted at GitHub Issues. GitHub is all about collaboration. If you raise an issue there then participate in resolving it. Please do not use GitHub Issues for general discussions or support requests.
> 
> > X(:, 3) // Access the whole row at column 3
> 
> Do you mean all rows at column 3?
> 
> `Array1D<Double> slicedColumn = matrix.sliceColumn(3);`
> 
> > mean(X, 2) // Take the average of very row
> 
> `ElementsSupplier<Double> averageOfEveryRow = matrix.reduceRows(Aggregator.AVERAGE);`
> 
> > repmat(X, n, m) // Extend X at n times down and m times to right
> 
> No direct support, but should be able to use the LogicalBuilder
> `LogicalBuilder<Double> logicalBuilder = matrix.logical();`
> 
> > X(: 1:m) // Cut the matrix from 1:m columns
> 
> ```
> LogicalBuilder<Double> columns1toM = matrix.logical().limits(-1, m).offsets(1, 0);
> LogicalBuilder<Double> specificColumns = matrix.logical().column(0, 2, 3, 6, 8);
> ```
> 
> > sorting with descend
> 
> Not everything is sortable. Check which classes implement the `Mutate1D.Sortable` interface
> 
> > max and min
> 
> ```
> double max = matrix.aggregateAll(Aggregator.MAXIMUM);
> double min = matrix.aggregateAll(Aggregator.MINIMUM);
> ```
> 
> > find (y==i) // return a vector with the same length as vector y
> 
> Don't know what this does

Thank you.
It's impossible to follow your guidelines because I'm looking for more MATLAB equivalent functions. 

I know there is few examples here. But a good guideline according to me would be a list of MATLAB equivalent functions to OjAlgo.
http://www.ojalgo.org/2019/03/linear-algebra-introduction/

You have show me some of them, and I'm very pleased with that. 

Here is an example what find does.

```
>> a = [1 2 3 3 4 1 4 5 6 2 3 5 6 2 6 6 2 5 1 0 7 8]
a =

 Columns 1 through 19:

   1   2   3   3   4   1   4   5   6   2   3   5   6   2   6   6   2   5   1

 Columns 20 through 22:

   0   7   8

>> find(a == 3)
ans =

    3    4   11

>> find(a == 0)
ans =  20
>>
```
