### ISSUE TITLE
Negative index for huge matrix multiplication

### ISSUE THREAD

**Issue by Johannes-Schneider** [optimatika/ojAlgo#252]
For my current research project, I need to be able to process huge matrices (e.g. more than 2^31 cells).
To do so, I implemented my own `MatrixStore<Double>`, which uses a `DoubleBigList` (FastUtil) to store the records internally.
From the existing interfaces and concepts (which accept and return `long` values), I would expect ojAlgo to be able to deal with matrices that contain more than `Integer.MAX_VALUE` cells.
However, upon multiplying my huge matrix I get an `ArrayIndexOutOfBoundsException`.

**Example**

Im trying to reduce the dimensionality of my matrix `A` (65M rows x 35 columns) by multiplying it with the result of my PCA `B` (35 rows x 3 columns) by simply calling `A.multiply(B)`.
This leads to following exception:

```Java
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 1
	at it.unimi.dsi.fastutil.BigArrays.get(BigArrays.java:2259)
	at it.unimi.dsi.fastutil.doubles.DoubleBigArrayBigList.getDouble(DoubleBigArrayBigList.java:276)
	at de.hpi.msc.jschneider.math.SequenceMatrix.get(SequenceMatrix.java:39)
	at de.hpi.msc.jschneider.math.SequenceMatrix.get(SequenceMatrix.java:10)
	at org.ojalgo.matrix.store.MatrixStore.doubleValue(MatrixStore.java:813)
	at org.ojalgo.structure.Access2D.doubleValue(Access2D.java:589)
	at org.ojalgo.array.operation.MultiplyBoth.lambda$static$3(MultiplyBoth.java:119)
	at org.ojalgo.matrix.store.Primitive64Store.fillByMultiplying(Primitive64Store.java:668)
	at org.ojalgo.matrix.store.MatrixStore.multiply(MatrixStore.java:924)
	at org.ojalgo.matrix.store.WrapperStore.multiply(WrapperStore.java:58)
	at org.ojalgo.matrix.store.MatrixStore.multiply(MatrixStore.java:938)
	at org.ojalgo.matrix.store.WrapperStore.multiply(WrapperStore.java:68)
```

For me, this looks like a numeric overflow at some point in the multiplication process, so that ojAlgo tries to access a cell at index `-1`, which of course does not exist.

My custom implementation of the `MatrixStore<Double>` interface is shown down below:
```Java
public class SequenceMatrix implements MatrixStore<Double>
{
    private final long sequenceLength;
    private final DoubleBigList values;

    public SequenceMatrix(long sequenceLength, DoubleBigList values)
    {
        this.sequenceLength = sequenceLength;
        this.values = values;
    }

    @Override
    public PhysicalStore.Factory<Double, Primitive64Store> physical()
    {
        return Primitive64Store.FACTORY;
    }

    @Override
    public Double get(long l1, long l2)
    {
        val columnIndex = isTransposed ? l1 : l2;
        val rowIndex = isTransposed ? l2 : l1;

        val diff = Math.min(rowIndex, sequenceLength - 1 - columnIndex);
        val valueRowIndex = rowIndex - diff;
        val valueColumnIndex = columnIndex + diff;

        var value = values.getDouble(valueColumnIndex + valueRowIndex);
        if (columnSubtrahends != null)
        {
            value -= columnSubtrahends.get(0, columnIndex);
        }

        return value;
    }

    @Override
    public long countColumns()
    {
        if (isTransposed)
        {
            return numberOfRows();
        }
        else
        {
            return numberOfColumns();
        }
    }

    @Override
    public long countRows() 
    {
        if (isTransposed)
        {
            return numberOfColumns();
        }
        else
        {
            return numberOfRows();
        }
    }

    private long numberOfColumns()
    {
        return sequenceLength;
    }

    private long numberOfRows()
    {
        return values.size64() - sequenceLength + 1;
    }
}
```

**Comment by apete** [comment]
You've constructed your own MatrixStore implementation to handle very large matrices, and when you call the default matrix multiplication code you get an error (probably index overflow), is that correct?

You should be able to construct matrices with `Integer.MAX_VALUE` rows and/or columns, but not all supplied implementations can handle it. Some are limited to holding that many elements.

Did you try to simply use RawStore?

Do you need to be able to handle rows or columns larger than what a plain double[] or float[] can hold?

For your use case a transposed version of RawStore (perhaps with float[] as columns) seems a good alternative.

**Comment by Johannes-Schneider** [comment]
Yes, I'm using my custom MatrixStore (`SequenceMatrix`, shown in my initial description), which I'm multiplying with a simple `PrimitiveMatrix64` using the default `multiply` method provided by the `MatrixStore` interface (no custom implementation).
That scenarios leads to the overflow exception shown in my initial comment.

In my scenario, I need to handle larger number of **rows**, columns are usually just a few hundred.
However, unfortunately, I can not fall back to one of the existing Implementations (at least as far as I know), because I'm using a very use-case specific optimization that allows me to only store `#rows + #columns` actual cells (instead of `#rows x #columns` in usual dense matrix implementations).

I think `RawStore`s would always actually store `#rows x #columns` many entries (which is problematic due to main memory constraints), is that correct or can I somehow adapt that?

**Comment by apete** [comment]
Yes, RawStore is fully dense. From what you describe this may be a suitable case for writing a custom MatrixStore. 

I’ll write some tests to see if I can reproduce the problem you describe. You don’t have a repository with a test case to share?

BTW Did see the SpareStore? It may work ok for you.

**Comment by Johannes-Schneider** [comment]
Unfortunately, at this point in time I can not share my repository, because the studies I'm working on are not yet published.
However, I've quickly constructed a test case that demonstrates the issue:

```Java
import it.unimi.dsi.fastutil.doubles.DoubleBigArrayBigList;
import it.unimi.dsi.fastutil.doubles.DoubleBigList;
import junit.framework.TestCase;
import org.ojalgo.matrix.store.MatrixStore;
import org.ojalgo.matrix.store.Primitive64Store;

import static org.assertj.core.api.Assertions.assertThat;

public class TestSequenceMatrix extends TestCase
{
    public void testMultipleHugeSequenceMatrix()
    {
        final long numberOfRecords = 65000000L - 16L;
        final DoubleBigList records = new DoubleBigArrayBigList(numberOfRecords);

        for (long i = 0L; i < numberOfRecords; ++i)
        {
            records.add(1.0d);
        }

        final SequenceMatrix sequenceMatrix = new SequenceMatrix(34, records);
        final MatrixStore<Double> factor = Primitive64Store.FACTORY.makeEye(34L, 3L);

        assertThat(sequenceMatrix.countRows()).isEqualTo(64999951L);
        assertThat(sequenceMatrix.countColumns()).isEqualTo(34L);
        assertThat(sequenceMatrix.count()).isGreaterThan(Integer.MAX_VALUE);

        final MatrixStore<Double> result = sequenceMatrix.multiply(factor);

        assertThat(result.countRows()).isEqualTo(sequenceMatrix.countRows());
        assertThat(result.countColumns()).isEqualTo(factor.countColumns());
    }
}
```

The execution of that test produces the following exception:

```Java
java.lang.NegativeArraySizeException: -61322616

	at org.ojalgo.array.operation.MultiplyLeft.invoke(MultiplyLeft.java:641)
	at org.ojalgo.array.operation.MultiplyLeft$1.conquer(MultiplyLeft.java:567)
	at org.ojalgo.concurrent.DivideAndConquer.divide(DivideAndConquer.java:76)
	at org.ojalgo.concurrent.DivideAndConquer.invoke(DivideAndConquer.java:49)
	at org.ojalgo.array.operation.MultiplyLeft.lambda$static$13(MultiplyLeft.java:571)
	at org.ojalgo.matrix.store.Primitive64Store.fillByMultiplying(Primitive64Store.java:666)
	at org.ojalgo.matrix.store.MatrixStore.multiply(MatrixStore.java:924)
	at org.ojalgo.matrix.store.MatrixStore.multiply(MatrixStore.java:938)
```

Regarding your last question: I assume you meant Spar**s**eStore, right? If so, I did have time to investigate it in detail, however, on first glance I noticed some `int[]` members, which might be problematic when dealing with so huge matrices?

**Comment by apete** [comment]
I haven't looked much at this yet, but I can tell you  a few things:

1. On the examples page https://www.ojalgo.org/code-examples/ there is an example demonstrating how do a custom `MatrixStore`. You really should implement the recommended additional methods described in the `BetterPerformingEye` class.
2. In a case like this with very large matrices you have to control in which matrix type (or even instance) the multiplication results end up. As it is now a product matrix is created for you using the factory supplied by the `physical()` method. In your custom class you use `Primitive64Store.FACTORY`. That's a fully dense implementation limited to `Integer.MAX_VALUE` elements. That won't work for you.
3. You need to create something that implements `TransformableRegion` (and that's a lot more work) or you try to use `SparseStore`. Either do `sparseStore.fillByMultiplying(customStore, anyStore)` or `customStore.multiply(anyStore,sparseStore)`.

**Comment by apete** [comment]
Try it with this branch: https://github.com/optimatika/ojAlgo/pull/255

**Comment by Johannes-Schneider** [comment]
Thank you for your effort. I will try your fixes as soon as I have some spare time.
I will of course report back whether this fix helped.

**Comment by apete** [comment]
I assume it's ok now
