### ISSUE TITLE
How to get the coefficient/weight of the variable in the objective?

### ISSUE THREAD

**Issue by danyaljj** [optimatika/ojAlgo#27]
Trying to extend [our wrapper to ojAlgo](https://gitlab-beta.engr.illinois.edu/cogcomp/inference/blob/master/src/main/java/edu/illinois/cs/cogcomp/infer/ilp/OJalgoHook.java). Any ideas how to get the weight of the variables? How about this? 

``` java
model.getVariable(index).getContributionWeight()
```

Surprising that the output type is `BigDecimal` ...

**Comment by apete** [comment]
The getContributionWeight() method will return the value you set with the weight(Number) method. There used to be a setContributionWeight(Number). Just "weight" was shorter and more convenient when building the models. Similar inconsistencies exists with getLowerLimit() and getUpperLimit() that are set by lower(Number) and upper(Number).

The actual variable "weights" sent to the solver are derived/aggregated from the weights of all variables and expressions and rescaled to improve numerical accuracy.

**Comment by apete** [comment]
Looked briefly at your code:

`model.getObjectiveExpression();`

That's not a good idea! Calling that method you'll get a new Expression every time that is derived from all variables, expressions and their weights. And modifying that expression will NOT modify the optimisation model to be solved.

**Comment by danyaljj** [comment]
I think you're referring to [this line](https://gitlab-beta.engr.illinois.edu/cogcomp/inference/blob/master/src/main/java/edu/illinois/cs/cogcomp/infer/ilp/OJalgoHook.java#L25)?
Seems like it's never been used ....

**Comment by apete** [comment]
Improved the javadoc a tiny bit.
