### ISSUE TITLE
Proper introduction to Primitive matrix

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [optimatika/ojAlgo#275]
I'm always frustrated when I open the local javadoc but found a matrix class but have no description about it.
The naming is verbose,but not enough to narrow down a specific detail

Just a small description that states by primitive is it int?float?
The 32 vs 64 bit?as in float vs double?or max access matrix size?
Possibly also documents some other class if needed.

No alternative,javadoc is best and easiest to implement,also included in source code just a few line and consistent.

**Comment by apete** [comment]
Yes I agree. You are very welcome to help out with a PR. While you're working on that, if you have questions, I'll be more than happy to answer them.

**Comment by apete** [comment]
Originally, in ojAlgo, _primitive_ referred to primitive `double` . As support for `float` was added some names where changed from just Primitive to Primitive32 and Primitive64, respectively for `float` and `double`.

**Comment by xwaeaewcrhomesysplug** [comment]
What's the usage of these many factories?and stores compare to the matrix class itself?Filled the primitive docs in my fork.

**Comment by xwaeaewcrhomesysplug** [comment]
I mean for eg the primitive matrix have nested class and one of it is factory at the same package there's also a solid class as factory,
What's the difference to user?performance?

**Comment by apete** [comment]
The main choice is between using BasicMatrix (its type specific subclasses) or not.

This post at ojAlgo's site answers some of these questions:

https://www.ojalgo.org/2019/03/linear-algebra-introduction/

Further, some wiki pages here at GitHub that have not yet been moved to the new site, may give additional info:

https://github.com/optimatika/ojAlgo/wiki/Create-Custom-MatrixStore
https://github.com/optimatika/ojAlgo/wiki/Sparse-Matrices

Even if not all wiki pages have been transferred all example code is available here:

https://www.ojalgo.org/code-examples/

**Comment by LJWxyz** [comment]
thanks for the info,but i found out that you also have some ann class.I think i will treat this issue as solved.Sorry this is my second account you can close this issue.^^
