### ISSUE TITLE
fixing some bad constructor

### ISSUE THREAD

**Issue by LJWxyz** [optimatika/ojAlgo#279]
I found out the official way is by using factory.However,the basic constructor should be available.And is in fact available but in a  funny layout.

So by default java programmers should be used to creating objects with;SomeClass varname=new SomeClass();
However in org.ojalgo.matrix.store.Primitive32Store,we don't do that here.We do Primitive32Store.Primitive32Store(int,int);
or we do it using factory.
Is this expected and required for a reason?

The best way to fix it is make it normal and a normal people can even find the cnstructor in javadoc,or even slowly removing some factory is not needed.However,any changes should not affect performance.If hurt performance.Keep it like that 

>What will be found by newbies
error: no suitable constructor found for Primitive32Store(no arguments)
constructor Primitive32Store.Primitive32Store(int,int) is not applicable....

**Comment by apete** [comment]
Yes, this is very much intentional. No, you should use the factories.

This is a very common design pattern that you best get used to.
