### ISSUE TITLE
NumberFormatException raised processing MPS file

### ISSUE THREAD

**Issue by lukek27** [optimatika/ojAlgo#28]
Creation of a model from MPS file fails. I first tried with a CPLEX-created MPS file and I got a NumberFormatException. Then I tried with a simple MPS instance and it worked. When I modified coefficients to include decimal digits, I got the exception again. Here is the exception I got calling MathProgSysModel.make(fileName):

Exception in thread "main" java.lang.NumberFormatException
	at java.math.BigDecimal.<init>(BigDecimal.java:596)
	at java.math.BigDecimal.<init>(BigDecimal.java:383)
	at java.math.BigDecimal.<init>(BigDecimal.java:806)
	at org.ojalgo.optimisation.MathProgSysModel.parseSectionLine(MathProgSysModel.java:633)
	at org.ojalgo.optimisation.MathProgSysModel.make(MathProgSysModel.java:400)

Here is the MPS test file I used. It works fine with CPLEX. The exception is raised when parseSectionLine processes the first line of the COLUMNS section. If you remove all decimals and leave integer numbers, the code works fine.

```
NAME          TESTPROB
ROWS
 N  COST
 L  LIM1
 G  LIM2
 E  MYEQN
COLUMNS
    XONE      COST                 1.1   LIM1                 1.1
    XONE      LIM2                 1.1
    YTWO      COST                 4.1   LIM1                 1.1
    YTWO      MYEQN               -1.1
    ZTHREE    COST                 9.1   LIM2                 1.1
    ZTHREE    MYEQN                1.1
RHS
    RHS1      LIM1                 5.1   LIM2                10.1
    RHS1      MYEQN                7.1
BOUNDS
 UP BND1      XONE                 4.1
 LO BND1      YTWO                -1.1
 UP BND1      YTWO                 1.1
ENDATA
```

**Comment by apete** [comment]
MPS files have fixed columns. You can't just add decimals without also deleting previous empty space.

What error did you get with that CPLEX-generated file?

**Comment by lukek27** [comment]
Thanks, that did indeed fix the issue I had with the small test instance. The CPLEX-generated file also raised a NumberFormatException. In this case, I did not make any change after the CPLEX generation. You may find the mps instance (with extension renamed to .txt) attached below.

[0845.txt](https://github.com/optimatika/ojAlgo/files/566729/0845.txt)

**Comment by apete** [comment]
I believe this explains the problem:

http://eaton.math.rpi.edu/cplex90html/reffileformatscplex/reffileformatscplex7.html

ojAlgo currently does not support those extensions.

**Comment by lukek27** [comment]
Yes, that does indeed explain the problem!
Thanks for your quick assistance.
