### ISSUE TITLE
Aggregator.MAXIMUM does not work for negative numbers

### ISSUE THREAD

**Issue by VitekVlcek-Broadcom** [optimatika/ojAlgo#286]
When `Primitive64Store` contains only negative numbers  then `dataArray.aggregateAll(Aggregator.MAXIMUM)` returns always `0.0`.
It is caused by the wrong initial value `ZERO`
https://github.com/optimatika/ojAlgo/blob/4cf22f15f96d2658580d7c4b2b5596f71b3592a7/src/org/ojalgo/function/aggregator/PrimitiveAggregator.java#L184
It is supposed to be `private double myValue = PrimitiveMath.NEGATIVE_INFINITY;`

**Comment by apete** [comment]
Thanks for reporting this. Will most likely release v48.3.1 soon with that fixed.
