### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by Programmer-Magnus** [optimatika/ojAlgo#289]
When I run this test it fail to complete the last multiplication. It hangs.

    public void testAboveBelowStore() {
        SparseStore<Double> Au = PhysicalStore.PRIMITIVE64.makeSparse(2, 4);
        SparseStore<Double> Al = PhysicalStore.PRIMITIVE64.makeSparse(1, 4);
        MatrixStore<Double> A = Au.logical().below(Al).get();
        Primitive64Store x = Primitive64Store.FACTORY.make(4, 1);
        MatrixStore<Double> work1 = Au.multiply(x);        
        MatrixStore<Double> work2 = Al.multiply(x);        
        MatrixStore<Double> failToCompute = A.multiply(x);        
    }

**Comment by Programmer-Magnus** [comment]
Another example:
    public void testAboveBelowStore2() {
        Primitive64Store Au = Primitive64Store.FACTORY.make(2, 4);
        Primitive64Store Al = Primitive64Store.FACTORY.make(1, 4);
        MatrixStore<Double> A = Au.logical().below(Al).get();
        Primitive64Store x = Primitive64Store.FACTORY.make(4, 1);
        MatrixStore<Double> work1 = Au.multiply(x);        
        MatrixStore<Double> work2 = Al.multiply(x);  
        PhysicalStore<Double> B = A.copy();
        MatrixStore<Double> works3 = B.multiply(x);
        MatrixStore<Double> failToCompute = A.multiply(x);        
    }

**Comment by apete** [comment]
I can't reproduce this. Your examples work when I run them. Is it, exactly, this code that fails for you?

You should not have to copy...

**Comment by Programmer-Magnus** [comment]
"infinite loop" was my assumption when program froze but did not crash, I lacked a better description, the method just not return.

I am sorry for the inconvenience. I now believe I was confused by Netbeans.

If I step through this code using "Debug Focused Test Method" using "Step into" or "Step over" it start but newer pass this "failtocompute" line.  But it seems like this is actually some kind of hidden break point, because if I press Contiue(F5) it will proceed to the next line as it should have done from the beginning.
 
I also tried to select the line and show the result of the multiplication but then the GUI hangs until I stop the test.

It stops/waits on line 120 in the multiplication in the get() call.
            return new AboveBelowStore<>(futureAbove.get(), below); 

I learned something about Netbeans.
Thank you for your answer. I think you can close this issue.
