### ISSUE TITLE
Missing function to delete a constraint?

### ISSUE THREAD

**Issue by atmaca94** [optimatika/ojAlgo#29]
Hi, im integrating this solver to my project. I managed to delete bounds of a variable but constraints what are created with 
Expression c = model.addExpression("c").level(value);
c.setLinearFactors(model.getVariables(), foobar);

i cant delete completely from the model, where the counter of expressions decrease too.
I tried setting the levels null, like deleting bounds for variable, but they still remain in the model, even the bounds are no more visible. So am I doing something wrong or does this function doesnt exist?

Regards
alper

**Comment by apete** [comment]
If you set the limits to null then the expression is no longer a constraint. The expression is still there but it is not used for anything. I'll think about adding the possibility to actually delete an expression, but you shouldn't need that.

**Comment by atmaca94** [comment]
I set the limits to null, both lower and upper and even tried with level. It indeed deletes the constraint from the model and has no more effect, but the constraint still remains in the solver internally. I can see that on the counter (model.countExpression()) still counts the constraint, what is set to null.

**Comment by apete** [comment]
model.countExpression()

That counts expressions, not constraints.

An expression (or a variable) becomes a constraint when/if you set an upper or lower limit on it. An expression could just as well be part of the objective function. It becomes part of the objective when/if you assign a weight to it. One and the same expression could be both a constraint and a part of the objective. If both an upper and lower limit is set (and they are different) the expression  is in fact two constraints. If neither a weight nor any of the limits are set then the expression has no real meaning/function and could just as well be deleted. (This seems to be your case.) Actually deleting it or not makes no real difference. I will probably make it possible to delete expressions, but you do not need to wait for this feature.

**Comment by atmaca94** [comment]
thanks for the good explanation.
my goal: I want that the counter of model.countExpressions() decreases after doing this:
 
model.getExpression("any expression").weight(null).level(null).lower(null).upper(null);

The counter still stays the same after that.
I need that function to display the amount of Expressions in my project after removing constraints.
How would u suggest to do that, before u maybe add somewhen this function?
(sorry if I ask trivial newbie questions, im a bit new)

**Comment by apete** [comment]
model.constraints().count();
