### ISSUE TITLE
An official efficient implementations for merging those matrixes~

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [optimatika/ojAlgo#291]
An official efficient implementations for merging those matrixes~

Yes,We can create matrix with array however it is not so easy to merge them.
Current known solution is manually create a bigger matrix put that small one in there manually.
Plus if used wrong function may return other types,more development time again.

Ideally is of course a one size fit all solution a function that can take any matrix merge them.
Of course that is a naive ideal mindset.If achieved will of course decrease the maintainance cost.

A realistic solution would probably be a a function with in a well known class.(matrix itself?utils?)
with type specific matrix implementations and a type lossy implementations(kinda one fit all?).
Of course,type lossy on a primitive matrix would be a stupid implementations for performance.
Sadly,the primitive may not have this nice function first,maybe copy paste editing may work with good base.
The general core matrix should have the implementations first as test.

Alternative
Maybe not from high level thinking but a lower level manipulation?
Possible gain less memory overhead,faster efficient.
Sadly,No good advice or experience can be given.

Tried example,It should be very bad pls do not use

int maxweightl=0;
for(double[] arrw:listflattenweights){if(maxweightl>arrw.length){maxweightl=arrw.length;}}
outmat=org.ojalgo.matrix.store.Primitive64Store.FACTORY.make(listflattenweights.length+1,maxweightl);//test to make sure loseless
outmat.fillRow(0,0, org.ojalgo.structure.Access1D.wrap(arr));//probably will have no interval or exterpolation,test needed
realout=outmat.logical().below(org.ojalgo.matrix.store.Primitive64Store.FACTORY.rows(listflattenweights)).get();

**Comment by apete** [comment]
?! Not really sure what you're talking about.

If you have programming questions then please use [StackOverflow](https://stackoverflow.com/search?tab=newest&q=ojalgo) for that.

An issue here at GitHub should be a bug report, pull request, or similar.
