### ISSUE TITLE
Matrix solution performance

### ISSUE THREAD

**Issue by winsway** [optimatika/ojAlgo#292]
**I would like to use your math library for CFD matrix calculations, because I see that your matrix solution performance tests work well in all Java libraries. I am using the conjugate gradient method in ojAlgo to solve the matrix, my matrix size is 2500 square matrix by sparse matrix, the matrix symmetry is very good. However, the solving speed is not very ideal, and it takes about 250ms. I am worried that the calculation speed will be seriously reduced when the matrix size is larger.**

**Comment by winsway** [comment]
I tested MTJ's(1.0.4) sparse matrix solver, using the same algorithm, MTJ's sparse matrix processing is much more quickly.

**Comment by apete** [comment]
Can you give me some small code snippet so I can see what you're doing.

**Comment by winsway** [comment]
I have define a variable coefficient. i use two way to test matrix solvers.
first: ojAlgo
```
   public SparseStore<Double> tmpA= SparseStore.PRIMITIVE64.make(size,size);
   public Primitive64Store RHS= Primitive64Store.FACTORY.make(size, 1);
```
then I use solver to solve. 
```
        ConjugateGradientSolver tmpSolver = new ConjugateGradientSolver();
        tmpSolver.configurator().iterations(100);
        Primitive64Store current = FvMatirx.setPrimitive64Store(F.Internal);
         try {
            tmpSolver.solve(Tequ.tmpA, Tequ.RHS, current);
        } catch (RecoverableCondition ex) {
            Logger.getLogger(MySimpleWTTGPBE1D.class.getName()).log(Level.SEVERE, null, ex);
        }
        fvSolution.RESOR[IFI] = tmp.getIterationMonitor().residual();
        F.Internal = FvMatirx.setMTJValue(solver, F.Internal);
```
Second: MTJ
```
   public FlexCompRowMatrix tmpA = new FlexCompRowMatrix(size,size);
   public Vector   RHS = new DenseVector(size);
```
then I use solver to solve.

   
```
        no.uib.cipr.matrix.Vector solver = FvMatirx.setMTJvector(F.Internal);
        CGS tmp = new CGS(solver);
        IterationMonitor iter = new DefaultIterationMonitor(100, 1e-6, 1e-6, 1e40);
        tmp.setIterationMonitor(iter);
        try {
            tmp.solve(Tequ.tmpA, Tequ.RHS, solver);
        } catch (IterativeSolverNotConvergedException ex) {
            Logger.getLogger(MySimpleWTTGPBE.class.getName()).log(Level.SEVERE, null, ex);
        }
        fvSolution.RESOR[IFI] = tmp.getIterationMonitor().residual();
        F.Internal = FvMatirx.setMTJValue(solver, F.Internal);
```

MTJ is more quickly. Could it be that my way of using ojAlgo is wrong?

**Comment by apete** [comment]
Just a few comments:

1. If MTJ is using some good quality native code (like Apple's veclib) then pure Java code cannot compete for more complex algorithms on larger matrices.

2.  This invocation

`tmpSolver.solve(Tequ.tmpA, Tequ.RHS, current);`

copies the input `A` matrix to an internal representation of sparse rows. That copying is not very efficient. In particular, I just realised, if the input is a sparse (column oriented) matrix this may become very slow with larger matrices.

3. Instead try this:

```
List<Equation> equations = ...
tmpSolver.resolve(equations, current);
```
Don't extract/create the matrices `Tequ.tmpA` and `Tequ.RHS` instead create a list of equations and feed those to the solver.

**Comment by winsway** [comment]
> 
> 
> Just a few comments:
> 
>     1. If MTJ is using some good quality native code (like Apple's veclib) then pure Java code cannot compete for more complex algorithms on larger matrices.
> 
>     2. This invocation
> 
> 
> `tmpSolver.solve(Tequ.tmpA, Tequ.RHS, current);`
> 
> copies the input `A` matrix to an internal representation of sparse rows. That copying is not very efficient. In particular, I just realised, if the input is a sparse (column oriented) matrix this may become very slow with larger matrices.
> 
>     1. Instead try this:
> 
> 
> ```
> List<Equation> equations = ...
> tmpSolver.resolve(equations, current);
> ```
> 
> Don't extract/create the matrices `Tequ.tmpA` and `Tequ.RHS` instead create a list of equations and feed those to the solver.

thank for your help. The improved performance of the matrix has been significantly improved, and the calculation time is about 8ms (size 2500). For CFD calculations that require high-performance mathematical solvers, because of too many cells. I look forward to ojAlgo's ability to develop parallel matrix solving algorithms. I will enrich the ojAlgo library based on some matrix solving algorithms of MTJ, such as BiCGstable, GMRES .

**Comment by apete** [comment]
Great that it worked for you. Pull requests with additions or improvements are very welcome!
