### ISSUE TITLE
java.lang.NegativeArraySizeException: -727379968,But in range

### ISSUE THREAD

**Issue by xwaeaewcrhomesysplug** [optimatika/ojAlgo#296]
I tried to do a test

**To Reproduce**
public class Testmemojalgo{
	
	public void plugstart(){
		System.out.println("start test");
		try{
		long st=System.nanoTime();
		org.ojalgo.matrix.Primitive64Matrix.Factory matrixFactory = org.ojalgo.matrix.Primitive64Matrix.FACTORY;
		org.ojalgo.matrix.Primitive64Matrix mat=matrixFactory.makeFilled(1000000,1000000,new org.ojalgo.random.Gamma());
		System.out.println(System.nanoTime()-st);
		System.out.println("testfinished,with primitive64matrix .ojalgo");
		}catch(Exception e){e.printStackTrace();}
	}
	
}
console out>
java.lang.NegativeArraySizeException: -727379968
        at org.ojalgo.array.Primitive64Array.<init>(Primitive64Array.java:112)
        at org.ojalgo.matrix.store.Primitive64Store.<init>(Primitive64Store.java:402)
        at org.ojalgo.matrix.store.Primitive64Store$1.make(Primitive64Store.java:167)
        at org.ojalgo.matrix.store.Primitive64Store$1.make(Primitive64Store.java:64)
        at org.ojalgo.matrix.store.PrimitiveFactory.makeFilled(PrimitiveFactory.java:61)
        at org.ojalgo.matrix.store.PrimitiveFactory.makeFilled(PrimitiveFactory.java:37)
        at org.ojalgo.matrix.MatrixFactory.makeFilled(MatrixFactory.java:967)
      .....

As you can see th size is definitely not the exception size onor exceed the int size.

**Comment by apete** [comment]
That's a huge dense matrix. It's like 7TB in a single matrix - that won't work.

Somewhere in the code chain there is an integer overflow (I guess) that's causing the negative array size. Possibly there is a bug related to this, but that's not relevant for you. A single dense matrix that is 7TB just won't work.

Doing this should work:

`matrixFactory.makeSparse(1_000_000,1_000_000);`

but you can't "fill" it. You have to keep it sparse.

**Comment by xwaeaewcrhomesysplug** [comment]
Sadly,I does not know how to use the sparse factory.
>
org.ojalgo.matrix.store.SparseStore.Factory matrixFactory = org.ojalgo.matrix.store.SparseStore.Factory();
		org.ojalgo.matrix.store.SparseStore mat=matrixFactory.makeSparse(1000000,1000000);

That does not seems to compile I am kinda confused

**Comment by xwaeaewcrhomesysplug** [comment]
Oops,thanks the copy paste with your code works,i thought need change factory thanks.^^

**Comment by xwaeaewcrhomesysplug** [comment]
Then,for this issue.I think you can close it.Will be excited if the integer overflow is fixed.
As a side question,will the sparsefactory created matrix take some performance suffer?Or maybe i need benchmark it?

**Comment by xwaeaewcrhomesysplug** [comment]
of course here is the final snippets for future reference.
		org.ojalgo.matrix.Primitive64Matrix.Factory matrixFactory = org.ojalgo.matrix.Primitive64Matrix.FACTORY;
		org.ojalgo.matrix.Primitive64Matrix.SparseReceiver mat=matrixFactory.makeSparse(1000000,1000000);

Maybe we can add it to wiki or website.as example

**Comment by apete** [comment]
Feel free to add things you think may be useful to others to the wiki.
