### ISSUE TITLE
Sparse matrix performance

### ISSUE THREAD

**Issue by winsway** [optimatika/ojAlgo#297]
**I use sparse matrix class to deal with the coefficient of equation, and need to assign value, and find that the process is time-consuming. The access performance of the sparse matrix really needs to be improved. **
the matrix size is 98820x98820.
梯度离散时间：#without sparse operation
ExecutionTime = 2.239 s  ClockTime = 2 s

扩散项离散时间：#have sparse operation ,it use 14 s
ExecutionTime = 16.843 s  ClockTime = 17 s

GaussSeidelSmoothSolver:  Solving for T, Initial residual = Infinity, Final residual = Infinity, No Iterations 500
求解耗费时间：# i use the List<Equation> just use 4s.
ExecutionTime = 20.329 s  ClockTime = 20 s

  ```
 protected void interfaceFlux(
            Cell cellP,
            Cell cellN,
            double gammaf,
            double Ef,
            Vector gradf,
            Vector Tf,
            FvMatrix coe,
            double alpha,
            int ncmpt
    ) {
        int IJP = cellP.index();
        int IJN = cellN.index();
        double dCF = Tensor.sub(cellN.shape.centroid, cellP.shape.centroid).mag();
        double gDiff = gammaf * Ef / dCF;
        //
        double nonOrth = gammaf * Tensor.dotDouble(gradf, Tf) * alpha;
        //
        coe.addAValue(IJP, IJN, symbol.value * gDiff);
        coe.addAValue(IJN, IJP, symbol.value * gDiff);
        coe.addAValue(IJP, IJP, -coe.getA(IJP, IJN));
        coe.addAValue(IJN, IJN, -coe.getA(IJN, IJP));
        coe.addSource(IJP, ncmpt, -symbol.value * nonOrth);
        coe.addSource(IJN, ncmpt, +symbol.value * nonOrth);
    }
```
The detail is:

```
  public void addAValue(
            int row,
            int col,
            double value
    ) {
        this.tmpA.add(row, col, value);
    }
```
the tmpA is define as:
`public SparseStore<Double> tmpA;`

I really need your help~. List<equation> is a great way to deal solver equation. but I have to use sparse matrix to store coefficient.

**Comment by apete** [comment]
Can't see what you're doing. Random access on a sparse matrix will be slow. Why do you need a SparseStore?

**Comment by winsway** [comment]
Because I need to store a lot of data, I need to use a sparse matrix.

**Comment by apete** [comment]
But is it just a temporary store? Later you copy to a List<Equation>. Can't you store it there all the time?

When inserting to the SparseStore it very much helps to insert in a strictly increasing index order (column major).

**Comment by winsway** [comment]
Last time you recommended that I use a List<equation> for calculations. This method is very effective. Every time I calculate a sparse matrix, I need to reinitialize it because the coefficients are changing.

**Comment by winsway** [comment]
I found the problem, the initial sparse is very slow. so I changed the way. 
  ```
       if (tmpA == null) {
            tmpA = SparseStore.PRIMITIVE64.make(size, size);
        } else {
            tmpA.nonzeros().forEach(view -> tmpA.set(view.row(), view.column(), 0));
        }

        if (source == null) {
            source = SparseStore.PRIMITIVE64.make(size, nComponents);
        } else {
            source.nonzeros().forEach(view -> source.set(view.row(), view.column(), 0));
        }

        if (internalCoeffs == null) {
            internalCoeffs = SparseStore.PRIMITIVE64.make(size, nComponents);
        } else {
            internalCoeffs.nonzeros().forEach(view -> internalCoeffs.set(view.row(), view.column(), 0));
        }

        if (boundaryCoeffs == null) {
            boundaryCoeffs = SparseStore.PRIMITIVE64.make(size, nComponents);
        } else {
            boundaryCoeffs.nonzeros().forEach(view -> boundaryCoeffs.set(view.row(), view.column(), 0));
        }
```

**Comment by apete** [comment]
There is a method `boundaryCoeffs.reset();`

When inserting to the SparseStore it very much helps to insert in a strictly increasing index order (column major).

**Comment by winsway** [comment]
I have test the method of `reset();` just now. it is slow like `SparseStore.PRIMITIVE64.make(size, nComponents);` 
`boundaryCoeffs.nonzeros().forEach(view -> boundaryCoeffs.set(view.row(), view.column(), 0));` is more effective.

**Comment by winsway** [comment]
> There is a method `boundaryCoeffs.reset();`
> 
> When inserting to the SparseStore it very much helps to insert in a strictly increasing index order (column major).

I have test the method of reset(); just now. it is slow like SparseStore.PRIMITIVE64.make(size, nComponents);
boundaryCoeffs.nonzeros().forEach(view -> boundaryCoeffs.set(view.row(), view.column(), 0)); is more effective.

**Comment by winsway** [comment]
> There is a method `boundaryCoeffs.reset();`
> 
> When inserting to the SparseStore it very much helps to insert in a strictly increasing index order (column major).

I have test the method of `reset();` just now. it is slow like` SparseStore.PRIMITIVE64.make(size, nComponents);`
`boundaryCoeffs.nonzeros().forEach(view -> boundaryCoeffs.set(view.row(), view.column(), 0));` is more effective.

**Comment by apete** [comment]
That seems very strange. `reset()` should be faster. Are you sure about your test setup?

With that `nonzeros().forEach` you are doing random access, it's just that you target precisely nonzero elements that needs to be reset. The `reset()` method is better than that.

**Comment by winsway** [comment]
> That seems very strange. `reset()` should be faster. Are you sure about your test setup?
> 
> With that `nonzeros().forEach` you are doing random access, it's just that you target precisely the nonzero elements that needs to be reset. The `reset()` method is better than that because it doesn't do random access.

yes, I am sure. I just need the coefficient to be zero, then I reset the coefficient according my physical equation.
