### ISSUE TITLE
Surprisingly slow on fairly small problem

### ISSUE THREAD

**Issue by djahandarie** [optimatika/ojAlgo#30]
On a 5520-binary-variable (all weighted) 500-expression ExpressionsBasedModel minimise, ojalgo can take up to 8GB of ram and 8 seconds. (In our case, the time is acceptable, but the RAM usage is too high.) The model happens to be calculating a subgraph (each binary variable representing an edge).

If I directly build a LinearSolver as follows (which I guess is solving the linear relaxation?),
```java
model.setMinimisation();
Builder b = LinearSolver.getBuilder();
LinearSolver.copy(model, b);
Result linearResult = b.build().solve();
```
then it performs somewhat better (6 seconds), but unfortunately I need to use reflection to invoke `model.handleResult(linearResult)` because it is private, so I can't really use this trick in production. Either way, the memory usage seems to be happening here.

GLPK solves this same problem in a couple MB of RAM and 100ms, so it seems like it must be doing something fundamentally different, but I'm not sure what.

Is this the expected performance, and are there any tricks that can be used to speed things up?

**Comment by apete** [comment]
There is no trick. What you need is for the linear solver to make use of sparse data structures. Currently it does not (the convex solver does to some extent). Implementing this shouldn't be hard.

The ojAlgo solvers are not comparable to native (commercial) solvers in terms of performance and resource consumption. They're pure Java alternatives for smaller/simpler cases.

If you want solve the linear relaxation you have several options:

1) Create the model that way

2) Call model.relax(boolean);

3) Supply your own Optimisation.Integration using ExpressionsBasedModel.addIntegration(...) If you write your code in the org.ojalgo.optimisation package you can instantiate and delegate to any of the existing implementation.

I guess writing a GLPK integration shouldn't be too hard either, provided they have a Java interface. 

With your little trick to solve the relaxed problem execution time goes down from 8s to 6s. This makes me think you never actually make use of the MIP solver.

**Comment by djahandarie** [comment]
Aha! Sparse vs dense certainly seems like it could account for the difference.

If I relax the model using methods 1 or 2, it actually does not speed up at all. Not sure why...

As for integrations, I in fact started with ojAlgo in an effort to eliminate unpure code (I was using GLPK before via https://www.xypron.de/projects/linopt/), but perhaps it's unavoidable...

Unless you want to keep this ticket open to track sparse linear solving, I'm fine with it being closed. Thank you for your quick response!

**Comment by apete** [comment]
> On 16 Dec 2016, at 23:58, Darius Jahandarie <notifications@github.com> wrote:
> 
> Aha! Sparse vs dense certainly seems like it could account for the difference.

I’ve had this (sparse LP) on my todo list for a long time, but so far other things have been prioritised. ojAlgo is an open source project. Anyone can contribute…


> If I relax the model using methods 1 or 2, it actually does not speed up at all. Not sure why…

Most likely the relaxed problem is solved to an integer solution anyway. What you did before by-passed both the presolvers and the integer solver, and that earned you 2s. (I guess)


> As for integrations, I in fact started with ojAlgo in an effort to eliminate unpure code (I was using GLPK before via https://www.xypron.de/projects/linopt/), but perhaps it's unavoidable…

Most use cases would be reversed. You start with ojAlgo and if you discover the built-in solvers are not enough you can switch to some other without changing your main program in any way - you just add a solver integration. I’ve built such for CPLEX and MOSEK and outlined one for GUROBI.


> Unless you want to keep this ticket open to track sparse linear solving, I'm fine with it being closed. Thank you for your quick response!

I prefer to have the Issues here at GitHub restricted to bugs - not a wish list.

**Comment by apete** [comment]
ojAlgo now has a sparse simplex LP solver.
