### ISSUE TITLE
Inequality constraints are not respected by the ConvexSolver

### ISSUE THREAD

**Issue by baracil** [optimatika/ojAlgo#300]
Hi,

I use the ConvexSolver to solve a problem with a positive constraint on the variables. For some cases, the positive constraint is not respected, i.e. some variables are negative even though the solver indicates an optimal solution.

I managed to isolate such a case [here](https://github.com/baracil/ojalgo-issue).

Is there something I do not understand or is the way I use the solver not adequate for this case ?

Thank You

Bastien

**Comment by apete** [comment]
It'll be a couple of days before I can look at this in detail.

If you turn on debug logging, and run in a debugger, you may gain some understanding.

`solver.options.debug(ConvexSolver.class);`

I always recommend to start using ExpressionsBasedModel rather than the solvers directly. ExpressionsBasedModel contains functionality that may be necessary in order to solve the problem.

**Comment by apete** [comment]
Here's the faulty iteration:

```
PerformIteration 12
Last Incl/Excl: 11/-1 => [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13] / [0, 2]
RHS=[-197.98293439988583, -53223.05393572833, 289040.77421320934, -813543.5294320501, 1065263.2856166917, -173690.4458531644, -884555.1775198452, 247862.34903686267, 762895.3175459494, -154405.29347097594, -577592.7809266244, 574334.6648122392]
Relative error 0.0065267109737203325 in solution for L=[-0.0012724366667372646, -6.719942918449121E-5, -1.6702093691617497E-4, -2.0279829246634017E-4, -1.9398197093026614E-4, -1.623296657942146E-4, -1.2145230748244847E-4, -7.881322970608284E-5, -3.8190297167408524E-5, -1.2967528080201341E-6, 3.127018209475647E-5, 2.974715986697202E-5]
Current: 0.0 - { 0.0, -0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0 }
Step: 8407.08638764574 - { 3.3830681359001424, -0.0667028228929179, 21.866460726443833, 28.449241804551562, 319.33350751900343, -978.3115397814216, -938.4084404108128, 5148.600794439978, -2452.459817627476, -6511.302389635464, 8407.08638764574, -3990.6636165924338, 2039.5918426414225, -1974.2382939267497 }
Included-change: { 0.0667028228929179, -28.449241804551562, -319.33350751900343, 978.3115397814216, 938.4084404108128, -5148.600794439978, 2452.459817627476, 6511.302389635464, -8407.08638764574, 3990.6636165924338, -2039.5918426414225, 1974.2382939267497 }
Nonzero Included-change! 8407.08638764574
Numer/slack: [0.0, 0.0]
Denom/chang: [-3.3830681359001424, -21.866460726443833]
Looking for the largest possible step length (smallest positive scalar) among these: [-0.0, -0.0]).
Performing update with step length 1.0 adding constraint -1
Post iteration
	Solution: { 3.3830681359001424, -0.0667028228929179, 21.866460726443833, 28.449241804551562, 319.33350751900343, -978.3115397814216, -938.4084404108128, 5148.600794439978, -2452.459817627476, -6511.302389635464, 8407.08638764574, -3990.6636165924338, 2039.5918426414225, -1974.2382939267497 }
	L: { 0.0, -0.0012724366667372646, 0.0, -6.719942918449121E-5, -1.6702093691617497E-4, -2.0279829246634017E-4, -1.9398197093026614E-4, -1.623296657942146E-4, -1.2145230748244847E-4, -7.881322970608284E-5, -3.8190297167408524E-5, -1.2967528080201341E-6, 3.127018209475647E-5, 2.974715986697202E-5 }
I-slack: { 3.3830681359001424, -0.0667028228929179, 21.866460726443833, 28.449241804551562, 319.33350751900343, -978.3115397814216, -938.4084404108128, 5148.600794439978, -2452.459817627476, -6511.302389635464, 8407.08638764574, -3990.6636165924338, 2039.5918426414225, -1974.2382939267497 }
Negative I-slack! -6511.302389635464
```

**Comment by baracil** [comment]
Hi,
Ok I will try to investigate tomorrow. Do you have any resource that you used to write the algorithm so that I can understand a bite more quickly what is going on ?

Thank you,

Bastien

**Comment by apete** [comment]
There are many books on the subject... ;-)

Only a subset of the inequalities are "active" at each iteration. In that method we have a proposed solution increment. We need to figure out if we can accept the entire proposed change and/or if we need to add one of the currently inactive constraints to be active in the next iteration. A typical result here would be to modify the current solution by a fraction of the proposed change, activate a constraint, and do another iteration.

Have a look at that method. I believe you may understand what's going, at least partly. If it's too much then just wait a couple of days for me to take a look at it.

That iteration is when the solution becomes invalid, but I see there are numerical problems in earlier iterations as well.

`Nonzero Included-change!`

Should not happen.

**Comment by baracil** [comment]
So before looking at the code, I tried using the ExpressionsBasedModel to perform the minimization. Although the solution now honor the inequality constraints, it seems that, even though the result is said optimal, the solution is not the optimal and far from it (I added a test in the test repo).

I think the root cause of the these two issues is the same but I cannot say for sure.

**Comment by baracil** [comment]
After looking at the code in the method `ActiveSetSolver#handleIterationSolution(...)`, I think the issue occurs when the the [stepLength](https://github.com/optimatika/ojAlgo/blob/50a614c78c756460be42b7e5ba0e96c9bf1612de/src/org/ojalgo/optimisation/convex/ActiveSetSolver.java#L100) variable is not [initialized](https://github.com/optimatika/ojAlgo/blob/50a614c78c756460be42b7e5ba0e96c9bf1612de/src/org/ojalgo/optimisation/convex/ActiveSetSolver.java#L139) and then has a default value of 1 that [produces](https://github.com/optimatika/ojAlgo/blob/50a614c78c756460be42b7e5ba0e96c9bf1612de/src/org/ojalgo/optimisation/convex/ActiveSetSolver.java#L158) an invalid solution.

I am not sure how to handle this case though and even if this is a problematic case after all.

**Comment by apete** [comment]
Can you try this?

https://github.com/optimatika/ojAlgo/compare/Issue300?expand=1#diff-0bdd4c6d62fd09781c95d1d0ba8f1a3471fa7dcb05f3605c1c0c45674a31d58f

**Comment by baracil** [comment]
Hi,
I relaunch somee analyses with the version of ojAlgo on the branch Issue300, and all the analysis that I had issue with, are now fine. So As far I am concerned, this is solved !

Thank you very much.
