### ISSUE TITLE
getEigenpair gets null pointer exception

### ISSUE THREAD

**Issue by hardlyb** [optimatika/ojAlgo#304]
Using ojalgo-48.3.1.jar

**Describe the bug**
Null pointer exception in getEigenpair.

    [junit] java.lang.NullPointerException
    [junit] 	at org.ojalgo.matrix.store.RawStore.countRows(RawStore.java:687)
    [junit] 	at org.ojalgo.matrix.store.TransjugatedStore.<init>(TransjugatedStore.java:36)
    [junit] 	at org.ojalgo.matrix.store.TransposedStore.<init>(TransposedStore.java:32)
    [junit] 	at org.ojalgo.matrix.store.RawStore.transpose(RawStore.java:1283)
    [junit] 	at org.ojalgo.matrix.decomposition.RawEigenvalue.getV(RawEigenvalue.java:320)
    [junit] 	at org.ojalgo.matrix.decomposition.Eigenvalue.getEigenpair(Eigenvalue.java:417)

**To Reproduce**

            double[][] test1 = new double[][] { { 4.0, 3.0, 2.0, 1.0 },
                                                { 3.0, 3.0, 2.0, 1.0 },
                                                { 2.0, 2.0, 2.0, 1.5 },
                                                { 1.0, 1.0, 1.5, 1.0 } };
            blowUp(test1);

        public static boolean blowUp(double[][] matrix) {
        int size = matrix.length;
        Eigenvalue<Double> decomp = Eigenvalue.PRIMITIVE.make(Primitive64Matrix.FACTORY.rows(matrix));
        if (!decomp.isOrdered()) throw new IllegalArgumentException("matrix not symmetric");
        for (int i = 0; i < size; i++) {
            System.out.printf("getting Eigenpair %d\n", i);
            Eigenvalue.Eigenpair pairI = decomp.getEigenpair(i);
        }
        return true;
    }

It prints "getting Eigenpair 0" and then the stacktrace shown above.

**Pull Request**
If you know how to fix the problem, then also provide a PR with a suggested fix.

**Comment by apete** [comment]
Yes, that's a bit of a design/usability problem.

`Eigenvalue<Double> decomp = Eigenvalue.PRIMITIVE.make(Primitive64Matrix.FACTORY.rows(matrix));`

Doesn't actually compute the decomposition. It only returns an appropriate implementation. You need to call

`decomp.decompose(theMatrixToDecompose);`

before you can access the various components or properties.

**Comment by hardlyb** [comment]
Thanks. That 'fixed' my bug. Sorry for the bogus report.
