### ISSUE TITLE
solution for binary variable not restricted to 0 and 1 when using expression simplification

### ISSUE THREAD

**Issue by pakkg** [optimatika/ojAlgo#309]
Using method `ExpressionsBasedModel.simplify` before maximization provides solution with wrong value for a binary variable; 0.5 for example.

Version 48.3.2.

**To Reproduce**
* Two **binary** variables: X, Y
* One constraint: X < Y * 0.5
* Function to maximize: X + Y
* Expected result: X = 0; Y = 1
* Result with simplification: X = 0.5; Y = 1

**Test Case**

```java
@Test
public void testSimplification() {

  NumberContext precision = NumberContext.getGeneral(14, 12);
  ExpressionsBasedModel model = new ExpressionsBasedModel();

  Variable varX = model.addVariable("X").binary();
  Variable varY = model.addVariable("Y").binary();

  // (X <= Y * 0.5)  equivalent to  (0 <= Y * 0.5 - X)
  // only one solution: X = 0, Y = 1
  Expression constraint =
    model
      .addExpression("X < Y * 0.5")
      .lower(ZERO)
      .set(varX, NEG)
      .set(varY, HALF);

  Expression objectiveFunction =
      model
        .addExpression("sum")
        .weight(ONE)
        .set(varX, ONE)
        .set(varY, ONE);

  Result result = model.maximise();
  Result resultWithSimplification = model.simplify().maximise();

  TestUtils.assertEquals(result.getValue(), resultWithSimplification.getValue(), precision);
}
```
Output:
```
AssertionFailedError: double != double: 1.0 != 1.5
```

**Comment by apete** [comment]
Looks like there's a problem. I'll have  look at this. Thanks for the test case.

**Comment by apete** [comment]
Believe I found and fixed a problem with the presolver, but I'm not done because now a number of other/old test cases fail. I have to look in to why that is.

https://github.com/optimatika/ojAlgo/tree/IntegerSolverProblems

**Comment by pakkg** [comment]
Great news! I'm eager to test this fix :)
