### ISSUE TITLE
set(Variable variable, double value) method in 37.1.1

### ISSUE THREAD

**Issue by pksiwan11** [optimatika/ojAlgo#323]
I have used `set(Variable variable, double value)` method in the 48.4.0 version. This method is present in `Expression` class. [[link to Expression Class of 48.4.0]](https://javadoc.io/doc/org.ojalgo/ojalgo/latest/org/ojalgo/optimisation/Expression.html)

Due to some dependency in Android Studio, I've to explicitly use 37.1.1 version. And I'm not able to find an alternative to this method that provides this functionality. [[link to Expression Class of 37.1.1]](https://javadoc.io/doc/org.ojalgo/ojalgo/37.1.1/org/ojalgo/optimisation/Expression.html)

Is there a replacement to this `set(Variable variable, double value)` method in 37.1.1 ?

**Comment by apete** [comment]
If I remember correctly v37.1.1 was the last version to not require Java 8 – that was a long time ago. Are you not able to move to Java 8?

This method in v37.1.1 should do the same thing: `void setLinearFactor(Variable variable, Number value)`

There should be tags for all versions if you want to branch and fix something.
