### ISSUE TITLE
Add the possibility to set the options of ExpressionBasedModel

### ISSUE THREAD

**Issue by sigma02** [optimatika/ojAlgo#324]
When creating an ExpressionBasedModel with MPS file, there is no possibility to set the optimisation options. This is very annoying for complex optimisation problems (which need timeout and logging). Maybe removing the final keyword in Abstract model is the solution?

**Comment by apete** [comment]
Please make an effort to create issues linked to the correct repository.

Doesn't this work for you?
```
ExpressionsBasedModel model = ExpressionsBasedModel.parse(file);

model.options.progress(ConvexSolver.class);

Result result = model.maximise();
```
