### ISSUE TITLE
ShadingStore supplyTo overflow

### ISSUE THREAD

**Issue by byrongibby** [optimatika/ojAlgo#330]
Before you sumit this issue; did you try with the latest version?!
```xml
    <dependency>
      <groupId>org.ojalgo</groupId>
      <artifactId>ojalgo</artifactId>
      <version>48.4.1</version>
    </dependency>
```
**Describe the bug**
It seems that when there are more columns than rows in an instance of _ShadingStore_, `.supplyTo` goes out of bounds in:
```java
public void supplyTo(final TransformableRegion<N> consumer) {

        consumer.reset();

        final int tmpColDim = this.getColDim();

        if (this.isPrimitive()) {

            for (int j = 0; j < tmpColDim; j++) {
                final int tmpFirst = this.firstInColumn(j);
                final int tmpLimit = this.limitOfColumn(j);
                for (int i = tmpFirst; i < tmpLimit; i++) {
                    consumer.set(i, j, this.doubleValue(i, j));
                }
            }

        } else {

            for (int j = 0; j < tmpColDim; j++) {
                final int tmpFirst = this.firstInColumn(j);
                final int tmpLimit = this.limitOfColumn(j);
                for (int i = tmpFirst; i < tmpLimit; i++) {
                    consumer.fillOne(i, j, this.get(i, j));
                }
            }
        }

    }
```
**Test Case**
```java
public class App 
{
    public static void main( String[] args )
    {
      double[][] data = { { 1.0, 2.0, 3.0, 10.0 }, { 4.0, 5.0, 6.0, 11.0 }, { 7.0, 8.0, 9.0, 11.0 } };

      PhysicalStore.Factory<Double, Primitive64Store> storeFactory = Primitive64Store.FACTORY;
      Primitive64Store m = storeFactory.rows(data);
      Primitive64Store r = storeFactory.makeZero(m.countRows(), m.countColumns());

      QR<Double> qr = QR.PRIMITIVE.make(true);
      qr.decompose(m);
      System.out.println( qr.getQ().toString() );
      qr.getR().supplyTo(r);
      System.out.println( r.toString() );
    }
}
```

>byron@arch2 ~/ojalgo-test> mvn exec:java -Dexec.mainClass=online.byrongibby.App
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< online.byrongibby:ojalgo-test >--------------------
[INFO] Building ojalgo-test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ ojalgo-test ---
org.ojalgo.matrix.store.Primitive64Store < 3 x 3 >
{ { -0.12309149097933259,       0.9045340337332904,     0.4082482904638633 },
{ -0.49236596391733084, 0.30151134457776413,    -0.8164965809277258 },
{ -0.8616404368553291,  -0.30151134457776385,   0.4082482904638628 } }
[WARNING]
java.lang.ArrayIndexOutOfBoundsException: 12
    at org.ojalgo.array.Primitive64Array.doubleValue (Primitive64Array.java:218)
    at org.ojalgo.array.PlainArray.doubleValue (PlainArray.java:78)
    at org.ojalgo.array.Array2D.doubleValue (Array2D.java:388)
    at org.ojalgo.matrix.store.Primitive64Store.doubleValue (Primitive64Store.java:588)
    at org.ojalgo.matrix.store.UpperTriangularStore.doubleValue (UpperTriangularStore.java:44)
    at org.ojalgo.matrix.store.ShadingStore.supplyTo (ShadingStore.java:52)
    at online.byrongibby.App.main (App.java:24)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:748)

**Pull Request**
I am not confident enough that this is indeed a bug, but if it is I would be happy to create a pull request.

Thanks in advance!

**Comment by apete** [comment]
Thanks for a well defined bug report.

I just looked at it briefly, but yes this appears to be a bug. As far as I can see the matrix returned by `qr.getR()` and `r` have the same dimensions in which case `qr.getR().supplyTo(r)` definitely should work.

I'll have a look at this in more detail later today.

You're very welcome to create a PR.

**Comment by apete** [comment]
https://github.com/optimatika/ojAlgo/pull/331

**Comment by byrongibby** [comment]
I can confirm that it works for my test case

>[byron@arch1 ojalgo-test]$ mvn exec:java -Dexec.mainClass=online.byrongibby.App
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------< online.byrongibby:ojalgo-test >--------------------
[INFO] Building ojalgo-test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.0.0:java (default-cli) @ ojalgo-test ---
org.ojalgo.matrix.store.Primitive64Store < 3 x 3 >
{ { -0.12309149097933259,	0.9045340337332904,	0.4082482904638633 },
{ -0.49236596391733084,	0.30151134457776413,	-0.8164965809277258 },
{ -0.8616404368553291,	-0.30151134457776385,	0.4082482904638628 } }
org.ojalgo.matrix.store.Primitive64Store < 3 x 4 >
{ { -8.12403840463596,	-9.601136296387953,	-11.078234188139945,	-16.986625755147912 },
{ 0.0,	0.9045340337332906,	1.809068067466581,	8.743828992755144 },
{ 0.0,	0.0,	6.661338147750939E-16,	5.329070518200751E-15 } }
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.410 s
[INFO] Finished at: 2021-04-14T23:10:39+02:00
[INFO] ------------------------------------------------------------------------

Thank you for the rapid response, much appreciated.

**Comment by apete** [comment]
Great. There will be a bug fix release soon. Just need to figure out if anything else should go in there.
