### ISSUE TITLE
BasicMatrix missing divide(final M)

### ISSUE THREAD

**Issue by rauar** [optimatika/ojAlgo#332]
Hi,

I'm currently updating an application from ojalgo 37.1.1 to the latest released version (48.4.1). Wading through all API changes 🤯 I struggle to find a substitute for element-wise division of matrices like A.divide(B) should result in ( A11/B11, A21/B21, etc...).

I see 
`````
public M add(final M addend)
public M multiply(final M multiplicand)
public M subtract(final M subtrahend)
`````
being available but for division there are only methods with scalars implemented.

I would have expected that 
`````
 public M divide(final M dividend)
`````

should exist as well but it does not. Am I missing something ?

I tried to subclass Primitive32Matrix for adding that method but it's marked final.

Thanks, Alex

**Comment by apete** [comment]
Yes, I believe element-wise division has been rationalised away. You'll have to do something like this:
```
        Primitive32Matrix mtrxA = ...;
        Primitive32Matrix mtrxB = ...;

        DenseReceiver mutable = mtrxA.copy();
        mutable.modifyMatching(DIVIDE, mtrxB);
        Primitive32Matrix modA = mutable.get();
```

All the BasicMatrix implementations are immutable so the copying always happens. The shorter syntax for `mtrxA.add(mtrxB)` essentially does the same thing
