### ISSUE TITLE
Allow access to eigenvalues of RawEigenvalue without creating an additional Array1D instance

### ISSUE THREAD

**Issue by hanslovsky** [optimatika/ojAlgo#34]
`RawEigenvalue.getEigenvalues()` returns the eigenvalues as an `Array1D<ComplexNumber>`. It creates a new `Array1D` and fills the array with the real and complex components of the eigenvalues. The components are accessed via `RawEigenvalue.getRealEigenvalues()` and `RawEigenvalue.getImagEigenvalues()` that both just return references to member variables:
https://github.com/optimatika/ojAlgo/blob/master/src/org/ojalgo/matrix/decomposition/RawEigenvalue.java#L234-L248
I would like to access the eigenvalues without creating any objects. However, `getRealEigenvalues` and `getImagEigenvalues` are private and I am forced to use `getEigenvalues` instead. This could be resolved easily by making these methods public.

edit: I just realized that it will not be as straight forward as I had imagined given that `RawEigenvalue` is package private.

**Comment by apete** [comment]
I've added a method

void getEigenvalues(double[],Optional<double[]>)

to the Eigenvalue interface, and an implementations in RawEigenvalue that is a first step. Looking at the code I realize there's lots of more optimisations that can be done, but those would fit under your other Issue.

**Comment by hanslovsky** [comment]
Thanks, I just confirmed that this and #33 work with my code.

**Comment by apete** [comment]
How exactly do you use the eigenvalue decompositions? I believe I saw you only wanted the eigenvalues, is that correct?

Could I have a test case that demonstrates your usage?

**Comment by hanslovsky** [comment]
I only need the eigenvalues, that is correct. I am using it to calculate image/volume features on tensors over n-dimensional images. In my specific use case, n is small but I don't know if that is true for all potential use cases in the imglib2 domain. The only current use-case for me is eigenvalues of the Hessian matrix.

I have an [`EigenValue`](https://github.com/hanslovsky/imglib2-algorithm/blob/hessian-eigenvalues/src/main/java/net/imglib2/algorithm/linalg/eigen/EigenValues.java) interface that gets called at every pixel/voxel location of an n-dimensional volume. I added an example implementation using a `org.ojalgo.commons.math3.linear.RealMatrixWrapper` on [a different branch](https://github.com/hanslovsky/imglib2-algorithm/blob/hessian-eigenvalues-ojalgo/src/main/java/net/imglib2/algorithm/linalg/eigen/EigenValuesSymmetricOJ.java). Eventually, I will get rid of the redirection through `Math Commons` and just use my own `ojAlgo` wrapper.

For a specific example, check out:
https://github.com/hanslovsky/imglib2-algorithm-hessian-examples/blob/ojalgo/src/main/java/de/hanslovsky/examples/Hessian2D.java
I have a closed form solution implementation of the interface for 2D but this is the most straight forward case to show as an example.

**Comment by apete** [comment]
I've done some general improvements to the various Eigenvalue implementations. In particular the symmetric case in RawEigenvalue has been improved. Pretty sure performance has been improved, but don't really know how much. There used to be a problem with "values only" - it calculated the eigenvectors anyway. That's fixed now.

Unless you find some problem I don't plan do more related to this issue.

**Comment by hanslovsky** [comment]
Great, I appreciated that, especially the fix with "values only"!
I'll checkout the latest commit and will run with my code!
