### ISSUE TITLE
Infinite recursion when trying to multiply two objects of SparseStore<ComplexNumber>

### ISSUE THREAD

**Issue by asmisloff** [optimatika/ojAlgo#360]
**Test Case**
public class test {

    public static void main(String[] args) {
        final int N = 100;
        SparseStore<ComplexNumber> Z = SparseStore.makeComplex(N, N);
        for (int row = 0; row < N; ++row) {
            int col = ThreadLocalRandom.current().nextInt(N);
            Z.set(row, col,
                    ComplexNumber.of(
                            ThreadLocalRandom.current().nextDouble(10),
                            ThreadLocalRandom.current().nextDouble(10))
            );

            Z.multiply(Z); //StackOverflowError here
        }
    }
    
}

**Comment by apete** [comment]
Thanks for reporting this problem. I'll fix it shortly.

**Comment by apete** [comment]
https://github.com/optimatika/ojAlgo/tree/hotfix/GitHubIssue360

If you could give this a try to.

**Comment by asmisloff** [comment]
Works well for me. I'm very appreciated!

**Comment by asmisloff** [comment]
Sorry for my english
