### ISSUE TITLE
org.ojalgo.matrix.decomposition.EvD2D.hqr2 not converging

### ISSUE THREAD

**Issue by heta78** [optimatika/ojAlgo#366]
Before you sumit this issue; did you try with the latest version?!
Yes, org.ojalgo:ojalgo:49.0.3 at the time of writing
**Describe the bug**
For a certain matrix, the function enters in an infinte loop
**To Reproduce**
1. ...Set up a java project with the latest version of library
2. ... read the attached matrix as the following
[Mat.txt](https://github.com/optimatika/ojAlgo/files/7121134/Mat.txt)
`final Eigenvalue<Double> EvD = Eigenvalue.PRIMITIVE.make();                
String path="C:/.../Mat.txt";
                List<String> lines = null;
                try {
                    lines = Files.lines(Paths.get(path)).collect(Collectors.toList());
                } catch (IOException e2) {
                    e2.printStackTrace();
                }
                PhysicalStore.Factory<Double, Primitive64Store> storeFactory = Primitive64Store.FACTORY;
                Primitive64Store G_2 = storeFactory.make(p, p);

                for(int r=0;r<lines.size();r++){
                    String[] line_vec=lines.get(r).split(" ");
                    for(int c=0;c<line_vec.length;c++){
                        double v=Double.parseDouble(line_vec[c]);
                        G_2.set(r, c, v);
                    }
                }

              EvD.decompose(G_2);`

3. ...Following the debugger, it is the method hqr2 that get stuck in a loop.

**Test Case**
If possile, write a test that demonstrates the problem.

**Additional context**

**Pull Request**
If you know how to fix the problem, then also provide a PR with a suggested fix.

**Comment by apete** [comment]
Thanks for reporting this. I've created a test case for it. This will require non-trivial debugging to find the problem and a fix.

**Comment by apete** [comment]
Could you verify that this

https://github.com/optimatika/ojAlgo/pull/373

solves your problem and doesn't introduce any new issues with other matrices you may have?
