### ISSUE TITLE
How to map all values in PrimitiveDenseStore with a function ?

### ISSUE THREAD

**Issue by tak2siva** [optimatika/ojAlgo#37]
Say I have an 2x2 matrix as PrimitiveDenseStore

pstore = [ 1 2 
           3 4 ]

Is there anyway to map all these values based on given anonymous function like
`
pstore.map(x -> x * x)
`
So the result is

pstore = [ 1 4
           9 16 ]

Linking https://stackoverflow.com/questions/44398173/ojalgo-how-to-map-update-all-the-values-in-primitivedensestore

**Comment by apete** [comment]
Please restrict Issues here at GitHub to bug reports, feature requests and similar - not user support.

Use either the ojAlgo-user mailing list or StackExchange for that.

... and don't cross post (I have answered you question at StackExchange).

**Comment by tak2siva** [comment]
Sure wasn't aware of the mailing list. And just now I have added StackExchange tag for this lib.

**Comment by apete** [comment]
Thanks for the StackExchange tag.
