### ISSUE TITLE
Releases not in Maven central

### ISSUE THREAD

**Issue by athy** [optimatika/ojAlgo#4]
The only version in maven central repository is the 31.0.
It would be great to have past releases in the central repository, as it would make it much easier to depend on your project.
For instance the "tweety" project depends on ojalgo 35, making it very difficult to use.

It would be great to have all releases in a maven repository (central or custom).

**Comment by optimatika** [comment]
The recently released v38 is available in the central repository. I'll see what I can do regarding making v35, v36, v37 and v37.1 available there as well (but won't go further back than that).

Why are you stuck at v35? Is something preventing you from upgrading to v37.1 (or v38 if you use Java 8)?

**Comment by optimatika** [comment]
v38.0, v37.1, v37.0, v36.0, v35.0 and v31.0 are now available at The Central Repository.

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.ojalgo%22%20AND%20a%3A%22ojalgo%22
