### ISSUE TITLE
DaemonPoolExecutor is creating too many thread when runs multiple DivideAndConquer in parellel

### ISSUE THREAD

**Issue by hotou** [optimatika/ojAlgo#40]
I found that when running multiple calculation in parallel. DaemonPoolExecutor is creating way too many threads, especially on a machine with a lot of cores. Do you guys think of any way to control that ? Why not using ForkJoinPool which is much better of managing target parallelism level.

**Comment by apete** [comment]
There are 2 different ways to control how many times a specific task is "forked":

1) Redefine org.ojalgo.OjAlgoUtils.ENVIRONMENT to something with fewer threads, This will be a global limit on forks for each task.

2) Set the THRESHOLD for the specific operation to something that suits your usage. Look at the classes in the org.ojalgo.matrix.store.operation package. The class org.ojalgo.matrix.MatrixUtils also has two methods setThresholdMinValue(int) and setThresholdMaxValue(int).

Have a look at the class org.ojalgo.concurren.DivideAndConquer to see how these things interact.

This is an area that will probably see some refactoring in the future.

ojAlgo did at one point switch to using ForkJoin (when it was relatively new) but it had some bug then that caused problems so the change was reverted.

**Comment by hotou** [comment]
I tried 
OjAlgoUtils.ENVIRONMENT = Hardware.makeSimple(VirtualMachine.getArchitecture(), VirtualMachine.getMemory(), 32).virtualise();
and 
MatrixUtils.setAllOperationThresholds(32);

None of them seems to be able to control the number of threads being created. 
![untitled](https://user-images.githubusercontent.com/116712/28427801-653fff4c-6d45-11e7-9130-312f16a46bf2.png)

**Comment by hotou** [comment]
BTW, I tried switching to ForkJoinPool seems all the unit test passed, and yield the same result on my app, I think you guys might want to give it another try, since we are in Java 8 now.

**Comment by apete** [comment]
How about just setting

MatrixUtils.setThresholdsMinValue(10000);

(something relatively large in comparison to the matrices you use)


The problem with redefining OjAlgoUtils.ENVIRONMENT is that each individual operations still assumes it has all the resources to itself.


Yes, maybe it’s time to give ForkJoin another try. Pull request are welcome.


/Anders

**Comment by apete** [comment]
I've checked in a code change that should prevent that kind thread explosion (without requiring you to redefine operation matrix size thresholds or similar). 

Moving to ForkJoin or not will be a later question.

**Comment by hotou** [comment]
Cool thanks

**Comment by apete** [comment]
If you test and find any issues with the change/fix then please reopen this issue.
