### ISSUE TITLE
Expression should have "add" method that takes Variable as argument.

### ISSUE THREAD

**Issue by buckfeng** [optimatika/ojAlgo#421]
While building a long `Expression`, I'd like to add variables by calling `Expression.add` method in a loop becasue the `add` method combines the value (coefficient) of the same `Variable` automatically.  However, the `Expression.add` method only takes `IntIndex` and doesn't take `Variable`.  The `Variable` doesn't have a method to get its `IntIndex` value (this method does exist but it is package-private).  To work around the situation, I have to do this:

```java
expression.add(Structure1D.IntIndex.of(getModel().indexOf(myvar)), 50d);
```

I'd like to request to have `Expression.add` to take `Variable` or make `Variable.getIntIndex()` method public, so that above code will work like this:

```java
expression.add(myvar, 50d);
```

**Comment by apete** [comment]
Agree, can do that.

The `IntIndex` and `IntRowColumn` usage is a bit "internal". You shouldn't be forced to use it.

**Comment by apete** [comment]
https://github.com/optimatika/ojAlgo/tree/Expression-add

Could you perhaps create junit tests that verify some basic cases?

**Comment by apete** [comment]
https://github.com/optimatika/ojAlgo/pull/422

**Comment by buckfeng** [comment]
```java
public class ExpressionAddVariableTest
{
	@Test
	void testAddingVariableToExpression()
	{
		ExpressionsBasedModel model = new ExpressionsBasedModel();
		Variable x1 = model.addVariable("x1").lower(0).upper(20).weight(1);
		Expression expr = model.addExpression("10 * x1 = 100").lower(100).upper(100);
		expr.add(x1, 4);  // add term (4 * x1) to expression
		expr.add(x1, 6);  // add term (6 * x1) to expression which now becomes (10 * x1)
		Optimisation.Result result = model.minimise();
		BigDecimal x1Result = result.get(model.indexOf(x1));
		Assertions.assertEquals(BigDecimal.valueOf(10), x1Result);
	}
}
```
