### ISSUE TITLE
Eigenvalues and Eigenvectors differing from MatLab implementation?

### ISSUE THREAD

**Issue by racs4** [optimatika/ojAlgo#427]
**Describe the bug**
Hello, and thanks for making this library.
I'm trying to replicate a code I have in Matlab for Java. But I couldn't get equal results when it comes to the generalized decomposition into eigenvalues/eigenvectors.
In MatLab this is done in the form ` [V,D] = eig(A,B)` where `AV = BVD` described [here](https://www.mathworks.com/help/matlab/ref/eig.html#d123e378419).
For ojAlgo I followed the example described [here](https://www.ojalgo.org/2019/08/generalised-eigenvalue-problems/), but I can't get the same results I was getting in MatLab.
Sometimes the result of eigenvalues is null which causes error when accessing eigenvectors.

**To Reproduce**
Just execute the code in Test Case.

**Test Case**
MatLab:
```
A = [3 12; 32 1];
B = [12 1; -45 32];
[V,D]=eig(A,B)
```
Results
```
V:
 -1.0000    0.5091
    0.6899    1.0000
    
D:
   -0.4668         0
         0    1.9027
```

ojAlgo:
```
public static void main(final String[] args) {
    double[][] A = {{3, 12},{32, 1}};
    Primitive64Store matrixA = Primitive64Store.FACTORY.rows(A);
    double[][] B = {{12, 1},{-45, 32}};
    Primitive64Store matrixB = Primitive64Store.FACTORY.rows(B);
    System.out.println("A = " + matrixA);
    System.out.println("B = " + matrixB);
    Eigenvalue.Generalised<Double> eig = Eigenvalue.PRIMITIVE.makeGeneralised(matrixA);
    eig.decompose(matrixA, matrixB);
    System.out.println("Eigenvales = \n" + eig.getEigenvalues());
    // Commented because gives error
    // System.out.println("Eigenvectors = \n" + eig.getEigenvectors());
  }
```
Results
```
A = org.ojalgo.matrix.store.Primitive64Store < 2 x 2 >
{ { 3.0,        12.0 },
{ 32.0, 1.0 } }
B = org.ojalgo.matrix.store.Primitive64Store < 2 x 2 >
{ { 12.0,       1.0 },
{ -45.0,        32.0 } }
Eigenvales = 
null
```

**Additional context**
Is there something more that I need to do to get a result equal to the MatLab?  The way I'm using ojAlgo is the same in the Test Case section.

**Comment by apete** [comment]
> where both A and B are symmetric/hermitian and B is positive definite.

**Comment by apete** [comment]
No, I don't.
