### ISSUE TITLE
Array index out of bounds exception while using IntegerStrategy

### ISSUE THREAD

**Issue by Jurian** [optimatika/ojAlgo#450]
Hello all,

I'm currently using this great library to calculate solutions to the [correlation clustering](https://en.wikipedia.org/wiki/Correlation_clustering) algorithm. Below is my code that builds the model and then calls maximise(). I hope I did it right :-)

     final int n = component.length; // number of vertices

        if(n < 3) return skip(n);

        final int edges = (n*(n-1))/2; // number of edges
        final ExpressionsBasedModel model = new ExpressionsBasedModel();
        final Variable[] vars = new Variable[edges];

        for(int i = 0, e = 0; i < n ; i++) {
            for(int j = i + 1; j < n; j++) {
                Variable x = model
                        .addVariable("x("+i+","+j+")")
                        .integer() // constrain to binary
                        .lower(0)  // constrain to binary
                        .upper(1)  // constrain to binary
                        .weight(Util.weight(component[i], component[j], vectors, theta, epsilon, penalties[e]));
                vars[e] = x;
                e++;
            }
        }

        // Add 3 constraints for every triangle in this component
        for(int[] triangle : Util.triangles(n)) {

            model.addExpression().upper(1) // constraint: x_ij + x_ik - x_jk <= 1
                    .set(vars[triangle[0]], 1)
                    .set(vars[triangle[1]], 1)
                    .set(vars[triangle[2]], -1);

            model.addExpression().upper(1) // constraint: x_ij - x_ik + x_jk <= 1
                    .set(vars[triangle[0]], 1)
                    .set(vars[triangle[1]], -1)
                    .set(vars[triangle[2]], 1);

            model.addExpression().upper(1) // constraint: - x_ij + x_ik + x_jk <= 1
                    .set(vars[triangle[0]], -1)
                    .set(vars[triangle[1]], 1)
                    .set(vars[triangle[2]], 1);
        }

        Optimisation.Result result = model.maximise();

However, sometimes I get this error: 

    java.lang.ArrayIndexOutOfBoundsException: Index 25 out of bounds for length 24
          at java.base/java.util.ArrayList.add(ArrayList.java:455)
          at java.base/java.util.ArrayList.add(ArrayList.java:467)
          at org.ojalgo.optimisation.integer.IntegerStrategy$ConfigurableStrategy.getWorkerPriorities(IntegerStrategy.java:93)
          at org.ojalgo.optimisation.integer.ModelStrategy.getWorkerPriorities(ModelStrategy.java:220)
          at org.ojalgo.optimisation.integer.IntegerSolver.solve(IntegerSolver.java:224)
          at org.ojalgo.optimisation.IntermediateSolver.solve(IntermediateSolver.java:117)
          at org.ojalgo.optimisation.ExpressionsBasedModel.optimise(ExpressionsBasedModel.java:1357)
          at org.ojalgo.optimisation.ExpressionsBasedModel.maximise(ExpressionsBasedModel.java:1082)

When looking in the source code it seems to have something to do with [distributing the load over different workers](https://github.com/optimatika/ojAlgo/blob/develop/src/main/java/org/ojalgo/optimisation/integer/IntegerStrategy.java) (line 93). Either that, or the myPriorityDefinitions array is too small. To what part of the model do the priority definitions belong?

Cheers

**Comment by apete** [comment]
I'm guessing this is concurrency related. The exception is thrown when adding an item to an `ArrayList`.

Do you solve multiple model simultaneously?

**Comment by apete** [comment]
Believe I've spotted a problem with the code (that could be a problem if you are solving multiple models simultaneously).

Whenever you create a new `ExpressionsBasedModel` then explicitly set a new integer strategy option:

`model.options.integer(IntegerStrategy.newConfigurable());`

Let me know if this solves your problem.

**Comment by apete** [comment]
Believe I've spotted a problem with the code (that could be a problem if you are solving multiple models simultaneously).

Whenever you create a new `ExpressionsBasedModel` then explicitly set a new integer strategy option:

`model.options.integer(IntegerStrategy.newConfigurable());`

Let me know if this solves your problem.

**Comment by Jurian** [comment]
I am indeed solving multiple problems simultaneously. It is difficult to reproduce this problem as it seems to occur randomly (as is often the case in these concurrency issues). I will change the code and see if it works. 

Since I am already using concurrency to solve multiple (small) problems at the same time, is there a way to constrain the solver to a single thread?

**Comment by apete** [comment]
Yes, that's what the `IntegerStrategy` is for:

`model.options.integer(IntegerStrategy.newConfigurable().withParallelism(Parallelism.ONE));`

Each of the worker threads (potentially) use different strategies for selecting the next node to evaluate. When/if you only have 1 worker thread you better make sure it's using the "right" strategy. If you set the parallelism to 4 you'll get 1 thread using each of the default strategies. To set your own strategy:

`integerStrategy.withPriorityDefinitions(...)`

Have a look here if you haven't already: https://www.ojalgo.org/2022/03/mip-strategy-configuration/

**Comment by Jurian** [comment]
Great! It seems that using multiple threads is a must have, unless I set my own priority definitions. 

I will check for errors with your proposed solution. I see that you also issued a fix where you move the worker priorities from IntegerStrategy` to `ModelStrategy`. Is this a better solution than what you proposed earlier?

Perhaps it would be nice if the parallelism was set to `ONE` the solver would search each priority sequentially and pick the best one after. That would be much slower, but hey, you set it to using a single thread.

**Comment by apete** [comment]
It's rarely that simple (but it could be in your case).

If you set the parallelism to 1 you can see how various strategies perform (choosing the node priority is not the only thing to consider).

Most likely you need different behaviour before and after a first integer solution is found.

The default configuration needs to cover all bases. With some experimentation you're very likely to find something that works better for your specific case.

Turn on progress logging when you experiment.

**Comment by apete** [comment]
Problem could happen if concurrently using multiple `ExpressionsBasedModel` instances that share the same `IntegerStrategy` instance (models will share by default).

A workaround is to create a new `IntegerStrategy` for each `ExpressionsBasedModel` – `model.options.integer(IntegerStrategy.newConfigurable());`.

The problem is fixed but do not plan a specific bug fix release only for this.
