### ISSUE TITLE
Implement non-linear constraints

### ISSUE THREAD

**Issue by voddan** [optimatika/ojAlgo#46]
The original SO question: https://stackoverflow.com/q/47378153/3144601

Currently it is possible to create a  model with non-linear constraints, but solving it results in an NPE. 

Please:
 - Provide a clear error instead of an NPE
 - Implement an assertion in the method that sets a quadratic constraint like `set(Variable, Variable, value)`
 - Describe all currently unsupported features in the documentation
 - Implement quadratic constraints in the solver

**Comment by apete** [comment]
Being able to solve anything/everything that can be modelled with ExpressionsBasedModel using built-in solvers has long been on my todo list. It's not trivial to do, and so far there has been no business incentive to do it.

I made some minor improvements to error handling and documentation in line with your suggestions.

**Comment by apete** [comment]
https://github.com/optimatika/ojAlgo/projects/3

I've "converted" this issue to a project that will in turn have a number of more concrete action points (issues).
