### ISSUE TITLE
hardware profile

### ISSUE THREAD

**Issue by jbaron** [optimatika/ojAlgo#493]
When running ojAlgo, I'm getting the following message:

```
Algo includes a small set of predefined hardware profiles,
none of which were deemed suitable for the hardware you're currently using.
A default hardware profile, that is perfectly usable, has been set for you.
You may want to set org.ojalgo.OjAlgoUtils.ENVIRONMENT to something that
better matches the hardware/OS/JVM you're running on, than the default.
Additionally it would be appreciated if you contribute your hardware profile:
https://github.com/optimatika/ojAlgo/issues
Architecture=aarch64 Threads=8 Memory=4294967296
```

So hereby the requested issue. My hardware is an Apple M1 Pro laptop with 16GB om memory. Just let me know if more info is required.

**Comment by apete** [comment]
Do you know anything about the cpu cache size/architecture of those processors? That's the main thing the hardware profiles try to model.

**Comment by jbaron** [comment]
The following I could find out, applicable to my 8 core M1 Pro machine:

Clock Rate: <=3220 MHz
Main memory: 16GB (256-bit LPDDR5 SDRAM memory). 
Memory bandwidth: 200GB/s
Level 1 Cache: 2.3 MB
Level 2 Cache: 28 MB
Level 3 Cache: 16 MB
Number of Cores / Threads: 8 / 8 (6 performance + 2 energy cores)
Transistor Count: 33700 Million
Manufacturing Technology: 5 nm
Features: ARMv8 Instruction Set

BTW,  10 core machines or M1 Max have different cache sizes.

**Comment by apete** [comment]
Are those cache sizes correct? - very different from an Intel CPU (Very large L1 and L2 larger than L3).

Are the L1 and L2 caches per core, and L3 per CPU? (as with Intel)?

This is the architecture of my Intel MacBook Pro:

MacBookPro16,1
1 processor
8 cores per processor (8 cores in total)
2 threads per core (16 threads in total)
64GB system RAM
16MB L3 cache per processor
256kB L2 cache per core
32kB L1 cache per core

**Comment by jbaron** [comment]
Why I could gather from various resources:

**L1 Cache**
- the high-perf cores have a large 192 KB of L1 instruction cache and 128 KB of L1 data cache
- The energy-efficient cores have a 128 KB L1 instruction cache, 64 KB L1 data cache 

Perhaps not very useful to add them them all together (like I did in the previous post) 

**L2 Cache (28MB all together)**
- The 8 high-perf cores are split in two clusters, each cluster has 12MB of shared L2 cache (so 24MB total)
- The 2 high-efficiency cores have 4MB of shared L2 cache

**L3 / SLC (24MB all together)**
- The SLC is 12MB per memory controller, so 24MB total (so not 16MB as I mentioned earlier).


P.S the days of CPU architecture are far behind me, so there might be some blatant mistakes, sorry for that up front.

**Comment by apete** [comment]
Ok, thanks, Will have to think about how to map this to ojAlgo's simplified hardware model. Seems either a "cluster" or a memory controller should be mapped to processor/unit. I'll post in this thread when I've pushed something you can try.

I'm on holiday now with poor internet connection. Plan to release a new version later this month. There will be support for `aarch64` in that release.

**Comment by apete** [comment]
https://github.com/optimatika/ojAlgo/pull/494
