### ISSUE TITLE
Quadratic Objective Function.

### ISSUE THREAD

**Issue by dmex38** [optimatika/ojAlgo#5]
Hello,

First many thanks for your great library.

I have a question about usage of the library, I'm not sure if it's an issue in the library or my problem is not well defined.

The situation :

From one side I have a list of Customer. (CUSTOMER_1, CUSTOMER_2, CUSTOMER_3,....)
From an other side I have distinct Type (version) of product (PRODUCT_TYPE_1,PRODUCT_TYPE_2, ...)

I create all available links between Customer and Product Type.
 Each link is a variable. It's represent the allocation of Product type X to the Customer X.

I create constraints for Customer level. (Ex: CUSTOMER_1 need <= 40_000)
 - The sum of all variables linked to CUSTOMER_1 <= 40_000

I create constraints for Product level. (Ex: PRODUCT_TYPE_1 <= 50_000)
 - The sum of all variables linked to PRODUCT_TYPE_1 <= 50_000
 
I try to maximize the allocation :
Max of (the sum of all variables)

But on other hand, I try to be fair, I try to split proportionally between customers:

For that, I compute the global ratio (stockTotal/demandTotal) and compute the squared error between the allocation and the global ratio.
I create for each Customer a Variable error and an expression to compute the error:

Error + Sum(Variables Customer X) / Demand Customer X = Stock Total / Demand Total

And I remove the Squared of each errors in the objective function.

The result I have with the OjAlgo Library is strange. The result can be different between run with the same data input.

Do you think, my problem is solvable by your library or not ? If yes, what I'm doing wrong ? 
Or is it possible there is a bug in OjAlgo library ?

My Test file is available here : https://github.com/dmex38/JavaExample/blob/master/OJAlgoTest 

Sometime I have this result :

OPTIMAL 49998.797722288284 @ [40000.0, 10000.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.425287356322, -0.174712643678, -0.574712643678, -0.574712643678, -0.574712643678]

0 <= CUSTOMER_1|PRODUCT_TYPE_1: 40000.000000 <= 40000.000000
0 <= CUSTOMER_2|PRODUCT_TYPE_1: 10000.000000 <= 25000.000000
0 <= CUSTOMER_3|PRODUCT_TYPE_1: 0 <= 15000.000000
0 <= CUSTOMER_3|PRODUCT_TYPE_2: 0 <= 15000.000000
0 <= CUSTOMER_3|PRODUCT_TYPE_3: 0 <= 15000.000000
0 <= CUSTOMER_3|PRODUCT_TYPE_4: 0 <= 15000.000000
0 <= CUSTOMER_3|PRODUCT_TYPE_5: 0 <= 15000.000000
0 <= CUSTOMER_4|PRODUCT_TYPE_1: 0 <= 5000.000000
0 <= CUSTOMER_4|PRODUCT_TYPE_2: 0 <= 5000.000000
0 <= CUSTOMER_5|PRODUCT_TYPE_2: 0 <= 2000.000000
0 <= CUSTOMER_5|PRODUCT_TYPE_3: 0 <= 2000.000000
0 <= CUSTOMER_5|PRODUCT_TYPE_4: 0 <= 2000.000000
0 <= CUSTOMER_6|PRODUCT_TYPE_2: 0
0 <= CUSTOMER_6|PRODUCT_TYPE_3: 0
0 <= CUSTOMER_6|PRODUCT_TYPE_4: 0
0 <= CUSTOMER_6|PRODUCT_TYPE_5: 0

And Sometime this :

---- Error formula ------
OPTIMAL 49998.917986454384 @ [23731.0, 25000.0, 1269.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0185623563218, 0.425287356322, -0.490112643678, -0.574712643678, -0.574712643678]

0 <= CUSTOMER_1|PRODUCT_TYPE_1: 23731.000000 <= 40000.000000
0 <= CUSTOMER_2|PRODUCT_TYPE_1: 25000.000000 <= 25000.000000
0 <= CUSTOMER_3|PRODUCT_TYPE_1: 1269.000000 <= 15000.000000
0 <= CUSTOMER_3|PRODUCT_TYPE_2: 0 <= 15000.000000
0 <= CUSTOMER_3|PRODUCT_TYPE_3: 0 <= 15000.000000
0 <= CUSTOMER_3|PRODUCT_TYPE_4: 0 <= 15000.000000
0 <= CUSTOMER_3|PRODUCT_TYPE_5: 0 <= 15000.000000
0 <= CUSTOMER_4|PRODUCT_TYPE_1: 0 <= 5000.000000
0 <= CUSTOMER_4|PRODUCT_TYPE_2: 0 <= 5000.000000
0 <= CUSTOMER_5|PRODUCT_TYPE_2: 0 <= 2000.000000
0 <= CUSTOMER_5|PRODUCT_TYPE_3: 0 <= 2000.000000
0 <= CUSTOMER_5|PRODUCT_TYPE_4: 0 <= 2000.000000
0 <= CUSTOMER_6|PRODUCT_TYPE_2: 0
0 <= CUSTOMER_6|PRODUCT_TYPE_3: 0
0 <= CUSTOMER_6|PRODUCT_TYPE_4: 0
0 <= CUSTOMER_6|PRODUCT_TYPE_5: 0

**Comment by optimatika** [comment]
I just had a quick look at your problem. The model is a little too symmetric, that's why ojAlgo struggles with it. If you turn on debug printing and model validation you'll be able to see some of what goes on.

        model.options.debug(ConvexSolver.class);

ojAlgo could/should be tweaked to handle cases like this, but I can't promise when I'll be able solve that problem.

**Comment by optimatika** [comment]
There's a fuzzy line between a bug and a modelling issue. You have definitely hit a weak spot in ojAlgo, but I believe you can avoid it by modifying your model.

The reason you get different results between executions is an indication that ojAlgo struggles with the model. The algorithm uses an element of randomness to break out of cyclic state. Sometimes (but not always) this solves your model.

I believe your model will be easier to solve (for ojAlgo) if you do not introduce those ERROR variables (nor the ERROR_EXP expressions that link those variables to the other variables). It's better if you simply express the error in terms of the already existing variables.

In most cases it is not beneficial to model redundant constraints - don't routinely set both lower and upper limits on all expressions. In many cases you only need to limit expressions on one side (lower or upper).

I'm keeping your model as a test case, but it does not clearly pinpoint a specific (fixable) problem.

**Comment by dmex38** [comment]
Hello Optimatika,

First many thanks for your answer, 

I take your advice to design the model.
Starting the previous test case, I've made some modifications:
- Suppress unnecessary constraints (keep only upper for constraints Customer and Product)
- Remove intermediate variables (ERROR and ERROR_EXP).
- Express the error directly with existing variables.

The result is here : https://github.com/dmex38/JavaExample/blob/master/OJAlgoTest2

But unfortunately, the result is the same, some time good some time wrong.

**Comment by optimatika** [comment]
Equality constraints are good - much better than inequality constraints - don't remove the upper or lower bound on such constarints. The advice to not routinely set both lower and upper limits was primarily aimed towards avoiding double inequalities.

Those warnings/exceptions you get when you turn on validation should be taken seriously. ojAlgo may be able to solve the model anyway (if you turn off validation) but you really should think about why those warnings are there and then try to remove them.

The primary issue I see with ojAlgo in this case is regarding error detection and reporting. I'll see what I can do to improve that.

**Comment by optimatika** [comment]
I've just checked in improvements/additions to the ExpressionsBasedModel presolver that seems to fix your problem. As far as I can see ojAlgo can now handle the 2 models you supplied (and doesn't break any previously existing test cases).

**Comment by dmex38** [comment]
Hello optimatika, 
First many thanks for your support. I've tried to my more complex problem and I have the same problem of resolution. Some time right solution, some time not. I will try to construct a little example with the error and send you the links.

**Comment by apete** [comment]
When you send me something that demonstrates the problem I'll reopen this issue.

**Comment by dmex38** [comment]
Please find the example with issue : https://github.com/dmex38/JavaExample/blob/master/OJAlgoTest3
Many thanks.

**Comment by apete** [comment]
I really believe you should reconsider how you model this problem.

I did a small tweak of ojAlgo so that it reaches 560300.4702803734 more often than before, but it still sometimes only reach 560300.4015031556.

I also tried submitting your model to CPLEX (via the ExpressionsBasedModel). CPLEX is consistent but "only" reaches 560300.4691158283...

Rescale the problem parameters sent to CPLEX (to try to improve numerical accuracy) it will return a slightly different objective function value realised by a radically different solution.

When/if you turn on model validation and you get an exception "Q must be positive semidefinite!" that's something you should look into. This last example of yours has 52 variables. About 30 eigenvalues of the Q matrix are 0.0 or very small, and some of the very small ones are negative.

**Comment by apete** [comment]
The ConvexSolver is now deterministic! You will now get the same solution with every solve of the same model.
