### ISSUE TITLE
Submatrix as a view

### ISSUE THREAD

**Issue by dclong** [optimatika/ojAlgo#53]
Does ojAlgo support a submatrix as views? That is a submatrix does not make copy of data but instead pointing to data in the original matrix.

**Comment by apete** [comment]
You can do `marixStore.logical().offsets(a,b).limits(c,d).get()` os some other combination.

If you want to discuss or ask these kind of questions then please join the mailing list: https://sourceforge.net/p/ojalgo/mailman/ojalgo-user/
