### ISSUE TITLE
Optimization - Don't require names for variables and expressions

### ISSUE THREAD

**Issue by thomasnield** [optimatika/ojAlgo#54]
Hi there, 

I've been having a great time with ojAlgo optimization and have [even started a series of blog articles on it](http://tomstechnicalblog.blogspot.com/2018/01/kotlin-for-linear-programming-part-ii.html). I also have a clear plan for some [okAlgo](https://github.com/thomasnield/okAlgo) extensions which I will donate later to optimatika if they are wanted.

One thing I find myself doing frequently is creating Kotlin extensions on `ExpressionsBasedModel` to not require names for variables or expressions. It's a bit of a pain to concatenate name arguments especially when my OOP design will organize the variables for me. For instance: 

```kotlin 
data class Driver(val driverNumber: Int,
                  val rate: Double,
                  val availability: IntRange? = null) {

    val shiftStart = variable().lower(6).upper(22)
    val shiftEnd = variable().lower(6).upper(22)
}
```

I don't care about naming the variables, and I typically will just assign an incremented numeric name to a variable automatically using Kotlin extensions like this: 

```kotlin 
// custom DSL for  expression and variable inputs, eliminate naming and adding
val funcId = AtomicInteger(0)
val variableId = AtomicInteger(0)
fun variable() = Variable(variableId.incrementAndGet().toString().let { "Variable$it" })
fun ExpressionsBasedModel.addExpression() = funcId.incrementAndGet().let { "Func$it"}
```

Before I start building closure API's for okAlgo, I wanted to propose adding some overloads to eliminate the requirement to name variables and expressions.

**Comment by thomasnield** [comment]
Just to give some more insight, I'm also trying to support more intuitive expression building that Kotlin enables like this: 

```kotlin 
val v1 = variable(lower = 3, upper = 10)
val v2 = variable(lower = 10, upper = 12)

model.addExpression((3 * v1) + (2 * v2) GT 4)
```

**Comment by apete** [comment]
I suppose ExpressionsBasedModel could get two new methods addVariable() and addExpresssion() that will generate names internally. Would that work for you?

**Comment by thomasnield** [comment]
That would be great, and I figured it wouldn't be hard to add. It would take a huge GC management burden off the Kotlin extensions I'm building, because I don't have to manage extended state on the `ExpressionsBasedModel`. I'll even put in a PR if you want. 

And it is on my docket to do a JitPack build and test your IP solver fixes, especially against some suboptimal model design scenarios where performance suffered to a crawl. I'll do it tomorrow at work. 

Mastering and extending this library is my priority right now, so I'll contribute anywhere and everywhere I can.

**Comment by apete** [comment]
It’s done.

How does this lighten the GC burden? ojAlgo now generates a name for you – it’s just that you don’t have to worry about it.

The changes I made recently would primarily decrease memory consumption and GC activity. But that could shorten solve times significantly.

Regarding your particular problem you may want to read about “special ordered sets”. ojAlgo currently has no specific support for this. I thought maybe it would be possible to implement a presolver specific to your use case.

I’ve noticed your activities and I welcome you willingness to contribute. I do my best to support those who contributes back.

/Anders

**Comment by thomasnield** [comment]
@apete It had nothing to do with the processing, just simple referencing for the model declaration. [I was maintaining a separate state](https://github.com/thomasnield/okAlgo/blob/master/src/main/kotlin/org/nield/okalgo/optimization.kt#L9-L18) for each `ExpressionsBasedModel` for the incrementers. Nothing major, but with this change it's no longer needed.

I'll research that. Thankfully I found some patterns that are effective and useful without presolving, but I don't know if I'll have to resort back to my old ones that were underperforming. Thank you, and I'll keep you posted.
