### ISSUE TITLE
invert method got wrong result

### ISSUE THREAD

**Issue by gx304419380** [optimatika/ojAlgo#540]
Before you sumit this issue; did you try with the latest version?!

**Describe the bug**

**To Reproduce**
`        
double[][] a = {
                {1, 0, 0, 0, 0, 0, -1, 0, 0, 0, 0},
                {0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0},
                {0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0},
                {0, 0, 0, 1, 0, 0, -1, 0, 0, 0, 0},
                {0, 0, 0, 0, 1, 0, -1, 0, 0, 0, 0},
                {0, 0, 0, 0, 0, 3294104700.0, 0, 0, -3294104700.0, 0, 0},
                {0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0},
                {-245980000, 0, 0, 0, 0, 0, 0, 1634776400, 0, 0, 0},
                {0, 0, 0, 0, 0, 0, 0, -2079832300, 2079832300, 0, 0},
                {0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0},
                {0, 0, 0, 0, 0, -16395321.6, 0, -150812632.8, -393902424, 0, 3.6}
        };

        MatrixR064.FACTORY.rows(a).invert().toRawCopy2D();
`

run the java code you will get a wrong inverse matrix:

1.9104108394140476E-15	-2.7755603435895157E-23	1.3822536140821288E-15	-1.8404109075663993E-15	-9.090662204638276E-16	-5.895122064135262E-11	-1.748132508139986E-15	-4.065371168387659E-9	-2.3365822484441515E-9	0.0	-1.1844323504176636E-8	
-8.558114146727279E-10	0.9999999999999994	-6.314941849701287E-10	1.711623110560073E-9	-1.2841571127125705E-16	-2.96762293710258E-18	8.558115826222804E-10	-3.4791905011761546E-18	6.054335568147066E-19	0.0	-1.8701516717667334E-16	
1.2188581416711705E-8	-6.408608443279391E-17	0.9999999999235863	-2.4377163555699416E-8	2.8737075043259834E-16	6.097372844104933E-17	-1.218858145152679E-8	1.1331488937575673E-17	9.550931081518965E-17	0.0	-7.048201362271328E-16	
-0.5	-9.06363382452437E-17	2.1769408158053316E-16	0.9999999999999996	-7.216449660063518E-16	-2.947547867408596E-11	0.49999999999999867	-2.032685549862347E-9	-1.1682910708796101E-9	0.0	-5.92216199619007E-9	
-0.5000000000000006	-4.2064083192639785E-17	-1.7088394395104713E-16	-3.3306690738754696E-16	0.9999999999999998	-2.94756123247706E-11	0.49999999999999867	-2.0326855756142343E-9	-1.1682911171202128E-9	0.0	-5.922161581738575E-9	
1.837712586185336E-16	6.9361489489728655E-18	2.476915959412084E-17	-4.756626702573729E-17	-1.652325424233296E-16	2.9470240481880804E-10	-1.6298186408988281E-16	2.3169429900914997E-24	1.2922933263475664E-10	0.0	-1.7821805450319513E-9	
-0.5000000000000001	-1.6835827595681625E-16	4.4505681926084755E-17	-8.326672684688674E-17	-1.1102230246251565E-16	-2.947558891621324E-11	0.499999999999999	-2.0326855642377704E-9	-1.1682911057834035E-9	0.0	-5.922161626460105E-9	
2.8621050148058713E-16	-4.182395713590284E-24	2.0798363910051384E-16	-2.769212204591803E-16	-1.3678452241420088E-16	-8.870216901442703E-12	-2.642797635668493E-16	2.4185638056698913E-24	-3.515786632791444E-10	0.0	-1.7821805450319496E-9	
2.9312691896356595E-16	1.3870429584713022E-18	6.15573227646767E-17	-2.7761730391387417E-16	-1.4853157079878081E-16	-8.870216901442779E-12	-2.723196284586197E-16	2.761441575705116E-24	1.2922933263475695E-10	0.0	-1.7821805450319503E-9	
0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	1.0	0.0	
3.19796732026506E-8	-6.301979330872437E-16	-2.509339121043618E-15	-2.1319782698444848E-8	-2.131978186101474E-8	2.621945481141716E-18	-3.197967320265051E-8	3.033548966907713E-16	1.7495142873117255E-16	0.0	9.181170001887602E-16	
------------------

**Test Case**
If possile, write a test that demonstrates the problem.

**Additional context**

**Pull Request**
If you know how to fix the problem, then also provide a PR with a suggested fix.

**Comment by apete** [comment]
How is it wrong?

The matrix is not full rank. What you get is the pseudo-inverse.

Try calculating A * inv(A) * A. If that gives you back A, then it is correct.

**Comment by gx304419380** [comment]
I use the ejml library and Excel to calculate the same matrix inverse，and they got the same result which is 
![image](https://github.com/optimatika/ojAlgo/assets/30303760/3cb1e16e-80b5-4bfb-897d-17db996769ab)

and this result is correct
