### ISSUE TITLE
Allocation of number of non-zero elements in SparseStore

### ISSUE THREAD

**Issue by ArmoredCat** [optimatika/ojAlgo#547]
Since sequentally filling a huge SparseStore matrix can be a bottleneck, a method or way to preallocate the number of non-zero elements like Matlab's 'spalloc' method would be a great way to circumvent this. A multithreaded implementation could be a possibility.

**Comment by apete** [comment]
I implemented this for 54.0.0-SNAPSHOT yesterday. I believe it will be some time before v54 is released, and there will be more than the usual amount of changes in it.

What version are you using? I could backport this to a version 53.3.1 or 53.4.0 

With or without these changes, it is important to fill the elements in a strictly index-increasing order  - column major.

**Comment by ArmoredCat** [comment]
I'm currently using 53.3.0. 

Regarding the right way to fill, using this matrix

1  4  7
2  5  8
3  6  9

you would be filling it this way right?

1 -> 2 -> 3 -> 4 -> 5 -> 6 -> 7 -> 8 -> 9

Thank you for your fast responses!

**Comment by apete** [comment]
Yes, that's the correct way. You can try doing 1 -> 4 -> 7 -> 2 -> 5 -> 8 -> 3 -> 6 -> 9 just to see how big the difference is.

If possible you also try a build of v54.0.0-SNAPSHOT to see if setting this initial capacity helps. Just clone the repository, checkout the `development `branch and do `mvn clean package -DskipTests`

**Comment by ArmoredCat** [comment]
Thank you very much, the correct way to populate a matrix plus the initial capacity did wonders on runtime! Although it would probably be great to have an easier way to set initial capacity, it's quite hidden right now.
