### ISSUE TITLE
QR Decomposition's getInPlace returns null

### ISSUE THREAD

**Issue by superyuuki** [optimatika/ojAlgo#548]
Before you sumit this issue; did you try with the latest version?!

**Describe the bug**
I go to use the QR decomposition and it is suddenly null

**To Reproduce**
I am doing this:
<img width="898" alt="image" src="https://github.com/optimatika/ojAlgo/assets/92664603/faf8660b-99d0-4e30-9d0c-047bbdb084c4">
I get a nullpointerexception
```
java.lang.NullPointerException: Cannot invoke "org.ojalgo.matrix.decomposition.DecompositionStore.aggregateDiagonal(org.ojalgo.function.aggregator.Aggregator)" because the return value of "org.ojalgo.matrix.decomposition.QRDecomposition.getInPlace()" is null

	at org.ojalgo.matrix.decomposition.QRDecomposition.getRankThreshold(QRDecomposition.java:224)
	at org.ojalgo.matrix.decomposition.MatrixDecomposition$RankRevealing.getRank(MatrixDecomposition.java:263)
	at org.ojalgo.matrix.decomposition.MatrixDecomposition$RankRevealing.isFullRank(MatrixDecomposition.java:272)
	at xyz.auriium.mattlib2.auto.ff.FastPolynomialRegression.loadRankDeficient_iterative(FastPolynomialRegression.java:59)
	at xyz.auriium.mattlib2.auto.PolynomialRegressionTest.testFastPolyReg(PolynomialRegressionTest.java:26)
```

**Test Case**
If possile, write a test that demonstrates the problem.

**Additional context**

**Pull Request**
i wish i knew

**Comment by apete** [comment]
`QR.R064.make(...)` does not calculate the decomposition. You have to call `decompose(...)`. No internal data is present until you have calculated a decomposition.

**Comment by superyuuki** [comment]
ah, it would be nice to have some documentation specifying that behavior. Thank you for elaborating.

**Comment by superyuuki** [comment]
Also, MatrixR064.FACTORY.make(Shape2d shape) is confusing, and I was using it in the place of MatrixR064.FACTORY.copy(Access2d access) for a while until I realized it only creates an empty matrix with the shape of the dataful matrix. While in hindsight this is made clear by the parameter types, it would be nice to have either documentation for the make function or a separate name

**Comment by apete** [comment]
Yes I know this is somewhat of a problem. I'll see what I can do about it.
