### ISSUE TITLE
Off-by-one error in MultiplyRight.invoke for SparseStore

### ISSUE THREAD

**Issue by henryem** [optimatika/ojAlgo#55]
In v44.0.0, lines 717-722 of MultiplyRight say this:

            final int tmpFirstInColumn = MatrixUtils.firstInColumn(right, j, 0);
            final int tmpLimitOfColumn = MatrixUtils.limitOfColumn(right, j, complexity);

            for (int c = tmpFirstInColumn; c < tmpLimitOfColumn; c++) {
                AXPY.invoke(product, j * tmpRowDim, 1, right.doubleValue(c + (j * complexity)), left, c * tmpRowDim, 1, 0, tmpRowDim);
            }

I believe there's a bug either in `MatrixUtils.limitOfColumn` or in its usage here, which can cause the last element in a column to be ignored.  For example, the following Scala code incorrectly computes `[1 0; 0 0; 0 0] * [1 0; 0 1] = [0 0; 0 0; 0 0]` with SparseStores:

    val m = SparseStore.PRIMITIVE.make(3, 2)
    val n = m.add(PrimitiveDenseStore.FACTORY.rows(Array(1.0, 0.0), Array(0.0, 0.0), Array(0.0, 0.0)))
    val eye = SparseStore.PRIMITIVE.make(2, 2)
    eye.set(0, 0, 1.0)
    eye.set(1, 1, 1.0)
    val prod = n.multiply(eye)
    println(n.toRawCopy2D.map(_.toSeq).toSeq) // WrappedArray(WrappedArray(1.0, 0.0), WrappedArray(0.0, 0.0), WrappedArray(0.0, 0.0))
    println(eye.toRawCopy2D.map(_.toSeq).toSeq) // WrappedArray(WrappedArray(1.0, 0.0), WrappedArray(0.0, 1.0))
    println(prod.toRawCopy2D.map(_.toSeq).toSeq) // WrappedArray(WrappedArray(0.0, 0.0), WrappedArray(0.0, 0.0), WrappedArray(0.0, 0.0))

I'm not sure whether `MatrixUtils.limitOfColumn` is meant to return the index of the last nonzero in the column (in which case the limit in the for-loop is wrong), or one greater than that.  I believe it's the latter, because for nonsparse matrices it would return 2 in this case.

**Comment by apete** [comment]
I translated your Scala code into this java code:

`
        final SparseStore<Double> m = SparseStore.PRIMITIVE.make(3, 2);
        final PrimitiveDenseStore mAdd = PrimitiveDenseStore.FACTORY.rows(new double[][] { { 1.0, 0.0 }, { 0.0, 0.0 }, { 0.0, 0.0 } });
        final MatrixStore<Double> n = m.add(mAdd);

        final SparseStore<Double> eye = SparseStore.PRIMITIVE.make(2, 2);
        eye.set(0, 0, 1.0);
        eye.set(1, 1, 1.0);

        final MatrixStore<Double> prod = n.multiply(eye);

        BasicLogger.debug("n", n);
        BasicLogger.debug("eye", eye);
        BasicLogger.debug("prod", prod);
    `

I see no problem running this code, but I don't recognise the code from MultiplyRight. Don't remember fixing any bug, but I have tweaked various multiplication code. Could you try with the latest source code from the repository.

BTW: Why don't you just do: `m.set(0,0,1.0);`

**Comment by henryem** [comment]
Thanks!  That mostly fixes the problem, but it introduces a new bug in the case where a column in a sparse matrix (on the right) has no nonzeros:

        int tmpFoundAt = this.index(rangeLimit - 1L); // tmpFoundAt=-1
        if (tmpFoundAt < 0) {
            tmpFoundAt = -(tmpFoundAt + 2); //tmpFoundAt = -(-1 + 2) = -1
        }
        if (tmpFoundAt >= myActualLength) { // Not true
            return rangeFirst;
        } else {
            return Math.min(myIndices[tmpFoundAt] + 1L, rangeLimit); // Attempts to find myIndices[-1]
        }

It works when I change the second if-condition to `tmpFoundAt >= myActualLength || tmpFoundAt < 0`.  Maybe there's a more elegant solution.

I know the support for sparse matrices is still under development.  I don't think I have the time now, but I might be able to contribute some unit tests in a couple weeks.

**Comment by apete** [comment]
It would be much appreciated if could the time to contribute some test cases. I'd prefer if you close this issue (rather than me) when we you've asserted that the problem is fixed.

**Comment by henryem** [comment]
I checked against 3df00fb, and I believe this is fixed.  Thank you!
