### ISSUE TITLE
Deploying okAlgo

### ISSUE THREAD

**Issue by thomasnield** [optimatika/ojAlgo#56]
Hi @apete,

I'm at the point where I'm ready to start deploying okAlgo `0.0.1` to Maven Central so myself and others can test it as a dependency. 

I wanted to pass it by you first and offer to have it put under the optimatika domain rather than mine `org.nield`. I think the core features at the moment are DSL's and [PuLP-like expression sytnax](https://github.com/coin-or/pulp).

https://github.com/thomasnield/okAlgo

Thoughts?

**Comment by apete** [comment]
@thomasnield 

Good work, and thanks for the offer!

I think it's best if you tell me directly/exactly what you would prefer. It's best to have a concrete proposal to discuss around. Most likely I'll be fine with whatever you propose...

**Comment by thomasnield** [comment]
I think it would be great to put it under your domain, optimatika. I'll maintain and grow it since I'm vested heavily in ojAlgo and Kotlin.

The scope of this library will focus on taking advantage of Kotlin language features to make ojAlgo even nicer to use. The initial focus will likely be on constraint solvers and expression builders, but I'll expand to matrices and other parts of the API where it makes sense before it hits a 1.0 version.

I can put something more formal in the readme to define the scope. But hopefully that's a satisfactory proposal.

**Comment by apete** [comment]
That’s fine by me. I’ll be glad to give okAlgo a home at optimatika next to everything else ojAlgo.

I assume you plan to move the repository as is to optimatika. Have you thought about things like package names, artefact group/id, license and copyright? It pays to think about these things in advance.

**Comment by thomasnield** [comment]
@apete I'm pretty flexible for the administrative stuff.  Let me refactor the package names to fall under `org.ojalgo.okalgo` before you fork it. Does it sound okay to put it under the `org.ojalgo` group?

I think "okAlgo" would be a good artifact name as Kotlin libraries like to brand things with a "k". 

It looks like I used MIT license, same as ojAlgo. I'll mirror copyright as well.

**Comment by apete** [comment]
I like to think I’m flexible too. ;-)

okAlgo seems a good artefact/project/module name.

**Comment by thomasnield** [comment]
Okay, ready to fork!

**Comment by thomasnield** [comment]
I've not migrated a project to a new domain before. Can you create an empty okAlgo repo and I'll move files over to it? I'm not sure if I have the rights to create repos.

**Comment by apete** [comment]
I've never done this either, but I have noticed a "transfer" button under repository settings (danger zone). I assumed that's what we should use in this case. Do you want to try that?

**Comment by thomasnield** [comment]
Got this message. I just made you a collaborator for `okAlgo`. See if you can do the transfer.
![image](https://user-images.githubusercontent.com/7420801/35752677-6b968fb4-0822-11e8-899a-3fd4c34afb71.png)

**Comment by apete** [comment]
Seems strangely difficult to do “transfer”.

I forked the repository to optimatika, but of course then it says that it was forked from thomasnield/okAlgo. What happens if you delete the original/root repository?

Or maybe we should just do what you suggested from the beginning.

/Anders

**Comment by apete** [comment]
Deleting a public repository

When you delete a public repository, one of the existing public forks is chosen to be the new parent repository. All other repositories are forked off of this new parent and subsequent pull requests go to this new parent.

https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/


optimatika currently has the only fork of okAlgo - should be ok.

**Comment by thomasnield** [comment]
okay excellent. What I may just do instead is delete all the contents from the original repository and replace it with a "this is now hosted under optimatika" with a link.

**Comment by thomasnield** [comment]
Hmm... actually, we don't want optimatika to be displayed as a fork, so I'll delete it later.

**Comment by thomasnield** [comment]
Alright, deleted. Transfer was successful. Thanks Anders!
