### ISSUE TITLE
ElementConsumer And Suppliers is out of date

### ISSUE THREAD

**Issue by TDI-tenderholt** [optimatika/ojAlgo#59]
I just tried the example from https://github.com/optimatika/ojAlgo/wiki/Element-Consumers-and-Suppliers. It's not compiling with 44.0.0 because `multiplyLeft` is no longer present. Has this been replaced by `premultiply`?

**Comment by apete** [comment]
Yes, it is now updated.

For each of the wiki pages that have example code there is a corresponding java file. If you clone the wiki repository you get all those example files, and they are continuously kept up to date.
