### ISSUE TITLE
UNBOUNDED but should be INFEASIBLE

### ISSUE THREAD

**Issue by flaghacker** [optimatika/ojAlgo#62]
Run the following code:

```java
Variable x = Variable.make("x").lower(0).weight(1);
Variable y = Variable.make("y").lower(0).weight(0);

ExpressionsBasedModel model = new ExpressionsBasedModel();
model.addVariable(x);
model.addVariable(y);

model.addExpression("first").set(x, 0).set(y, 1).lower(1);
model.addExpression("second").set(x, 0).set(y, 1).upper(-1);

ExpressionsBasedModel.clearPresolvers();

Optimisation.Result result = model.maximise();
System.out.println(result);
```

This prints `UNBOUNDED 0.0 @ [0.0, 0.0]`, but the problem is actually infeasible, since y can't be >=1 and <=-1.

This is kind of a dumb edge case so feel free to close it as such, I'm reporting it just in case.

**Comment by apete** [comment]
Using the latest version from git I don't see this problem. I get INFEASIBLE both with presolvers on and off.
