### ISSUE TITLE
INFEASIBLE but should be DISTINCT

### ISSUE THREAD

**Issue by flaghacker** [optimatika/ojAlgo#64]
Run the following code:

```java
Variable x = Variable.make("x").lower(0).weight(3);
Variable y = Variable.make("y").lower(0).weight(-2);

ExpressionsBasedModel model = new ExpressionsBasedModel();
model.addVariable(x);
model.addVariable(y);

model.addExpression().set(x, -1).set(y, 0).lower(0);
model.addExpression().set(x, -1).set(y, 3).level(2);

Optimisation.Result solution = model.maximise();
System.out.println(solution);
```

The result is `INFEASIBLE -1.3333333333333333 @ [0.0, 0.6666666666666666]`, but the program is actually DISTINCT: the point (0, ~1/3~ 2/3) doesn't conflict with any of the constraints:
```
x >= 0
y >= 0
-x >= 0
-x + 3y = 2
```

**Comment by apete** [comment]
The point (0, 1/3) does violate the second expression.

`0.9999999999999999999999999999999999 ! 2 <= EXPR1 <= 2` 

You can turn on validation by doing: `model.options.debug(LinearSolver.class);`

and then check your proposed solutions this way:

`      model.options.debug(LinearSolver.class);
        final BigArray propsed = BigArray.wrap(new BigDecimal[] { BigMath.ZERO, BigMath.THIRD });
        Assert.assertTrue(model.validate(propsed));
`

**Comment by flaghacker** [comment]
My bad, I meant (0, 2/3), the point the solver actually outputs. It does pass the validation code.

**Comment by apete** [comment]
Ok, pull and try again.

**Comment by flaghacker** [comment]
Fixed in the latest commit.
