### ISSUE TITLE
TaskException is missing

### ISSUE THREAD

**Issue by danilcha** [optimatika/ojAlgo#71]
`TaskException` is used in the matrix example (https://github.com/optimatika/ojAlgo/wiki/Getting-Started), exists in the official docs: http://ojalgo.org/generated/org/ojalgo/matrix/task/TaskException.html, but does not exist in
```
        <dependency>
            <groupId>org.ojalgo</groupId>
            <artifactId>ojalgo</artifactId>
            <version>44.0.0</version>
        </dependency>
```

**Comment by apete** [comment]
I've updated the javadoc and example code to be in line with the upcoming v45. That should be ok for v44 as well.
