### ISSUE TITLE
It looks like I somehow accidentally deleted https://github.com/optimatika/ojAlgo/wiki/Getting-Started page

### ISSUE THREAD

**Issue by danilcha** [optimatika/ojAlgo#72]
I was editing https://github.com/optimatika/ojAlgo/wiki/Getting-Started page to fix https://github.com/optimatika/ojAlgo/issues/71, then I wanted to update my revision comment and I think I somehow deleted the whole page. I also do not see any history there, hope you can rollback the deletion.

**Comment by danilcha** [comment]
Sorry!

**Comment by apete** [comment]
No problem. The wiki is a git repository so it's possible to revert any changes. You made pushed twice. Should I revert both of them, and you start again?

Let me investigate what's wrong code, wiki, javadoc...

**Comment by danilcha** [comment]
Hi! Yes, I recovered it from the repo.

**Comment by apete** [comment]
I just saw/realised that you had fixed the problem. Now I reverted everything, including the "fix". Did anything get lost then?

I've updated that code example, and the java doc to be compatible with v45.0.0-SNAPSHOT

**Comment by danilcha** [comment]
I made some modifications to the code, mostly that IntelliJ IDEA was complaining about, such as names like `storeClater` (changed to `storeCLater`), also in-code comments starting with `/**` (documentation  comments). I also removed `final` everywhere in the code to make it less cluttered (this you probably wouldn’t like). There are also a few typos. Should I change all that?

**Comment by apete** [comment]
I appreciate your willingness to contribute.

Fixing typos, or anything that's clearly wrong, is of course no problem.

Code changes is slightly more "sensitve". One should make sure to actually fix a problem. That said, as you noted, several of the examples are due for an update, and cleaning the examples from clutter like "final" is a good idea. (I'll keep them in ojAlgo, but the usage examples are probably better off without them.)

If you check out the entire wiki repo you'll find all the java example files there. There are java-files with names matching the md-files. You can code and run the examples using those, then just copy-paste to the md-files.

v45 will hopefully be released soon. Examples shpuld target that version.

**Comment by danilcha** [comment]
I did that for Getting-Started, but cannot push into the wiki repo, 403. This time I also wrapped all lines at 80 chars (the code width in GitHub wiki). I would also remove all logging and leave just Sytem.out.println of the matrices. Should I?

**Comment by apete** [comment]
Are you using GitHub Desktop?

 

I can’t check in wiki changes from GitHub Desktop, but it works from eclipse (and I suppose from the command prompt)

 

The BasicLogger is distracting for many, but it does have some features in formatting output (like printing matrices). Is the console output still readable?

 

/Anders

**Comment by danilcha** [comment]
I tried both IDEA and `git`, looks like I lack permissions:
```
remote: Permission to optimatika/ojAlgo.wiki.git denied to danilcha.
```

You are right, `toString` output is untidy (I assumed logger uses it):
```
org.ojalgo.matrix.store.PrimitiveDenseStore < 5 x 3 >
{ { 0.2169694061096615,	0.13995925620235347,	0.09301725038723954 },
{ 0.10092204991787194,	0.245036341010496,	0.13418974971026393 },
{ 0.2392931612797665,	0.08491193357729993,	0.070921600278032 },
{ 0.07546128408037431,	0.18885062817020407,	0.1620353818580702 },
{ 0.18351862578344572,	0.17802446135139743,	0.13155076087328416 } }
```

**Comment by apete** [comment]
Don't know why. As far as I can see the the wiki is configured to not restrict/limit updates.

I invited you to be an ojAlgo collaborator. I assume that will also increase your privileges for the wiki.

I see what you've done with the getting started page - it's an improvement! Thank you!

**Comment by apete** [comment]
I can't push to the wiki git depository either - don't know what happened.

**Comment by danilcha** [comment]
Thanks! I see that you have pushed a commit, what was it that you couldn't?

**Comment by apete** [comment]
It started to again after a while. Guess some temporary problem. Maybe that was the problem for you as well.
