### ISSUE TITLE
Rename test classes as quick fix for Travis

### ISSUE THREAD

**Issue by apete** [optimatika/ojAlgo#80]
@alf239 

> The tests were not run as it's a JUnit 3-style approach that requires the test classes to be named BlahBlahTest; so BlahBlahCase classes are quietly ignored.

**Comment by alf239** [comment]
Please please please don't

**Comment by alf239** [comment]
Check out https://github.com/optimatika/ojAlgo/pull/81 - the fix is to add `@Test` on the test of interest.

**Comment by apete** [comment]
Is it that bad?

**Comment by apete** [comment]
ok, scrap this.
