### ISSUE TITLE
Timezone-dependent tests?

### ISSUE THREAD

**Issue by alf239** [optimatika/ojAlgo#86]
It seems that `org.ojalgo.type.TimeIndexTest#testFrom` does not like BST :)
```
junit.framework.AssertionFailedError: OffsetDateTime 
Expected :2018-03-25T11:08:47.800+01:00
Actual   :2018-03-25T10:08:47.800Z

	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at org.ojalgo.TestUtils.assertEquals(TestUtils.java:322)
	at org.ojalgo.type.TimeIndexTest.doTestFrom(TimeIndexTest.java:24)
	at org.ojalgo.type.TimeIndexTest.testFrom(TimeIndexTest.java:78)
...
```
The line in question is, 

```
TimeIndexTest.doTestFrom(TimeIndex.OFFSET_DATE_TIME, CalendarDate.toOffsetDateTime(instant, SYS_DEF_ZONE),
        CalendarDate.toOffsetDateTime(reference, SYS_DEF_ZONE));
```

Note that `instant` is `2018-03-25T10:00:00.073Z` here, while `reference` is `2008-03-24T23:48:00.073Z`, which is probably a red herring.

**Comment by alf239** [comment]
The real cause seems to be,

> Daylight saving time 2008 in United Kingdom began at 01:00 on
> **Sunday, 30 March**
> and ended at 02:00 on
> Sunday, 26 October
> All times are in United Kingdom Time.

while 

> Daylight saving time 2018 in United Kingdom began at 01:00 on
> **Sunday, 25 March**
> and ends at 02:00 on
> Sunday, 28 October
> All times are in United Kingdom Time.

**Comment by alf239** [comment]
So we're in daylight saving time (BST, UTC+1) now in 2018, while 10 years ago we would still be in GMT.

**Comment by apete** [comment]
It fails for me as well. (Stockholm) Must be daylight saving time related (it's that day today).

**Comment by apete** [comment]
If you think this is fixed (correctly) then please close this issue.

**Comment by alf239** [comment]
Looks good to me; I would probably extract the explicit offset `OffsetDateTime.ofInstant(zoneToOffsetConversionInstant, zone).getOffset()` rather than pass it as a "reference instant", but that's merely my preference.
