### ISSUE TITLE
Average function along rows/columns of a matrix

### ISSUE THREAD

**Issue by imyoungmin** [optimatika/ojAlgo#91]
It is highly useful to have the average function running along the rows or columns of a matrix.  For example, let `A = [[1,2,3], [4,5,6]]` be a `2x3` matrix.  We should be able to compute the average along the columns and rows, and obtain a row and column vector, respectively, with the results.  For `A`, the average along the columns would be the row vector `[2.5, 3.5, 4.5]`, while the average along the rows would be the column vector `[2, 3]^T`.

**Comment by apete** [comment]
I've implemented something in the feature/Reduce branch:

https://github.com/optimatika/ojAlgo/tree/feature/Reduce

In particular look at the changes to Access2D and MatrixStore from this commit:

https://github.com/optimatika/ojAlgo/commit/07d3b31d2a97d02460f30219b784e71a15eb7fa0

What are these functions called in Numpy and Matlab?

**Comment by apete** [comment]
I think I'm done now:

https://github.com/optimatika/ojAlgo/compare/develop...feature/Reduce

In particular look at these 3 interfaces:

- Structure2D.ReducibleTo1D
- StructureAnyD.ReducibleTo1D
- StructureAnyD.ReducibleTo2D

Does this seem useful to you?

**Comment by apete** [comment]
I have now merged this to the develop branch
